### ISSUE TITLE
Add Project to Map Throws Mask Error

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#100]
When adding the project to the map an exception is triggered with the build mask layer function:

<img width="1447" alt="Screen Shot 2022-08-15 at 1 21 10 PM" src="https://user-images.githubusercontent.com/34071692/184711803-4cccc7bd-b1ec-4cc6-9acc-19d50acc74f2.png">

**Comment by philipbaileynar** [comment]
Working in 0.1.3-alpha
