### ISSUE TITLE
Design Status Not Updating

### ISSUE THREAD

**Issue by kunztr** [Riverscapes/QRiS#102]
While creating or editing a design, the dropdown menu does not update to the chosen value and instead remains as the default value when you open the edit menu again. 

Instructions to replicate:
1. Create New Project
2. Create New Design and give it a name
3. Change 'Design Status' from 'Specification' to 'As Built'.
4. Click 'OK'
5. Edit the design you just created.
6. Note that the 'Design Status' is still set to 'Specification'

**Comment by philipbaileynar** [comment]
Fixed for 0.1.3-alpha
