### ISSUE TITLE
Populate Acknowledgements Page & Plumb About to it

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#106]
I like the About Dialog:
![image](https://user-images.githubusercontent.com/9723905/191284459-6d5250f8-c697-47f7-b588-65610ca734f6.png)

If you give me the address to the page, I can create it and get it started.  Once you find provide URL it is looking for, assign back to me @philipbaileynar.

**Comment by philipbaileynar** [comment]
https://github.com/Riverscapes/QRiS/blob/dev/docs/dotnethack.md

Note that this file is only on the dev branch. Push your changes there. They will not publish until we push master (or I cherry pick that change onto master)

**Comment by joewheaton** [comment]
Sorry, does that mean that `dotnethack.md` is the `acknowledgements' page and I should be editing that, or do we need to add an acknowledgements page?

**Comment by philipbaileynar** [comment]
The dot net hack is the acknowledgements page for the app about form. 

`acknowledgements.md` is the acknowledgements page for the web site.
