### ISSUE TITLE
Change "Issues" to "Discussion" and link to https://github.com/Riverscapes/QRiS/discussions

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#107]
I know that we have directed people to our issue boards in the past for issues, but it clutters up the issue board. My preference would be for us to direct traffic to the discussion board. Then people can post, search, help each other out, and we keep a little bit of traffic out of the issues. If we find out that there is really an issue, we can then raise it as a bug or whatever it needs to be (easy to convert discussions to issues and/or make a new issue from a discussion). 
![image](https://user-images.githubusercontent.com/9723905/191285021-ac3cd0ab-798c-470e-8493-506ab1bd2e2b.png)

**Comment by philipbaileynar** [comment]
https://github.com/Riverscapes/QRiS/blob/dev/docs/dotnethack.md

Note that this page is only on the `dev` branch so pushing your changes will not cause the site to get published and page appear. After you're done, I can cherry pick your commit onto master to publish this page.

**Comment by philipbaileynar** [comment]
Implemented in 0.1.3-alpha
