### ISSUE TITLE
Where is "Scratch Space"?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#110]
I know we have discussed various things, but I was confused in this release of 0.1.2 where that went? In old version one of the first things I did was get my AOI masks, and then started importing "Context". Now the only thing in context is the `Create New Pour Point Catchment`.  I should be able to add in any raster or vector layer and just add it to the project or clip it by mask. 

![image](https://user-images.githubusercontent.com/9723905/191528288-52d36694-0e10-4bfc-9205-8d689e6dbc13.png)

I know @nick4rivers doesn't like the term "Scratch Space", but I don't know if I like forcing all this sort of information into "Context".  Some of it will be used for a) context, whereas some of it is used as b) actual inputs for analysis (e.g. DEMs, or HAND, or VBET likelihood but I guess you would call that a Basemap); and still some of it used as c) a starting point for digitization in a DCE (e.g. valley bottom polygon or channel area polygon), which I then improve in a DCE.

**Comment by philipbaileynar** [comment]
I have scratch space working for rasters but not vectors. I commented it out for this release for that reason. Would you like a release with it back?

**Comment by philipbaileynar** [comment]
Fixed with 0.1.3-alpha

- New right click option on scratch space group node to "Browse to Scratch Space"
- can now create scratch space rasters (with optional clipping to mask)
- can now create scratch space vectors (no option to clip to mask)
