### ISSUE TITLE
Change Command to `Run USGS StreamStats (US Only)`

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#111]
Lets be clear what we're doing and not take credit it for it. We're just letting the user run StreamStats from within there project and then we call the USGS API and try to get results.  I think the command is `Run USGS StreamStats (US Only)`
![image](https://user-images.githubusercontent.com/9723905/191529404-58ba9547-c71a-4a76-94f1-34ff5887ee74.png)

Please also add the error check that if a Lat/Long is entered outside the US, it tells them "This is a service by USGS and is only available in some US States. See https://streamstats.usgs.gov/ss/ for more information."

**Comment by philipbaileynar** [comment]
Implemented in 0.1.3-alpha
