### ISSUE TITLE
QRiS needs a logo and icon - QRiS needs to look more distinctive from QRAVE

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#117]
@philipbaileynar this will be an Aida task (not one we should do), but we absolutely need a Riverscapes Studio icon that we plan on using here and 

There are good ways to suggest consistent look and feel. This IS NOT one of them:
![image](https://user-images.githubusercontent.com/9723905/192581822-a93ee1f9-55ae-4dcf-9213-fdf00168720c.png)

The main command that brings up the panel, should not be an RC logo. In both cases this has been a place holder. Also the unnecessary overlap between similar buttons is confusing.

**Comment by KellyMWhitehead** [comment]
This is has been done for a while now!

**Comment by philipbaileynar** [comment]
The. Please close it.
