### ISSUE TITLE
Could not install 0.1.4 Error

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#119]
I tried installing the new release by uninstalling 0.1.3 and installing from zip and although the dialog said "Plugin Installed Successfully", QGIS through this message instantly:
```
Couldn't load plugin 'qris_deploy' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'rasterio' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\__init__.py", line 40, in classFactory
    from .src.qris_toolbar import QRiSToolbar
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 42, in 
    from .view.frm_dockwidget import QRiSDockWidget
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 68, in 
    from ..gp.metrics_task import MetricsTask
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\gp\metrics_task.py", line 9, in 
    from .metrics import Metrics
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\gp\metrics.py", line 5, in 
    import rasterio
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'rasterio'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.24.3-Tisler Tisler, cf22b74e 

Python Path:
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python
C:/Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.24.3\bin\python39.zip
C:\PROGRA~1\QGIS32~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.24.3\bin
C:\PROGRA~1\QGIS32~1.3\apps\Python39
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\GDAL-3.4.3-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/joemw/AppData/Roaming/QGIS/QGIS3\profiles\default/python

```

I was therefore unable to test 0.1.3. 

Even after doing this, it still showed up in the Plugins (incorrectly) but was check off. Checking it on, throws same error message. 
![image](https://user-images.githubusercontent.com/9723905/193288135-152ec156-57a9-425f-a7f2-576a974a281c.png)

**Comment by joewheaton** [comment]
I went back to 0.1.3 and reinstalled succssefully, but still no luck on 0.1.4

**Comment by philipbaileynar** [comment]
I introduced a dependency on rasterio to support raster statistics. Worked fine with my version of qgis. What version of qgis are you using?

**Comment by joewheaton** [comment]
Version:

> QGIS version
> 3.24.3-Tisler
> QGIS code revision
> cf22b74e
> Qt version
> 5.15.3
> Python version
> 3.9.5
> GDAL/OGR version
> 3.4.3
> PROJ version
> 9.0.0
> EPSG Registry database version
> v10.054 (2022-02-13)
> GEOS version
> 3.10.2-CAPI-1.16.0
> SQLite version
> 3.38.1
> PDAL version
> 2.3.0
> PostgreSQL client version
> unknown
> SpatiaLite version
> 5.0.1
> QWT version
> 6.1.6
> QScintilla2 version
> 2.13.1
> OS version
> Windows 10 Version 2009
> 
> 
> 
> 
> Active Python plugins
> qfieldsync
> v4.2.0
> qrave_toolbar
> 0.7.0
> db_manager
> 0.1.20
> grassprovider
> 2.12.99
> MetaSearch
> 0.3.6
> processing
> 2.12.99
> qris_deploy
> 0.1.3

**Comment by philipbaileynar** [comment]
@MattReimer see that @joewheaton got an installation error with the latest QRiS install because I introduced a dependency on `rasterio`. Thoughts?

**Comment by MattReimer** [comment]
Nothing comes quickly to mind. Did you try installing it yourself on your non-dev qgis profile. Repro is where I would start.

**Comment by MattReimer** [comment]
JUst a quick followup. I was wrong about rasterio. QGIS does not include it so we can't use it with QGis and will need to find another windowing method.

**Comment by philipbaileynar** [comment]
We can write our own `rasterio.mask()` operation using `gdal.ReadAsArray()` and pass in the bounding box of the polygon (see this [example](https://riptutorial.com/gdal/example/25844/read-subset-of-a-global-raster-defined-by-a-bounding-box)). We will then need to convert the polygon to NumPy and SetNull on cells outside the polygon.

But this is incredibly fiddly code to write that will need unit tests to avoid off-by-one errors and other edge effects.

**Comment by MattReimer** [comment]
Here's a starting place (maybe)

https://chris35wills.github.io/moving_window_functions/

**Comment by philipbaileynar** [comment]
New 0.1.5 release that has no dependencies on rasterio.

**Comment by MattReimer** [comment]
I believe this is solved. Closing

**Comment by joewheaton** [comment]
0.1.5 worked for me on install.
