### ISSUE TITLE
'Basemap' collision in TOC between QRAVE and QRiS

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#120]
Now that we are adding "Basemaps" to QRiS projects and we have basemaps in QRAVE we get a collission when adding basemaps from QRAVE. The problem is actually (I think) in QRAVE, where it seems like it just searches the tree from top to bottom and adds a basemap (e.g. Google Map) in the first "Basemap" layer group that occurs in the tree. In practice, this means that the basemap for overall context is now sucked up way high where it should not be (i.e. in a DCE). We still need basemaps in DCEs.

See:
https://youtu.be/k4m1lq6f_44

## Fix?
Maybe change in RAVE the `Basemaps` folder that gets put at bottom of tree to `Raster Basemaps` or  and separate out the `Cartographic Basemaps` vector layers. More fundamentally, be specific from QRiS where you look in tree (i.e. in subfolder of QRiS project for `Basemaps`.

**Comment by philipbaileynar** [comment]
This might be fixed because:

1. We are using the new map manager in QRiS
2. We no longer call them basemaps in QRiS


I am leaving this open for testing, but also because it might crop up when we tackle #194
