### ISSUE TITLE
Zonal Stats Issue When Polygon Off Raster

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#121]
I adapted some of Konrad's code to perform zonal stats within QRiS. It works great except when the polygon extends off the raster extent. See below.

- [QRiS Zonal Stats Code](https://github.com/Riverscapes/QRiS/blob/dev/src/gp/zonal_statistics.py)

The problem is that the polygon bounding rectangle is used to extract values from the raster. In the example below the polygon produces a negative column number which then errors out (see the `None` result in the table).

The solution is to use min/max to limit the columns and rows read from the raster and then transform these rows and cols back onto the polygon bounding extent correctly.

<img width="1608" alt="Screen Shot 2022-10-05 at 2 27 38 PM" src="https://user-images.githubusercontent.com/8645379/195220863-748b8694-f4a6-4860-b060-870336968d24.png">

**Comment by KellyMWhitehead** [comment]
fixed in f52f482252241c8a01a444d14dd16521d65c565d
