### ISSUE TITLE
Would be nice to add Stream Gages to QRiS

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#122]
![image](https://user-images.githubusercontent.com/9723905/93632164-17f65e80-f9aa-11ea-8e5b-e1f0f1261ffd.png)

**Comment by KellyMWhitehead** [comment]
Stream gages added to version 0.3.18

Please file any enhancements, changes, bugs, etc. as new tickets.

**Comment by philipbaileynar** [comment]
@KellyMWhitehead please close
