### ISSUE TITLE
About - Needs updating of website & dotnethack.md

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#124]
INPROGRESS
- [ ] Update the Website to https://qris.riverscapes.net/
![image](https://user-images.githubusercontent.com/9723905/196487041-3bc48ea9-88d0-4d4c-9d43-d655bbafff0b.png)
- [ ] Please merge [pull request](https://github.com/Riverscapes/QRiS/pull/126) from Joe (or fix as necessary) and confirm that it shows up in Acknowledgements

**Comment by philipbaileynar** [comment]
Fixed for 0.1.6.alpha
