### ISSUE TITLE
Design Assessment SQLite DB

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#13]
Some task

**Comment by nick4rivers** [comment]
@joewheaton - what is this referring to? Should this be for the entirety of a QRIS project? Or simply stick to a handful of assessment types? i.e., #21 and #26. Is this something we should develop ASAP?

**Comment by philipbaileynar** [comment]
My understanding is that this is the design of the SQLite database to hold the contents of the Excel Indicator form spreadsheet.

However, we left off the last call with several unanswered topics about this database relating to its dimensionality. Not least of which is whether a QRIS project can have multiple definitions of riverscapes segments.

But if you feel confident, why don't you start a Google Drawing to lay out the tables, columns and relationships for this database. Here's a BRAT example should you want an indication of how I go about these diagrams:

![brat schema](https://docs.google.com/drawings/d/e/2PACX-1vStWrxD4ZPoZqWN90m3BdNOpaAwT6rVSzUAUWixsePOJGKYWLKEOxgmHGkEhKx0o6ia_wxztdJVdZGi/pub?w=919&h=784)

**Comment by joewheaton** [comment]
Seems like this is superseded by: https://docs.google.com/drawings/d/1MQM0WEwrSaiZEEBgOFwtRV6UZgMJRprxn5GLN-DR9EU/edit?usp=sharing

![image](https://user-images.githubusercontent.com/9723905/192115493-9cf6c8be-0a87-4f1e-8086-141e15e6bb05.png)
