### ISSUE TITLE
We need a `Close Project` command that closes project

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#130]
![image](https://user-images.githubusercontent.com/9723905/196515950-7512e88e-52fb-4b90-a7fb-f8d428f10bb4.png)
We should add to right-click Project context menu a `Close Project and QGZ` command that will:

1.  Remove project from QRiS Panel (i.e. clear it)
2.  Prompts and asks user if they want to save the `.qgz` project before closing (if yes, offer to name project with same safe name as project` and save it in the project folder. 
3.  Open a new empty `.qgz` Project.

This follows logic of RAVE and would be very helpful.

**Comment by philipbaileynar** [comment]
I have implemented a "Close Project" right click menu item. This empties the map and closes the project dockable window. 

This operation currently performs no `.qgz` operations. QRiS as a rule does not interact with the QGIS document. It is more like ArcRAVE than QRAVE in this regard.

**Comment by joewheaton** [comment]
> I have implemented a "Close Project" right click menu item. 

Thank you.

>This empties the map and closes the project dockable window.

Okay. Does the "empty the map" only empty the stuff under the layer group with the name of the project? I don't know if users will like that per se. I didn't actually ask for either of those things. As a user, I might want to:
- Close a QRiS project _without emptying_ my map.
- Close a QRiS project and reopoen that project as a _troubleshooting step_, and not have to add the layers back to the map and fiddle with order and what was on and off.
- Close a QRiS project and re-load it to just start with a clean map.
- Close a QRiS project and start or open a new one in a different place. 

Among the many problems with doing what you're doing are:
- I may have other stuff in my map I don't want you to obliterate and clear! It is a GIS after all.
- I may be working in a QGZ I really like (it is not all about QRiS). You just ruined it when all I was trying to do was close the QRiS project in the tree.
- Why does the panel go away when I close the project? I can see it emptying, but going way is annoying. 
- If you clear the map of its contents, without actually creating a new empty map (`qgz`), the user may not realize that you are still stuck in the same projection and zoom level as wherever you were last in that QRiS project. Thus if they start adding new layers to the map and expect them to behave like a new map (i.e. projection gets assigned and zoom to extents of first layer added), you have confused users. This is why we did it the way I suggested specifically here as we did in GCD! 
 
> This operation currently performs no `.qgz` operations. QRiS as a rule does not interact with the QGIS document. It is more like ArcRAVE than QRAVE in this regard.

You have mentioned this before. I think we should discuss this. I don't know if I completely agree with or follow your logic. `QGZ`s are much more reliable and people use them then `mxd`s.  Also, @MattReimer pointed out that you can control and QRAVE does control this. For example, if you save a `qgz` that has layers in it from open QRAVE projects, when you re-open that qgz, those projects are also re-opened in QRAVE tree. That is really, really nice. So it can be done. I think we should discuss including that here.

## Back to my suggestion

We could do what you're doing on `Close` and ask user if they want to 
- `Also close the current map`
- `Keep current map, but clear table of contents`
- `Just close project, leave map contents alone`

We should add to right-click Project context menu a Close Project and QGZ command that will:

Remove project from QRiS Panel (i.e. clear it)
Prompts and asks user if they want to save the .qgz project before closing (if yes, offer to name project with same safe name as project` and save it in the project folder.
Open a new empty .qgz Project.

**Comment by joewheaton** [comment]
Currently the only way to close a QRiS project is to Quite QGIS. 

I illustrate that in this video: https://youtu.be/7mslneMveXw

Also in the video, I illustrate that you can control the QGZ from our plugin and we already do a nice job of this in QRAVE.

**Comment by philipbaileynar** [comment]
Implemented in 0.1.6-alpha:

- Close project now implementeded by righting clicking on the project.
- Project dockable window closes
- Map layers are left in the tree.
- QGZ now remembers the QRiS project and attempts to open it if it exists.
- QRiS layers are more loosely coupled with the map ToC. This allows saving the QGZ, closing and reopening QGIS, loading the same QGZ and all the map layers will be unchaged AND WILL BE RECOGNIZED by QRiS.

Closing this ticket for now. Create new, specific tickets that reflect on changes needed from 0.1.6-alpha.
