### ISSUE TITLE
What happens when a project is open and you close the current QGZ?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#132]
Currently, when you close a QGZ Map (`Projects` ∟ `Close`), it removes everything from map and takes you back to welcome screen in QGIS, but it does not empty the panel. I don't think this is logical.

![image](https://user-images.githubusercontent.com/9723905/196518705-27eea181-e17c-4315-bce4-e7340e477df6.png)

In GCD and in RAVE, when we close a map, it also closes all the projects in the respective panels or toolbars.

**Comment by philipbaileynar** [comment]
0.1.6-alpha leaves all layers in the map. (If you happen to open the QRiS project again it should detect the layers in the map that belong to QRiS and work with them just fine.)

**Comment by joewheaton** [comment]
I will check the new release but I think we might be talking past each other by your response. It is impossible to leave all layers in the QGZ map when you close the QGZ project (what is saved to QGZ on disk is a separate issue). As the screenshot shows, I am taking about when you close the QGZ map project, the QRiS project should also close.

It might be that we were talking past each other and your fixes address this anyway.... TBD
