### ISSUE TITLE
When I close map (qgz), the QRiS project should also close.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#135]
Currently, when you close the map of a qgz project that also has a QRiS project open, it does not close the QRiS project too:
![image](https://user-images.githubusercontent.com/9723905/196998012-0b7cb171-cc13-47d7-adfa-3904e391924b.png)

I think that is confusing. In GCD, when you closed the map document, the GCD project also closed. I think because of how often users use closing a map or project as a troubleshooting step or clean up, we should close our QRiS projects too!

**Comment by philipbaileynar** [comment]
I just tried handling the [QgsProject.projectSaved](https://qgis.org/pyqgis/3.0/core/Project/QgsProject.html#qgis.core.QgsProject.projectSaved) signal, but this gets fired when a project is saved as well as on close. 

@MattReimer any ideas?

**Comment by MattReimer** [comment]
Try the `self.qproject.cleared` signal. that's what QRave uses:

https://api.qgis.org/api/classQgsProject.html#a5464634d99f8703bc69d6a9846ccbe50

**Comment by KellyMWhitehead** [comment]
Already fixed in 2ae056e736a77dad75d0b7a10209d3d53e62f535
