### ISSUE TITLE
Build Scratch Space Container & Workflow

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#14]
- [x] Branch in project tree called "Scratch Space"
- [x] Make a look up list of scratch space layer types (including option of "other" by default; 
- [x] User interface for importing scratch layers
  - [x] Checkbox (default on) for clipping to "Project Extent"
  - [x] Checkbox for reprojection to  project projection

**Comment by philipbaileynar** [comment]
Layer type look up list (must be expanding in the future - maybe as database table)

- Jam Counts
- Dam Counts
- Riffle Crests
- Base Imagery
- Hillshade
- Other

**Comment by joewheaton** [comment]
And I am going to close this as a) @philipbaileynar has pretty much done all of this (reopen if you disagree) and b) we have more specific issues that supersede any hanging chads here.
