### ISSUE TITLE
Clip not working on `Import existing Scratch Vector Feature Class` a polygon feature class (drainagewings) to Scratch Space

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#140]
I tried importing drainage wings using `Import existing Scratch Vector Feature Class`.  It successfully imported entire layer to scratch space. However, the following bugs and inconsistencies were present:
- [ ] The `Select a Data Source` form is really cumbersome. It fails to remember previous folder (not sure if that can be controlled) and does not seem to allow selection of layers already in the map. 
- [ ]The incorrect form is being shown after you select layer . You are showing the `Create New Scratch Space Raster` Form
- [ ] This incorrect form is prompting user for `Raster Class`
- [ ] The form allows you to specify the `Clip to Mask` but fails to actually clip and instead imports entire thing. 
Minor requests:
- [ ] `Import existing Scratch Vector Feature Class` is rather verbose. Rename command (already clear we're in Scratch Space) to `Import Existing Vector Feature Class`. 

https://youtu.be/9FF8SgMRwEM

**Comment by philipbaileynar** [comment]
Lots of improvements regarding this legacy issue:

- Clipping has been working for the last few versions
- Import to QRiS now implemented in RAVE, makes importing data much easier.

**Comment by joewheaton** [comment]
Okay... I will test and look for breaks.
