### ISSUE TITLE
Fix where scratch rasters are added to Layers TOC

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#142]
When importing an existing scratch rater to project, it adds it to the Map under `Basemaps` instead of under a `Scratch` type location. 

https://youtu.be/9FF8SgMRwEM

**Comment by KellyMWhitehead** [comment]
We have made improvements on how QRiS manages layer TOC placement. Rasters will no longer appear in the basemaps group, but are grouped in Surfaces or Context as appropriate.

**Comment by joewheaton** [comment]
Okay... can I see? Give me a release to play with please.
