### ISSUE TITLE
Design ZOIs missing some key attributes to support Design Analysis functionality

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#145]
ZOIs in 0.1.5 have the following dialog when editing (designing) shown with two new suggested fields:
![image](https://user-images.githubusercontent.com/9723905/197361209-d2fea227-59df-48ff-ad64-be920e0ffb1b.png)

Please make the following changes:
- [ ] A. Please capitalize "Influence"
- [ ] B.  _NEW_ - We need to specify whether **"ZOI for"** complex or structure. ZOI Types is a different list if "ZOI for" "Structure" vs. "Complex". It should be complex by default because this is all we really need. However, structure level ZOIs are helpful for expressing explicit predictions/hypotheses and are a great learning and teaching tool. 
- [ ] C.  _NEW_ -This is the fiddley part. If the ZOI is for a **"Complex"** you choose which complex it is for. If for "Structure" you choose the structure.  This is hard because it needs to look at the Complex table in the same design and let you choose. It should be optional. 
- [ ] D.  #146
- [ ] E. The choices are great here, but can you make the default "Typical Flood" (it is currently "NULL"). This is the only one we require/suggest as part of the minimum standard of practice. However, people can make as many predictions as they want. 
- [ ] F. Please change to "Description (optional)". It is rare that people fill this in. However, if they do we may include it in a later report. 
- [ ] G. Change Area units to "(sq. m)" - Note that "m" should be based on the CRS the user is using (so could be ft)

**Comment by joewheaton** [comment]
See #77 for specification of categories for ZOI type.

**Comment by philipbaileynar** [comment]
Discussed with @joewheaton today and we agreed to split into two feature classes. One for structure ZOI and the other for complex ZOI.

**Comment by KellyMWhitehead** [comment]
@Jdgilby Please advise if this ticket is still relevant/needed.
