### ISSUE TITLE
Filter to not allow VRTs on Importing Rasters to Basemaps or Scratch

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#147]
I guess VRTs are technically a raster, but they are huge! At least for importing Basemaps and Scratch Rasters, maybe we should just filter to only import *.geotiffs and *.img? See:

https://www.youtube.com/watch?v=6qVWhzkPnz0

Plus, they don't successfully load when you try to bring them in, but also don't throw a helpful error message.

**Comment by KellyMWhitehead** [comment]
Qgis browser dialogs are a bit limited, so I cannot filter by extension type in this case. 

For 0.2.5, if the user selects a vrt raster, the user is now warned and not allowed to proceed with the import.
