### ISSUE TITLE
OSGEO Installer workflow for QRiS

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#152]
Directly related to https://github.com/Riverscapes/QRAVEPlugin/issues/90

From @MattReimer:

> When the user installs QGIS through the OSGEO installer they are able to pick and choose which python modules they can install.
> 
> The user should NOT use pip to install these modules. They should navigate to the C:\OSGEO4W\bin folder (or wherever they installed it) and use the osgeo12-setup.exe tool to install the modules.
> 
> There are some simple mitigation steps we can do to make sure OSGEO installer users aren't left out in the cold.
> 
> Let's make a list of recommended python modules across all our tools (lxml, scipy, shapely etc) and document it on our website for OSGEO users so they can go through and install them all before working with any of our plugins
> look into better import error handling inside QRave so that the user receives better errors and instructions inside QRave when things go wrong.
> So far, the list of modules that we needed to install is as follows:

```
scipy
shapely
```

**Comment by MattReimer** [comment]
As mentioned on the QRave ticket when I installed QGIS and QGIS-LTR from the OSGEO4W installed it installed everything correctly. 

This is an edge case that should affect such a small number of users that a quick note on the documentation page is all the action necessary until someone convinces me that it affects more than just the occasional user.
