### ISSUE TITLE
How to uniquely identify map layers in QRiS and QRAVE

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#156]
Both QRAVE and QRiS need to be able to "find" a map layer in the Map Table of Contents after it has been added. We do this by attaching a custom string identifier property to each map layer. This property is hidden and never seen by the user. Currently in QRiS it is:

`<product>_<layer_type>_<id>`

For a mask layer this looks like `qris_mask_17` where 17 is the database ID of a mask layer.

There are several problems with the current identifier:

- All QRiS projects use the same database numbering system. So in the above example mask 17 could be confused with multiple projects that have 17 masks! We store QRiS map layers in the QGIS project QGZ file and closing and opening successive QRiS projects could cause misidentification of the layers.
- We can't find layers if the user moves a layer outside of the top level QRiS project layer. (This has always been a problem dating back to GCD in ArcGIS, but it's worth mentioning it here if we can solve this longstanding problem.)
- Breaks if the <layer_type> machine code contains an underscore.

# Proposed Solution

I am proposing the following layer identification tag instead. The product slug is unchanged. There is a new project GUID that is stored in the QRiS or QRAVE project. Layer type and ID are unchanged. Note that ID for QRiS will be an integer database ID, but in QRAVE this might be the string XML layer tag ID. The separator is changed to a double colon because it is a character sequence that - unlike underscores - will never appear in any of the component pieces (chiefly the layer type).

`<product>::<project_guid>::<layer_type>::<id>`

Benefits of this proposed solution:

- Works for both QRiS and QRAVE
- Uniquely identifies the project in which a layer originates. This means the user can move the layer to anywhere in the map ToC and it can still be found.
- Works when a user zips and shares a project along with a QGZ. When the other person opens the QGZ both QRiS and QRAVE can identify the layers in the map.
- Supports finding all layers associated with a project, even if the layers has been moved outside the projects section of the map ToC.

Welcome feedback @MattReimer @joewheaton @KellyMWhitehead  @nick4rivers

**Comment by MattReimer** [comment]
Just a quick clarification: `project_guid` can't be the project guid in the warehouse as not every project is uploaded (so not every project has one). maybe it's some other kind of guid?

**Comment by philipbaileynar** [comment]
> Just a quick clarification: `project_guid` can't be the project guid in the warehouse as not every project is uploaded (so not every project has one). maybe it's some other kind of guid?

In QRiS this will be a GUID assigned during project creation.

Do riverscapes projects have any other kind of "top level" GUID?

**Comment by KellyMWhitehead** [comment]
Ready to go for masks and basemaps

Checks:
* On Create New or Import Existing
  * new layer is added to map in correct group
* Add To Map
   * new layer is added to map in correct group
   * Does not duplicate layer if already in map (even if moved outside of project/group)
* Edit (name change)
   *  name change is reflected in map layer
* Delete
   * layer is removed from map and tree, even if moved from project/group

**Comment by KellyMWhitehead** [comment]
Ready in version 0.1.10

**Comment by philipbaileynar** [comment]
The new map manager has been working in QRiS for a couple of internal releases now.
