### ISSUE TITLE
3.  Explore topological enforcement of shared boundaries between active channel and active floodplain, and active floodplain and inactive floodplain, and the plausible valley bottom extent and all of these (potentially).

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#157]
@philipbaileynar can you clarify if this is something we should still think about? It seems like with Riverscapes/riverscapes-tools#369 complete, we have a working way to derive mutually exclusive splitting of the valley bottom into these estimated geomorphic units. However, it seems we are not doing that by any smart topological enforcement of shared boundaries, just order of (geo-processing) operations? 

I guess my real questions are:
1. Do we want to explore this "topological" enforcement of these boundaries, or are we happy for VBET with what we're doing?
2. Does are current solution work for QRiS? We anticipate in Riverscapes Studio allowing users to edit any one of these (active channel, active floodplain, inactive floodplain or valley bottom boundary) and we want to then fix or update the rest for them.
3. Should we actually move this discussion over to QRiS?

**Comment by philipbaileynar** [comment]
Agree that this is more a qris topic. Not very relevant to vbet tool itself.
