### ISSUE TITLE
Custom Project File Name

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#158]
QRiS currently uses the same `qris_project.gpkg` file name for all projects. It does not base the project file name on the users project name.

Goal: Change the QRiS project file name to be a **SAFE** version of the users project name. We already base the project folder on a safe version (escaping spaces etc) and we should do the same for the project file name.

<img width="504" alt="Screenshot 2022-12-16 at 10 13 38 AM" src="https://user-images.githubusercontent.com/8645379/208162470-673b225a-670c-4dd2-ab25-e517c85b7a15.png">

**Comment by KellyMWhitehead** [comment]
Changed

![Image](https://user-images.githubusercontent.com/10746997/208214050-a66245f6-cd70-4151-abaf-88d2ec7136ea.png)

**Comment by KellyMWhitehead** [comment]
@philipbaileynar 

Just realized this affects the open existing project dialog. Currently filtering to match `qris_project.gpkg`:

![Image](https://user-images.githubusercontent.com/10746997/208552511-a2146716-cf45-4a30-9e40-d21c95c037b0.png)

**Comment by philipbaileynar** [comment]
Good catch!

Yes you will need to relax that match to `*.gpkg` (not as precise of course, but best we can do. I don't want to go down the custom file extension[yet])

**Comment by philipbaileynar** [comment]
works!

FYI opening a project with the custom name works on MacOS.
