### ISSUE TITLE
Most Recently Used Project Menu

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#160]
Implement a Most Recently Used (MRU) menu item on the QRiS toolbar, inside the Project dropdown menu.

<img width="244" alt="Screenshot 2022-12-16 at 10 22 52 AM" src="https://user-images.githubusercontent.com/8645379/208164003-3607925d-fc89-4efd-887d-7ecf53c31887.png">

MRUs look simple but they have lots of subtle behaviours...

- The list of MRU projects should be saved in the QGiS settings (same place as we save the last browsed QRiS project folder).
- The MRU list only shows the number of items stored in this list. (If only two projects are stored then the popup menu is only two items long).
- When the user picks an item from the MRU pop-up menu the list of projects is reordered with the selected item getting popped to the top of the list.
- Whenever a project is opened (i.e. not from the MRU) it gets inserted at the top of the MRU list (and pushes the last item off the list if the list is full).
- Do not include any projects in the MRU popup menu that cannot be found on disk.

Here's a [video demonstrating how we coded an MRU in GCD StandAlone](https://youtu.be/imechqip0FQ).

**Comment by KellyMWhitehead** [comment]
Now Implemented. Currently keeps 10 last used projects, can change this value if needed.

**Comment by philipbaileynar** [comment]
1. Use folder icon for the main menu item (same as open project)
2. Use riverscapes icon for the individual MRU project items.



![Image](https://user-images.githubusercontent.com/8645379/208994252-9e636168-a123-4c68-a194-d124bf1d210c.png)

**Comment by KellyMWhitehead** [comment]
Done

**Comment by philipbaileynar** [comment]
Perfect.
