### ISSUE TITLE
Create Project Wait Cursor

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#161]
Creating a new QRiS project takes a few seconds that currently locks QGiS:

- Implement creation of new QRiS project as an asynchronous `QgsTask`
- Make sure that the progress bar shows in the QGiS status bar. It doesn't need to track progress accurately (10%, 20% etc) but it just needs to be animated to provide the user feedback that the project creation is underway.
- when the project creation is complete:
    - Show a 3 second Banner message stating the process was successful
    - Open the QRiS project dockable window with the new project loaded.

**Comment by KellyMWhitehead** [comment]
Create project is now an asynchronous QgsTask and opens in the dockable window when complete.

Added a few messages to status bar when processing, but can modify if needed/desired.

**Comment by philipbaileynar** [comment]
Great! I don't want to go to the effort of estimating the processing time for the different subtasks and moving the progress bar in increments. Just a continuously spinning progress bar is fine.

**Comment by philipbaileynar** [comment]
works
