### ISSUE TITLE
QRiS initial map background

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#162]
This is very low priority...

It would be nice if we could get away from having a blank map background in QGiS upon creation of a new QRiS project. QRiS is about very localized GIS activities. Let's help the user zoom in on where they want to work.

Upon creation of new QRiS project, simply add Google Satellite imagery to the current QGiS map document. Only do this if the map ToC is currently empty (i.e. don't interfere if the user already has some context in the map ToC).

**Comment by KellyMWhitehead** [comment]
QRiS now adds `QRiS Base Maps` group and `Google Satellite` layer to map if empty when loading a qris project.

We can get rid of the group layer and just add the map layer if desired.

**Comment by philipbaileynar** [comment]
It works, but can you zoom to lower 48 US states (for now).

**Comment by KellyMWhitehead** [comment]
Not having much luck getting qris to zoom to the desired extents. 

Something seems to be setting the extents to the layer extent (google maps) after I try to apply them.

When I use the same code outside of qris, works just fine:

```
extent = QgsRectangle(-14746044, 1945739, -6403040, 7205585) 
iface.mapCanvas().setExtent(extent)
iface.mapCanvas().refresh()
```

Any ideas?

**Comment by philipbaileynar** [comment]
Check the coordinate reference system of the map frame before and after adding Google Maps. The initial state of the map frame might be some unspecified CRS, but different afterwards. You might have to apply your desired CRS before you can set the extent.

**Comment by philipbaileynar** [comment]
I know this is isn't quite finished, but here's a slight scope creepy request...

The above works for new projects. When opening an existing project, perhaps we could try and help user's out by moving the map focus to the relevant area.

1. Select the first feature in the mask AOI feature class and get it's bounding box. Do nothing if there are no features!
2. Zoom the current map document to this AOI - 20% or so...
3. Do NOT add the AOI to the map document (we just want the bounding box)
4. Do add Google Satellite if the map document is empty (presumes that closing any previous QRiS project removed all of its layers from the map, leaving the map empty unless they had other layers loaded).

Notes:

- I recognize that 1 above is somewhat arbitrary. The goal is not to be perfect, but merely help the user get to the right place

**Comment by philipbaileynar** [comment]
This is great but now having the Google Map in ToC means that the first thing in a QRiS project that you add to a map, no longer zooms the map to the QRiS layer.

Fix: When adding any QRiS layer to the map, detect if the only other thing in the map is the Google Map. If so, zoom to the QRiS layer being added.

**Comment by KellyMWhitehead** [comment]
Map now zooms to the layer (vector or raster) extent if no other layers (other than basemaps) are in the map. 

Does not change the map srs (which is set by the first layer added to the map, usually the basemap srs).

**Comment by philipbaileynar** [comment]
Nice Kelly. This makes it much more friendly and useful!
