### ISSUE TITLE
Mask menu order

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#163]
Switch the order of the mask import/create submenus. Import should come above create.

<img width="244" alt="Screenshot 2022-12-16 at 10 43 48 AM" src="https://user-images.githubusercontent.com/8645379/208167286-cf71a870-8e7b-44ac-b3f5-9773a72aef9c.png">

**Comment by KellyMWhitehead** [comment]
Done!

**Comment by philipbaileynar** [comment]
Works
