### ISSUE TITLE
Copy Feature Class Bug

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#164]
Top priority

@KellyMWhitehead wrote a [copy feature class](https://github.com/Riverscapes/QRiS/blob/copy_feature_class/src/gp/copy_feature_class.py) asynchronous process.  There is an option to this command that we never figured out:

https://github.com/Riverscapes/QRiS/blob/0bf2ec31446c8ebb3acdb76aac7cdec6c06a8588/src/gp/copy_feature_class.py#L64

Setting the option one way makes the command work for ShapeFiles but not for GeoPackages. Setting it another way makes it work for GeoPackages but not for ShapeFiles.

We need an ultra reliable way to copy feature classes from any format!

**Comment by KellyMWhitehead** [comment]
Seems like the issue wasn't shapefile vs gpkg layer, but rather if the [output geopackage already exists and/or has existing layers in it](https://gis.stackexchange.com/questions/323235/write-two-layers-to-geopackage). 

I have made the changes and tested with gpkg and shp layers as inputs.

Note that we currently only output to geopackages, but can add shp or other formats in the future if needed.

**Comment by philipbaileynar** [comment]
Great, so this now handles existing or new GeoPackages?

**Comment by KellyMWhitehead** [comment]
Y, it will create if it does not exist, and add layers if it already does.

**Comment by philipbaileynar** [comment]
Tested with:

- polyline ShapeFile
- polygon ShapeFile
- Polygon Geopackage feature class
- VBET polygon Geopackage polygon

All worked. And fast too!
