### ISSUE TITLE
Delete Mask Does Not Remove From Project

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#165]
Steps to Reproduce:

1. Create new project
2. Import existing mask
3. Delete Mask

Observed

Mask item remains in project tree.

Expected

Mask item gets removed from project tree

**Comment by KellyMWhitehead** [comment]
@philipbaileynar 
Could not reproduce, mask is removed from project tree using the Delete Menu.

**Comment by KellyMWhitehead** [comment]
Fixed
