### ISSUE TITLE
Add Vertical Spacer to DCE form

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#167]
Add a vertical spacer control to the Data Capture Event (DCE) form on the Basic Properties tab to push all the controls to the top of the form.

<img width="568" alt="Screenshot 2022-12-19 at 11 49 03 AM" src="https://user-images.githubusercontent.com/8645379/208507977-78666952-ce76-4cab-baa8-cf74b3e41fec.png">

**Comment by KellyMWhitehead** [comment]
Fixed.

**Comment by philipbaileynar** [comment]
works!
