### ISSUE TITLE
Centerline Tool

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#17]
Feed polygon, derive centerline.

**Comment by philipbaileynar** [comment]
Inputs are:

* inflow point(s) i.e. most upstream point of each tributary
* outflow point (single point where water leaves the polygon)
* bounding polygon

output

* Feature class containing polyline of the center of the polygon.

**Comment by joewheaton** [comment]
See [riverscapes-tools/issues/320](https://github.com/Riverscapes/riverscapes-tools/issues/320) for new Channel Area stuff.

**Comment by KellyMWhitehead** [comment]
New centerline tool available since 0.1.8-alpha release

Will need plenty of testing and review - please file new tickets for bugs/enhancements, etc.
