### ISSUE TITLE
When adding Basemap or Scratch Raster of type "DEM", derive hillshade and also add to map

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#171]
![image](https://user-images.githubusercontent.com/9723905/209315577-5e65ea46-4789-4452-9bf9-eba48afec9d6.png)

This is a request to basically implement the exact same GCD Giggle moment functionality to QRiS. Namely, if a user invokes:
- [ ] `Import Existing Scratch Raster` of type `Digital Elevation Model (DEM)`
- [ ] `Import Existing Basemap Dataset` of type `Digital Elevation Model (DEM)`

What we should do is 
- Import their DEM correctly as we're currently doing
- Derive a concurrent hillshade immediately and store in project in same locale as dem
- Add the DEM to the map with the symbology from [`Shared/DEM.lyr` in RiverscapesXML](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/qgis/Shared/dem.qml)
- Add the hillshade to bottom (like we do in QRV) in its own Hillshade Group, but within the Basemaps DCE. 

The logical extension is that when they `Add to Map` any DEM from Scratch space or Basemaps, that the DEM and its hillshade are added. 
- [ ] Update `Add to Map` for DEMs and hillshades from scratch space
- [ ] Update `Add to Map` for DEMs and hillshades from basemaps

**Comment by philipbaileynar** [comment]
Revised actions:

1. Add "Generate Hillshade" checkbox just above Add to map checkbox.
    - Checkbox is disabled until user selects DEM in the surface type dropdown.
    - Checked by default.
1. If the user is importing a DEM and checks the box then use GDAL to generate hillshade:
    - the hillshade is actually stored as an additional surface raster, with accompanying surface record in the database.
    - store some metadata JSON on the DEM record that links the hillshade record to the DEM. 
    - derive the name of the hillshade surface by using the DEM surface name and suffix with the word "Hillshade"
1. When adding a surface raster to the map, detect if the metadata possesses the hillshade data and add the hillshade to the map automatically. Will need to think about transparency and Map ToC structure/order.

**Comment by KellyMWhitehead** [comment]
This is all hooked up except for the symbology.

**Comment by KellyMWhitehead** [comment]
Done for version 0.5.0
