### ISSUE TITLE
BRAT CIS Export

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#172]
Add the ability to right click on a `BRAT CIS` layer in the QRiS project tree (not map ToC) and choose "Export BRAT CIS Observations...". 

Choosing this option will pop up a file browser dialog for the user to choose an output `*.csv` file. Columns in the CSV:

- FID
- Reach ID
- Observation Date (yyyy-mm-dd)
- latitude
- longitude
- reach length
- notes
- observer name
- streamside vegetation (string)
- riparian vegetation (string)
- vegetation dam density (string)
- base streampower (string)
- high streampower (string)
- slope (string)
- combined dam density (string)

# Notes

- the CIS fields are strings ("Pervasive", "Frequent") not the database lookup IDs.
- in the future we might also export these data as part of an HTML report

**Comment by KellyMWhitehead** [comment]
Almost done, need a few housekeeping answers:
* Do the field names need to strictly match the list above, or are the aliases in the brat cis layer sufficient? 
* Does order of columns need to match?
* Include "Event ID" ?

**Comment by philipbaileynar** [comment]
1. aliases in BRAT CIS layer should be sufficient
2. order does not matter
3. (I think) include event ID for audit trail purposes. No harm.

**Comment by philipbaileynar** [comment]
@KellyMWhitehead please close if this is completed.

**Comment by KellyMWhitehead** [comment]
Mostly done, but stashed away. I need to bring this back up to the top of the current version and test.

**Comment by KellyMWhitehead** [comment]
Done.
