### ISSUE TITLE
QRiS 0.1.10 - Initial Test Drive

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#173]
This [video](https://youtu.be/xltlO-IMYMs) is just @joewheaton trying out 0.1.10. Some cool new features. Lots of improvements, lots to do... Nice work @KellyMWhitehead and @philipbaileynar

**Comment by philipbaileynar** [comment]
Useful video thanks. Got lots of inspiration from this. Actionable items are broken into issues. Closing this issue for now. video link will stay here for future reference.
