### ISSUE TITLE
Watershed Catchments Getting Added To Project Tree Incorrectly

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#174]
See ~ minute 5:30 in this [video](https://youtu.be/xltlO-IMYMs). Notice that there watershed catchments are getting added to a new group at the bottom of the project tree instead of inside the existing folder in Context

<img width="289" alt="Screenshot 2023-02-03 at 10 44 04 AM" src="https://user-images.githubusercontent.com/8645379/216682376-54244292-34e2-4675-afb0-e88fe7b2694b.png">

**Comment by KellyMWhitehead** [comment]
Fixed.

**Comment by philipbaileynar** [comment]
Working!
