### ISSUE TITLE
Raster Slider Symbology

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#175]
Currently can't really see what's going on with the raster slider. The symbology obscures the threshold.

1. Remove symbology for pixel values that do not meet the threshold (i.e. grey area in screenshot)
2. Apply partial transparency (30%?) to the pixel values that do meet the threshold (pink area). We might end up making this transparency level an advanced setting on the slider panel.

<img width="2010" alt="threshold" src="https://user-images.githubusercontent.com/8645379/218887888-ce323d98-166d-47f7-a372-f5e762782b31.png">

**Comment by KellyMWhitehead** [comment]
Odd, the gray area _should already_ be transparent...

**Comment by KellyMWhitehead** [comment]
fixed.
