### ISSUE TITLE
Sampling Frame Improvements

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#176]
1. On the "import existing form" we need a new name for what we call `Attribute`. This is too vague. The underlying database can remain unchanged, but we need a better name for the field in the user interface.
    - `Label Field`
    - `Sample Frame ID`
    - ?
2. When adding a sample frame to the map, please add nice big, clear labels using the `Attribute` Field.
3. On the edit properties form, please make the `Attribute` field visible but read only. (Technically we could let the user change this right up until they do something useful with the sample frame, like calculate metrics, but let's leave it read only for now.)
4. The edit properties form still says "Edit Regular Mask Properties". Please change to reflect new naming of sampling frames.

**Comment by philipbaileynar** [comment]
Ok well let's put the label "Display label" next to the dropdown on the import form then.

**Comment by philipbaileynar** [comment]
Status @KellyMWhitehead ? Close if implemented.

**Comment by KellyMWhitehead** [comment]
changed this as well as other ui references to 'masks'
