### ISSUE TITLE
Analysis Improvements

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#177]
1. On the create analysis form, change the "Analysis Metrics" tab to "Metrics and Indicators".
2. If the user attempts to create a new analysis and either of the following conditions are not met then they should get an appropriate warning:
    - one or more data capture events
    - one or more sampling frames
3. Clicking calculate on dockable window shows an error. Clicking this button should just show a nice "Automated calculation of metrics is not yet implemented."
4. Double clicking a cell in the value column on the dockable window then entering a value and uncertainty and clicking OK throws an error. (This might be due to there being no DCE for this analysis.)
5. On the Analysis dockable window the sampling frame dropdown is not correctly picking up the sampling frame attribute column values:

<img width="1438" alt="Screenshot 2023-02-16 at 9 26 30 AM" src="https://user-images.githubusercontent.com/8645379/219441794-e13128ca-68b2-4d92-8189-214b62ee3d1b.png">

**Comment by KellyMWhitehead** [comment]
> Double clicking a cell in the value column on the dockable window then entering a value and uncertainty and clicking OK throws an error. (This might be due to there being no DCE for this analysis.)
@philipbaileynar This error was masked by an incorrect message box setup. The actual error occurs when trying to save the metric to the database, but I was unable to figure out the issue. check here: https://github.com/Riverscapes/QRiS/blob/177133bc3cf535a61378cfe668ce4aa3e3e4fc50/src/model/metric_value.py#L27

> On the Analysis dockable window the sampling frame dropdown is not correctly picking up the sampling frame attribute column values:
Again, sample frame doesn't currently include any other attributes other than 'display_label' and a few other housekeeping fields.

**Comment by philipbaileynar** [comment]
1-5 are implemented.
