### ISSUE TITLE
Map Layer ToC Collapsed

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#178]
When adding most layers to the map ToC the final group is collapsed, obscuring the actual layer entry in the QGIS ToC. This keeps confusing me because I know the name of the item I'm adding to the map but when I glance up at the ToC I don't see the layer, just the parent group.

Whenever adding a layer to map, please ensure that the map ToC is expanded to reveal the layer being added to the map.

**Comment by KellyMWhitehead** [comment]
Fixed.

FYI: https://gis.stackexchange.com/questions/420251/qgslayertreenode-ignores-expansion-calls

**Comment by philipbaileynar** [comment]
working
