### ISSUE TITLE
Valley Bottom Segmentation

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#18]
Two workflows... 
- [ ] 1. User draws own (allow first)
- [ ] 2. VBET or HAND slider tool derivative (do next using the *Scratch Space* to import VBET in 1 below and then accommodate 2-6 as commands)
   - with optional further splitter.

In https://github.com/Riverscapes/riverscapes-tools/issues/17 we pointed out a variety of ways to get valley bottom segments. :

> A valley bottom segment could be defined as a longitudinal portion (reach or segment) of a riverscape, which spans the entire valley bottom width. They will typically be longer (longitudinally) than it is laterally (cross-valley).
> 
> # Ways to get them
> In a [commercial-grade](riverscapes.xyz/Tools/#tool-grade) or [professional-grade](riverscapes.xyz/Tools/#tool-grade) version of VBET, we might let the user choose which way to get there, or let them choose the valley bottom segmentation method and produce multiple **valley bottom segmentation** realizations. These include (not mutually-exclusive... could be combined or used to further split/segment):
> 
> 1. Load an already segmented network, segments drawn perpendicularity from all reach segment end points into VB intersection.
> 2. Segment based on tributary (of intput VBET network) junctions - _Note: this would be really important that the end  of the tributary includes the fan of that tributary._
> 3. Further segment based on intersection with polygon input (e.g. of land ownership or property boundaries) - pyBRAT has this option
> 4. Further segment based on intersection of polyline input with drainage network (e.g. road crossings) - _Note: it is important not to allow this for polyline intersection of VBET polygon, because many roads run parallel._
> 5. Further segment based on a uniform segmentation length (e.g. RCAT uses 500 m and BRAT uses 300 m by default).
> 6. Further segment based on variable segmentation length defined by continuous network function (this is what Fluvial Corridor Toolbox can do and GNAT implemented as well).
> 
> # Why the above are important
> The valley bottom segment is important as it defines the length-scale over-which potential valley bottom derivatives and metrics can be summarized.
> 
> @philipbaileynar - this is one way we give users ownership of their own VBETs.

**Comment by joewheaton** [comment]
@joewheaton to flush out when sorted in VBET.

**Comment by philipbaileynar** [comment]
Currently have two ways of getting valley bottom segmentation into QRiS:

1. Draw your own.
2. Semi-automated:
    - Import VBET evidence raster
    - Bankfull slider to create polygon.
    - Centerline tool down middle of polygon.
    - Cross Sections to segment polygon.

**Comment by joewheaton** [comment]
And a third... import one to context!
