### ISSUE TITLE
Wrong structure type when copy and pasting in old projects to new ones. 

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#182]
In on case I was looking at  the Bank Attached PALS became BDA Large, Channel Spanning PAL became BDA Postless, and Mid Channel PAL became BDA Small. I haven't dove into other types, these were just the ones in the project I was looking at. It appears to be due to a change in the structure_type table. Not sure if that table changes based on how many structure types are in the project.
![image](https://user-images.githubusercontent.com/97305413/221306284-557786f7-53ab-4275-9437-3abba99132a8.png)
Heres a picture of the structure type table from the old project I'm importing. 
![image](https://user-images.githubusercontent.com/97305413/221306785-f7bf462c-60b9-4626-9929-288a9a79381b.png)
Versus the structure_type table from the newest version of QRiS

**Comment by joewheaton** [comment]
@KellyMWhitehead and @philipbaileynar did you see this? Please advise and propose fix.

**Comment by philipbaileynar** [comment]
This is hard and not much we can do about this when users cut and paste. QGIS looks at the attributes of the source feature class and the attributes of the target feature class. If the attribute column names match then QGIS pastes the geometry along with the attribute. But if the source field has structure type ID of 4 for BDA but in the target has structure type ID 4 is log jam then the feature will appear to get a switched structure type when it is pasted.

The only solution is see is managed import routine instead of cut and paste.

**Comment by Jdgilby** [comment]
@joewheaton I checked in on this today and its no that big of a deal. I copy and pasted and then inside the attribute table for the pasted features just changed them manually. Theres a nice drop down menu for that attribute which makes it super easy. I have successfully brought an old project into the latest version 0.1.13 and have it all symbolized correctly.

**Comment by philipbaileynar** [comment]
That's good. It just requires the user to be aware of whats happening. We really don't have control over things when native qgis functionality is at play. 

Not a big deal for one or two features. Not really practical for hundreds...

**Comment by Jdgilby** [comment]
Even with hundreds its not a big deal, you can just select all by a type and update selected in the attribute editing form. I tested that way and it worked as well. Its also easier because you dont even need to type out the structure (ex: 'Pals-Bank Attached'), you can just enter the corresponding number for that structure type ('5') and it populates with the correct description.

**Comment by philipbaileynar** [comment]
Based on @Jdgilby response I am going to close this. Happy for folks to re-open if this trips us up again.

**Comment by Jdgilby** [comment]
Im going to reopen this and post this video here and we can reassign if necessary, but its a related issue.
https://youtu.be/wqBmqPm72A4

**Comment by philipbaileynar** [comment]
Thanks for posting @Jdgilby ! Me and @KellyMWhitehead will review tomorrow.

**Comment by KellyMWhitehead** [comment]
This issue will be resolved with the new DCE import tool (see #221 ).

Closing for duplication.
