### ISSUE TITLE
Analysis Grid Refresh

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#183]
in #177  we fixed the saving of metric values to the database. New issues:

1. Refresh the grid on the dockable window when the metric value form closes and changes were made! See line 156 in `frm_analysis_dockwidget.py`.
2. Fix the resizing of the grid columns when the dockable window is resized. I just moved the dockable window from landscape mode (glued to the bottom of QGIS) to portrait mode (glued to the right side of QGIS), the column widths in the grid were no longer appropriate with data hanging off the right side of the screen. Is there any quick way to detect this (catch a resize signal) and resize the column widths.

**Comment by KellyMWhitehead** [comment]
1. This change has been made. Note that user can currently edit the value in the table (does this need to be read only?)
2. resizeEvent now checks if column 0 width is larger than table width and readjusts if needed. 
3. Added 'Open Analysis' menu item to project tree to reopen existing analyses.

**Comment by philipbaileynar** [comment]
The grid should be read only.

**Comment by KellyMWhitehead** [comment]
All these changes will be in 0.1.16
