### ISSUE TITLE
Leverage RAVE symbology in QRiS

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#184]
# Goal

Have QRiS ask QRAVE where it stores symbology files and then use this path to load symbology files.

# Notes

- See @MattReimer branch called `qrave_integration` that shows how QRiS can ask QGIS for another plugin and then call a piece of code from that plugin.
- Try to take a "light touch" and cause as little disruption as possible. Perhaps we don't need full QRAVE dependency at this early juncture.
- Don't re-write QRAVE project tree and map manager just yet!
- When you are successful you will want to move the symbology QML files that are currently in QRiS and put them in the Riverscapes XML repo under a new tool folder called `QRiS`. i.e. there should no longer be any symbology files in the QRiS repo.
- You will need some way to link QRiS layers with a RAVE symbology QML file. Reuse the `qml` field in the `layers` table but include the path to the QML file in the QRAVE symbology folder.

**Comment by KellyMWhitehead** [comment]
This is ready when these are released:
[] [RiverscapesXML](https://github.com/Riverscapes/RiverscapesXML/pull/506)
[] [QRiS](https://github.com/Riverscapes/QRiS/commit/724f452da11a7718b9516c59c16814ddeab527b9)
[] [QRave](https://github.com/Riverscapes/QRAVEPlugin/commit/a77966f0a89c57793f14cc2d6480d04491dc1a59)

**Comment by joewheaton** [comment]
When is ETA? We need to get moving on testing this. Thanks.

**Comment by philipbaileynar** [comment]
An official QRAVE release was launched over a week ago with the necessary capabilities to interact with QRiS.

All internal QRiS releases have the ability to "listen" for RAVE attempting to import a layer into QRiS.
