### ISSUE TITLE
Limit one DEM per data capture event

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#187]
1. Only allow one DEM per data capture event. (because we need to be able to find the one any only DEM for metrics)
2. Remove LiDAR from surface type dropdown. It's a DEM! Who cares about the source!

**Comment by KellyMWhitehead** [comment]
This is good to go.

**Comment by joewheaton** [comment]
I'm okay with one DEM per DCE, but don't apply this same logic please on other basemap layers. Technically, in some DCEs we use multiple lines of evidence. Anyway, lets get some reps and we can discuss.

**Comment by philipbaileynar** [comment]
@joewheaton we need to limit to one DEM because analyses require to know which surface is the official elevation raster to be used for metrics (gradient etc). 

Multiple surfaces for other types is fine.
