### ISSUE TITLE
Allow direct saving into Qris project folders and update the project tree when doing so

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#188]
@philipbaileynar @joewheaton 
https://user-images.githubusercontent.com/97305413/224834174-6ac94e97-dec2-4ad3-a10d-4d9fcd12d6d0.mov

**Comment by philipbaileynar** [comment]
Thanks for posting. I am traveling right now. Will digest and get back to you. 

Fyi @KellyMWhitehead

**Comment by joewheaton** [comment]
I think this is no longer relevant. @Jdgilby re-open if you still see a need.
