### ISSUE TITLE
Problem with raster slider dropdown

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#189]
@joewheaton @philipbaileynar @KellyMWhitehead Pretty simple issue, once the raster slider has been opened on a raster there is the option to change rasters within the slider panel. Once you hit select a dropdown window pops up. This dropdown menu isn't functional.
![image](https://user-images.githubusercontent.com/97305413/225074479-8bed69c1-a06d-417f-8ac9-db10b36f14c7.png)

**Comment by KellyMWhitehead** [comment]
Thanks for reporting this, I will take a look...

**Comment by joewheaton** [comment]
I noticed same problem.

**Comment by philipbaileynar** [comment]
@KellyMWhitehead this should be an easy fix?

**Comment by KellyMWhitehead** [comment]
Fixed for version 0.1.16
