### ISSUE TITLE
Error when trying to create transect profiles from cross sections

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#190]
@joewheaton @KellyMWhitehead @philipbaileynar Haven't been able to successfully generate transect profiles from cross sections I generated.

This is the error I'm getting.
2023-03-14T11:57:15     WARNING    Traceback (most recent call last):
              File "C:\Users/joshu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 348, in 
              self.add_context_menu_item(self.menu, 'Transect Profile', 'gis', lambda: self.generate_transect(model_data))
             TypeError: generate_transect() takes 1 positional argument but 2 were given

**Comment by KellyMWhitehead** [comment]
This actually isn't implemented yet, however a bug prevented a user friendly message from popping up. This is fixed for the next release.
