### ISSUE TITLE
Analysis Sample Frame drop down has the wrong contents

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#191]
On the analysis dockable window the "Sample Frame" dropdown should list all of the features in the selected sampling frame. I think this is the way that I originally coded it. (I requested a change of the label "Sample Frame" but did not intend that the contents of the dropdown were changed.)

So in the metric demo dataset you just provided, the values in this dropdown should be 1, 2, 3, 4 (i.e. the labels of the sample frame **polygons**).

<img width="2560" alt="Screenshot 2023-03-24 at 2 47 28 PM" src="https://user-images.githubusercontent.com/8645379/227647408-881fc8a4-c8f1-456b-b902-96487fede28a.png">

**Comment by philipbaileynar** [comment]
FWIW, it's the value in this dropdown that tells the software what the value of the `mask_feature_id` should be when reading and writing metric values to the database.

**Comment by KellyMWhitehead** [comment]
Fixed for Version 0.1.16
