### ISSUE TITLE
Reuse QRAVE Basemaps in QRiS

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#194]
Now that we have QRAVE capabilities within QRiS....

Implement the identical Basemaps listing at the bottom of the QRiS project tree. Ideally the same code could be leveraged?

Note that QRAVE will still be responsible for syncing the basemaps XML down to the users computer. The goal here is simply to have basemaps appear at the bottom of the QRiS project tree so that folks can use them without having QRAVE open.

<img width="289" alt="Screenshot 2023-03-28 at 1 22 22 PM" src="https://user-images.githubusercontent.com/8645379/228358048-73fe7992-369d-49b9-ad8d-5e9e96acaab8.png">

**Comment by KellyMWhitehead** [comment]
This was a big change. The QRave tree is managed differently than QRis. Having said that, I was able to get
1) Basemaps tree from QRave to build within the QRiS tree
2) Add a separate RiverscapesMapManager for basemaps. 
3) Riverscapes basemaps now appear as a separate layer group in the layer tree. This is forced to the bottom of the tree root.
4) Modified how opening a QRiS project behaves when map is empty to use the first map in this tree (Google Imagery). 

This will need plenty of testing, but is working well so far.

**Comment by joewheaton** [comment]
> This was a big change. 
...
> This will need plenty of testing, but is working well so far.

I am excited to check it out. Do you have a version I can start playing with?

**Comment by KellyMWhitehead** [comment]
Included in version 0.5.0.
