### ISSUE TITLE
Certain editing features not working on imported layers

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#195]
[Here's](https://youtu.be/HVleVdzdpTA) a video of the issue

**Comment by Jdgilby** [comment]
`<iframe width="560" height="315" src="https://www.youtube.com/embed/HVleVdzdpTA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>`

**Comment by KellyMWhitehead** [comment]
@Jdgilby 

I think these issues have been resolved with the recent merging and import updates. Please let me know if I missed a specific issue.
