### ISSUE TITLE
Calculate All Button Behaviour

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#196]
Here's a design for a form that should pop up when the "Calculate All" button is clicked on the analysis dockable window.

Note the difference between radio buttons (round) and checkboxes (squares).

Should if the words are illegible or the ramifications of any buttons are unclear. 

![PXL_20230330_184301007](https://user-images.githubusercontent.com/8645379/228933845-57e91a9c-c233-4679-9302-238e079ac6f1.jpg)

**Comment by KellyMWhitehead** [comment]
Up and running. 

Needs a little more testing to make sure all cases are working properly.

**Comment by philipbaileynar** [comment]
I really like the implementation. Closing until something crops up.

**Comment by joewheaton** [comment]
> Up and running.
> 
> Needs a little more testing to make sure all cases are working properly.

I'm happy to test.
