### ISSUE TITLE
Metric Data Type

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#198]
Add the ability to define a metric as either `int` or `float`.

I suggest incorporating this into the metric metadata data along with min, max and tolerance.

**Comment by KellyMWhitehead** [comment]
I am now setting the manual value to use the metric precision, if it exists. If precision is not specified, then the precision is 0 (no decimals, i.e. type int). This is similar behavior to the automated value box. 

I can add an explicit type to metadata, but I think the precision tag covers this need.

**Comment by philipbaileynar** [comment]
Yeah I think that works.
