### ISSUE TITLE
Tool tips

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#200]
This is a big one....

Let's start adding tool tips to all our forms!

Probably the best way to do this is in the `setupUI` method right where each widget is defined. In other words, try to do this systematically whereby we can quickly find the code and change any tooltips going forward. Look at CHaMP Topo Toolbar for inspiration on the grammar and appropriate level of detail.

**Comment by KellyMWhitehead** [comment]
Added a bunch of missing tool tips. Nearly every form now has them.

I will keep adding to new features moving forward.
