### ISSUE TITLE
Check documentation page for every form.

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#201]
1. Check that every UI form in the system has a help button.
2. Check that every help button launches a valid documentation page. OK at this stage if that page is blank.

**Comment by KellyMWhitehead** [comment]
Tasks
- [ ] Calculate All Metrics -> SoftwareHelp/metrics.md (point to analysis.md?)
- [ ] Analysis Properties -> SoftwareHelp/analysis.md
- [ ] Add buttons to individual metrics on Analysis Properties 
- [ ] Create Cross Sections Form -> SoftwareHelp/crosssections.md (currently points to masks.md)
- [ ] Create Centerlines Form -> SoftwareHelp/centerlines.md (currently points to masks.md)
- [ ] New Design form -> SoftwareHelp/designs.md (currently points to DCE)
- [ ] Raster Slider Dock -> SoftwareHelp/RasterSlider.md (need button)
- [ ] Save Raster Slider -> SoftwareHelp/RasterSlider.md 
- [ ] Geospatial Metrics Form (zonal stats) -> SoftwareHelp/zonalstats.md (currently points to masks.md)
- [ ] Geospatial Metrics Settings form (options) -> Software_Help/options.html
- [ ] Edit Metric Value form -> metrics? analysis? (in addition, this form has a blue help icon next to metric that points to the metric definition)
- [ ] Scratch (context) Vector -> ?? (currently points to basemaps.md)
- [ ] Stream Gages -> streamgages.md (form itself is not currently working at the moment)

Rename?
- [ ] masks.md
- [ ] basemaps.md

**Comment by KellyMWhitehead** [comment]
I have checked and updated all the forms I could find. Maybe a few obscure places I missed that we could add a button or two, but easy enough to do.

**Comment by philipbaileynar** [comment]
Impressive. Thanks. Try to keep this task in mind when creating new forms please.
