### ISSUE TITLE
Orphaned event layers

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#202]
Add a new top level item in the DCE create form called "Layers without a method". Under it list all layers that are disassociated from at least one method. Here's some SQL that uses a LEFT join to quickly find layers that don't appear in the `method_layers` table (actual table names might vary).

```sql
SELECT l.*
FROM layers l LEFT JOIN method_layers m on l.layer_id = m.layer_id
WHERE m.method_id IS NULL
```

**Comment by KellyMWhitehead** [comment]
Done.

**Comment by philipbaileynar** [comment]
Looks good
