### ISSUE TITLE
Importing DEM from RAVE doesn't symbolize

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#204]
# Steps to reproduce

Pay attention to which tool is being used below.

1. Open RAVE project (mine was VBET)
2. Add DEM to map.
3. Create new QRiS project.
4. Create a new AOI in QRiS
5. Right click on DEM in RAVE tree and click "Import to QRiS"
6. Ensure that "DEM" is selected in the surface type dropdown.
7. Click OK

# Observed

Imported raster gets added to map with grey scale (it is clipped by AOI correctly)

# Expected

DEM symbology.

**Comment by KellyMWhitehead** [comment]
DEM (and hillshade, slope, vbet evidence) now apply symbology when added to the map.

In addition, the associated Hillshade is now automatically added with the DEM (if it exists).

This required a schema change to add the qml file names to the lookup tables.  The associated migration script was added as well.

**Comment by KellyMWhitehead** [comment]
version 0.5.0
