### ISSUE TITLE
Export Riverscapes Compliant Project

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#205]
The goal of this ticket is to enable users to export **portions** of a QRiS project so that they can share it via the Riverscapes Warehouse. 

# High Level Concept

1. Create a Data Capture Event in QRiS
2. Digitize Data
3. Right click on Data Capture Event and Click "Export to Riverscapes Project"
4. QRiS writes all the data to a GeoPackage and accompanying `project.rs.xml`
5. User uses RAVE to upload project to warehouse (not scoped)

# Considerations

I started this feature last November on a branch called `event_export`. It's unfinished and will probably need some refactoring because the GeoPackage tables have changed. For the record my strategy was rather crude... it simply copies the QRiS project GeoPackage to a new folder and then deletes things NOT related to the selected Data Capture Event!

Note that @MattReimer has a new pip module that will be useful for this task. It is specifically designed for ALL our Python tools to use when writing Riverscapes `project.rs.xml` files. Please check in with him.

In our call today, @joewheaton wanted set a high bar for users to be able to export as riverscapes project... Specifically that there's a corresponding riverscapes project type, business logic and symbology. Ramifications:

1. In the `protocols` database schema I think we should add a `rs_project_type` to the `metadata` JSON. Only protocols with this value set can be right clicked on in the project tree and exported.
2. We are not currently tracking the protocol for each DCE. We decided a while back only to track layers with DCE. We will need to track the protocol in the DCE metadata. But we give the user flexibility when adding layers to DCE. They can add individual layers, partial protocols etc.

How do we pick which protocols are associated with a DCE?

**Comment by joewheaton** [comment]
I'm not sure what level (e.g. DCE or protocol within a DCE) export should be allowed at. I don't think it is DCE level. I think it makes more sense to do at protocol level.

**Comment by KellyMWhitehead** [comment]
This is available at 0.3.4. User can export any/all layers, dces, designs as a QRis Project type.
