### ISSUE TITLE
Remember Riverscapes Metadata When Importing From RAVE

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#206]
Following on issue from #52...

When right clicking in RAVE to import to QRiS, we need to:

1. Grab the project and dataset metadata from the host RAVE project.
1. Write them to the QRiS project in the `metadata` column for the scratch/context layer. Make sure it is stored as JSON so that we can do intelligent things with it later when the layer is promoted to a DCE layer.

**Comment by KellyMWhitehead** [comment]
Done. 

Copies whatever metadata (project and layer) that qrave provides.
