### ISSUE TITLE
I don't like the verb `Edit` as it is misleading. Change to `Properties`

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#208]
![image](https://user-images.githubusercontent.com/9723905/230903578-733073f6-bcf3-40b2-8bc6-431d9fc6f12f.png)

Almost every feature in a QRiS project has a right-click context command `Edit`. This is @philipbaileynar logic and I really like it on one hand, but it is a throw back to something that always bugged me about GCD and I saw it regularly confusing GCD users. The crux of that confusion is that the verb `Edit` suggests to the user that they only invoke that command if they want to change something. This is disingenuous. In GIS, `Edit` is a term most commonly associated with drawing or modifying vector geometry. You could be more specific and say `Edit Properties`, but even that is confusing and misleading. 

The most common thing you are trying to get the user to do (or that experienced users will use this for) is to **view** or **inspect** the properties of that feature or layer. I would request that we don't use **view** because in GIS everyone assumes you mean the map layer and that's a Layers TOC and map thing. I think what is most accurate is `Inspect`

- [ ] Change all those right-click context commands for every layer from `Edit` to `Inspect`

- [ ] Change first word on all those form titles from `Edit` to `Inspect`

Every form title starts with Edit currently. Change to Inspect.
![image](https://user-images.githubusercontent.com/9723905/230906379-90ed2dc7-93b5-4dd5-ba22-76573a02660f.png)

- [ ] Add the `Edit` feature toggle bottom of every form for editable fields

Instead of assuming or misleading the user that they have to edit (and therefor `OK` means you exit with saving changes and `Cancel` means you discard even if you didn't change anything.  Instead, lets toggle on the ability to edit. It should, after all, be something we sort of caution users from just changing without thinking about it.  Not all fields are editable, but something we did in a few GCD forms was added an edit button to toggle editing of those values in those fields on/off. 

One way to to do this would be to:
- By default only the `Help` and `OK` buttons are enabled. `Cancel` is disabled unless changes (i.e. edits) to a property are made.
- Add to the buttons at bottom of each form an `Edit` button (with an `Edit Properties` tooltip), which when toggled changes the `state` of the form fields above to editable. If user makes edits, `Cancel` is enabled.
- Add a warning dialog to users "You have edited the properties of this layer. Are you sure you want to override values with your edits?" with `YES` and `CANCEL` (returning back to form) and `NO` options (exits form without saving). 

I am okay with `OK` meaning leave the form, or leave the form with edits saved.

**Comment by philipbaileynar** [comment]
I would prefer to use "Properties" rather than inspect. I can't think of another software product that uses "inspect", but the use of "properties" is widespread and does not limit us to read or write.

**Comment by joewheaton** [comment]
> I would prefer to use "Properties" rather than inspect. I can't think of another software product that uses "inspect", but the use of "properties" is widespread and does not limit us to read or write.

I'd be happy with that.

**Comment by KellyMWhitehead** [comment]
Renaming of edit to properties changed for v 0.2.4
