### ISSUE TITLE
Develop Field Form for Hydrogeomorphic Meadow Classification in PostGIS that works with RIPT

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#21]
We have a geopackage and `*.qml` for the Hydrogeomorphic Meadow Classification. We'd like to have the ability to collect the information in QGIS (i.e. map and digitize meadow type polygons) and then integrate this (maybe with sync) back into a single polygon based feature class in an assessment (#20).

**Comment by nick4rivers** [comment]
@philipbaileynar - are you opinionated about where PostGIS database are hosted and have any suggestion/approaches/tutorials that outline what you and @MattReimer and Kelly are using/like?

**Comment by MattReimer** [comment]
Strictly speaking it doesn't matter where you host your DB but given that database administration is hard it would be nice if we didn't end up with everybody hosting their own in different places. That's just my $0.02 CAD

@nick4rivers here's what we use:

For our production DBs We use [AWS RDS on-demand](https://aws.amazon.com/rds) which seems to sit nicely in our cost bracket. Problem is, those need to live behind a firewall that is tricky to tunnel in and out of.

The DB philip sent you is still on [AWS RDS] but it's an always-on, dedicated RDS Postgres DB that lives outside our virtual cloud (so no need to tunnel in). It costs us about $12-15 USD per month. It's fine for development but would probably fall over under any serious load (maybe that's not a concern here though).

Getting up and running with the AWS stack takes a little work but if there's enough demand maybe we could put a tutorial or a series of sessions together.

**Comment by nick4rivers** [comment]
@MattReimer - good info and reference. This is about the answer I expected, basically that there is a cost of entry in terms of $ and effort/know how.

@joewheaton, the reason I'm asking is:
 - I put together a [workflow for this ticket ](https://www.youtube.com/watch?v=bl_vCSAG2YQ) yesterday.
 - I have a set of tutorials for hosting PostGIS dbs specifically designed for QGIS - which I may explore and circle back around with you all later.

**Comment by philipbaileynar** [comment]
Nick why don't we just integrate this into the existing roverscapes postgis?

**Comment by joewheaton** [comment]
## Feedback
A few responses. To @MattReimer comment:

> The DB philip sent you is still on AWS RDS but it's an always-on, dedicated RDS Postgres DB that lives outside our virtual cloud (so no need to tunnel in). It costs us about $12-15 USD per month. It's fine for development but would probably fall over under any serious load (maybe that's not a concern here though).

- Everything we're doing now is "just development". Our aducience of users are our employees (Anabranch/USU) and our project partners (so small numbers of trusted, but not necessarily super skilled... i.e. a form would help keep them on rails) partners. There will not be a "serious load", and things that might have one get upgraded to something more serious and real ;).

From:  @nick4rivers 

> This is about the answer I expected, basically that there is a cost of entry in terms of $ and effort/know how.
This is not the right conclusion entirely @nick4rivers. Combining what @philipbaileynar suggested using our current riverscapes postgis for this (i.e. the BRAT), there is negligible cost of entry (i.e. just creating the new feature class and attributes). We could do this in under an hour.  Also, the effort/know how is something you could get there very quickly on. What you should take away is that because we pay for these things to be hosted, it is worth not building a whole bunch of different ones. However, $12 to $20 a month is nothing and if we have one playground container we use to put lots of these sorts of things into, that is well worth doing.

From: @nick4rivers 

> I put together a workflow for this ticket yesterday.
I loved the video for how to do this as a workflow in QGIS. However, please update the symbology to match/expand the one I provided for you. 


### Lets Do It
Finally, to make this actionable ticket, @philipbaileynar can you please work with @nick4rivers to:
- [ ] Add a polygon feature class to the `brat_parameters` PostGIS Database and call it `Sierra_Meadow_Classification` (in Weber's video this is called `kern-meadow-classification` (it is a hydrogemorphic classification of meadow types developed for the Sierras and it may be used in other projects in the sierras)
- [ ] Include the categorical attribute fields in @nick4rivers [video](https://youtu.be/bl_vCSAG2YQ?t=470) of "Meadow Type" and "Condition" with the categorical choices he specified.
- [ ] Include the note attribute field
- [ ] Include the automatically calculated geometry fields of "area_acreage" and "area_hecatares"
- [ ] Add new categorical attribute fields of "Observer" (so we know if it is Sabra* (default), Nick, Joe, etc) 
- [ ] Add an "Assessment Snapshot" attribute field with choices of (Nick we need this for doing planning and monitoring so we don't need a new method of collecting the same thing for different assessment snapshots) :
  - Current Conditions * (default)
  - Historic Estimate
  - Recovery Potential
  - Monitoring Observation
- [ ] Add symbology that @nick4rivers will provide after I approve it (i.e. it needs to look like the one I gave you expanded to the Tier 2 list you went with)

**Comment by nick4rivers** [comment]
All - we can do this - and it will ultimately make it easier to take this stuff in the field with us for editing and ground truthing in July.

Note - The workflow and QGIS project/resources have been sent to Sabra and she should be getting started adding data. We should get some feedback from her soon to help refine the workflow / data model.

@philipbaileynar - I've got just a bit of work to do on the symbology / values for the `meadow_type` attribute but will follow up when I get some feedback.

**Comment by joewheaton** [comment]
> All - we can do this - and it will ultimately make it easier to take this stuff in the field with us for editing and ground truthing in July.
> 
Excellent. I added milestone.
> Note - The workflow and QGIS project/resources have been sent to Sabra and she should be getting started adding data. We should get some feedback from her soon to help refine the workflow / data model.
> 
Keep us posted how that goes. If you need to start new ticket for discussion on that just mention this thread for reference.

> @philipbaileynar - I've got just a bit of work to do on the symbology / values for the `meadow_type` attribute but will follow up when I get some feedback. @joewheaton - I'll revisit your symbology as well as we finalize this.

- [ ] @nick4rivers please please make a new thread to isolate the creation of the meadow type symbology into its own task we can add (check this box when done) and work with Chalese (get her GitHub account added here so we can mention her) and I to dial that in. As discussed above, we're close.

**Comment by nick4rivers** [comment]
@joewheaton - I created a ticket for #26, but not sure I got the scope right. Have a look and fine if you get a chance.

**Comment by joewheaton** [comment]
Done for QField. Closing for now as this is likely not yet a generic design feature.
