### ISSUE TITLE
Only bring in data types that exist in DCEs when opening project

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#213]
@joewheaton what are your thoughts on this? I've been messing around and one thing that bothers me is how when you open a design every structure type, structure point, Structure complex extents, and zones of influence are shown in the layer panel whether or not they exist in that particular DCE. Any reason to not change it so that only the ones in the design/DCE are shown? 
![image](https://user-images.githubusercontent.com/97305413/231807439-ca4e6afe-79d6-4d1d-9c7d-b06b1c98d8a2.png)
In this case there are no structure points or complex extents but they autopopulate the layer tree. Also in structure lines it shows BDA postless even though it doesnt exist in DCE. This same idea applies to all the different sampling protocols.

**Comment by philipbaileynar** [comment]
We need to be careful and think through all the implications. For example, if a symbol category is not visible then any features with that category will not show in the map. So if you digitize a new feature and assign it to a category for which there is no symbol category, then the feature will disappear once the attribute form is closed. The feature is correctly stored in the feature class - it's just not displayed. This prevents us from intervening when a DCE layer is added to the map and removing those symbol categories are present in the data. What if the user wants to digitize a symbol category that is defined but not already in use.

Note that QGIS does allow you to turn symbol categories on and off without actually deleting them:

<img width="819" alt="Screenshot 2023-04-14 at 9 03 30 AM" src="https://user-images.githubusercontent.com/8645379/232096753-99ab2743-207a-4e87-92dd-137712829a61.png">

We can investigate whether QGIS sends "signals" at relevant times; specifically just after a feature is digitized. This would allow us to curate which symbology categories are visible when a layer is added and then again after every feature is digitized.

Task: @KellyMWhitehead can you please investigate whether there's a signal fired after each feature is committed to the database?

**Comment by KellyMWhitehead** [comment]
Try using the "Filter Legend by Map Content" option on the Table of Contents:

![Image](https://github.com/Riverscapes/QRiS/assets/10746997/75626f2d-789c-48e4-803c-fc03f4b079dd)

Note that this is dynamic as you pan around the map.

I think this will resolve some of the display issues with layers containing large symbologies, but reopen if we need additional enhancements.

**Comment by joewheaton** [comment]
This is done.
