### ISSUE TITLE
Attribute table problems

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#214]
Watch the video of the problem [here](https://www.youtube.com/watch?v=txQtNsV3lDs), some weird things going on.

**Comment by joewheaton** [comment]
@Jdgilby this is really helpful. Thank you. This is weird. @KellyMWhitehead and @philipbaileynar and I are all distracted on the Data Excahnge at the moment. I just watched this and this is quite odd. I don't understand some of this stuff that makes these forms show all the nice drop downs (@nick4rivers figured that stuff out). It is really odd that if forgets those and then thinks the data isn't there. I have experienced this before too and didn't know what was going wrong.  We'll dig in soon.

In meantime, can you share the project with us and maybe the raw file you are copying over from?

**Comment by Jdgilby** [comment]
[Heres](https://drive.google.com/file/d/11KeXRWUTeV7YkrwwRiW6yEp12RNSKkt3/view?usp=share_link) the QRIS project. And [heres](https://usu.box.com/s/vn738wp46irhzksh69nyrtj6lsjob61h) the structure data I'm Importing.

**Comment by philipbaileynar** [comment]
Thanks @Jdgilby  Lots of juicy problems here. Having the actual project data is super helpful!

1. Obviously the attribute table issue.
2. Something wrong with projections.
3. Spatial extents not working (this might be related to the projection issue).

Assigning to Kelly to investigate.

**Comment by philipbaileynar** [comment]
Just talked with @KellyMWhitehead and we think this has something to do with cutting and pasting features from external feature classes. QGIS is either getting confused or failing to find the right columns, it's doing weird things.

@Jdgilby can you confirm that this all started when you cut and paste features into the affected layer?

**Comment by Jdgilby** [comment]
@philipbaileynar Yes that is correct. However, the issue has only popped up when cut and pasting into the 'structure lines' feature class.

**Comment by KellyMWhitehead** [comment]
> [Heres](https://drive.google.com/file/d/11KeXRWUTeV7YkrwwRiW6yEp12RNSKkt3/view?usp=share_link) the QRIS project. And [heres](https://usu.box.com/s/vn738wp46irhzksh69nyrtj6lsjob61h) the structure data I'm Importing.

@Jdgilby, I need permissions/access to view the files in these links. Thanks!

**Comment by KellyMWhitehead** [comment]
This issue will be resolved with the new DCE import tool (see https://github.com/Riverscapes/QRiS/issues/221 ).

Closing for duplication.
