### ISSUE TITLE
Centerline, suggestion rather than bug

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#215]
Not sure this is necessarily an issue. I'm sure its already a known thing but might be good to have some sort of instruction/documentation built in when using the centerline tool. I can see this causing problems for users who don't use GIS as much. 
![centerlines](https://user-images.githubusercontent.com/97305413/233697147-977688b4-008d-4a6d-b3d3-41178db503db.png)
If your start/end point lines for centerline generation cross a fingerlike feature with open space in between the centerline wont generate. Easy fix to just move the line where it wont be crossing more than 2 boundaries. But it might not be the most intuitive fix to everyone.

**Comment by KellyMWhitehead** [comment]
Thanks @Jdgilby, I will certainly take this into consideration. This is a new approach for generating centerlines. Previously, we would just use start/stop points near the end of the polygons, but this would often result in a skewed centerline. This new method largely avoids this issue, but as you have pointed out, there are some nuances with this. Some involve better documentation/instructions, and others will require code improvements (i.e. multi threaded channels, islands, etc).

Again, thanks for your continued support with testing and putting the tools through some paces!

**Comment by philipbaileynar** [comment]
I recommend intersecting the user-drawn transect with the polygon. Then only use the longest segment of the transect intersection as the feature to drive the centerline calculation.
