### ISSUE TITLE
Install Failure V0.5

### ISSUE THREAD

**Issue by AldenShallcross** [Riverscapes/QRiS#216]
An error occurred during execution of following code:
pyplugin_installer.instance().installFromZipFile(r'\\blm.doi.net\dfs\mt\so\users\ashallcross\My Documents\GIS\qris_deploy-0_5_0.zip')

Traceback (most recent call last):
  File "", line 1, in 
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\pyplugin_installer\installer.py", line 650, in installFromZipFile
    self.processDependencies(pluginName)
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\pyplugin_installer\installer.py", line 682, in processDependencies
    dlg = QgsPluginDependenciesDialog(plugin_id, to_install, to_upgrade, not_found)
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\pyplugin_installer\qgsplugindependenciesdialog.py", line 92, in __init__
    _make_row(data, i, name)
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\pyplugin_installer\qgsplugindependenciesdialog.py", line 63, in _make_row
    widget.use_stable_version = data['use_stable_version']
KeyError: 'use_stable_version'

Python version:
3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

QGIS version:
3.24.3-Tisler 'Tisler', cf22b74e

Python path:
['C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python', 'C:/Users/ashallcross/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/ashallcross/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~1/QGIS32~1.3/apps/qgis/./python/plugins', 'C:\\Program Files\\QGIS 3.24.3\\bin\\python39.zip', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\DLLs', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib', 'C:\\Program Files\\QGIS 3.24.3\\bin', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib\\site-packages', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib\\site-packages\\GDAL-3.4.3-py3.9-win-amd64.egg', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS32~1.3\\apps\\Python39\\lib\\site-packages\\Pythonwin', 'C:/Users/ashallcross/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python']

**Comment by joewheaton** [comment]
@philipbaileynar and @KellyMWhitehead I am closing this. We will now funnel this sort of feedback through freshdesk. All the same, we should keep our eye out on crashes reported by users here.  I think these are slipping through cracks because they are NOT assigned to anyone.
