### ISSUE TITLE
Please renumber 0.5 to 0.2. 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#218]
@philipbaileynar and I discussed, the jump to 0.5 was preamture and doesn't makes sense. We will reassess the milestones, but lets renumber to 0.2 for now. I am excited to start testing this. Thanks @KellyMWhitehead

**Comment by KellyMWhitehead** [comment]
version numbering has been downgraded with this [new release](https://github.com/Riverscapes/QRiS/releases/tag/0.2.0-alpha)
