### ISSUE TITLE
Metadata Widget

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#220]
Most of our database tables possess a metadata column but we currently have no user interface tool for the user to enter data.

Please build a new reusable Qt widget that has a data table with two columns:

- Key (string)
- Value (string)

This widget should be reusable so that we can insert it on a table in several places in the user interface. When it loads the parent dialog will send the metadata widget a JSON string that it will parse and display as key, value pairs. The user can then add, edit, delete pairs. When the parent form closes/saves, it will request a JSON string from the metadata widget that is then saved to the database.

Note here how the metadata widget does not know the context for which it is being used. It doesn't know whether the metadata belongs to a raster surface, vector layer or data capture event. It's just a dumb two column table.

The test case for development should be as a new tab on the raster surface properties form.

<img width="612" alt="Screenshot 2023-07-05 at 10 03 13 AM" src="https://github.com/Riverscapes/QRiS/assets/8645379/f1e8c1b8-c567-4a1c-9927-800dcdba643f">

# Other Notes:

- Key and value are both required fields.
- One idea we had in Logan last week was to "seed" the metadata table with some default keys. i.e. for rasters we might want "source" and an "acquisition date" keys. Maybe the widget could take an optional list of keys and pre-populate the table with these keys (and some default values per the previous point) to guide the user.

Here's a screenshot of a similar table that I built for another piece of software.

<img width="511" alt="Screenshot 2023-07-05 at 10 00 10 AM" src="https://github.com/Riverscapes/QRiS/assets/8645379/3c3cc7c5-b927-45e2-936b-8c41f69d6a3e">

**Comment by KellyMWhitehead** [comment]
This is ready for testing in the next release.

**Comment by KellyMWhitehead** [comment]
A metadata widget has been created, but must be added to each of our forms as need.

This has been added to raster surfaces (version 0.2.0) and project (0.2.1).

**Comment by philipbaileynar** [comment]
@KellyMWhitehead see #232

**Comment by KellyMWhitehead** [comment]
I have added metadata widget to profiles, cross sections, masks/aoi, rasters/surfaces, context layers and the project node. 

If we need to add this to other types of forms (i.e. analysis, dce, etc), open a new ticket. These forms are a little more complex anyway, so specific design requirements will be needed anyway.
