### ISSUE TITLE
Import Existing Feature Class Tool

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#221]
# Objective

We want to make it quick and easy for users to get existing data from feature classes on their computers into QRiS data capture event (DCE) layers.

# Workflow 

The vision is that users can right click on any data capture event layer and click "Import From Existing Feature Class..." They then browse to a feature class (of the appropriate geometry type) and are presented with the following user interface form to handle "field matching". This will let the user match up fields from the existing feature class with those required by the DCE layer.

![PXL_20230706_165336608 MP](https://github.com/Riverscapes/QRiS/assets/8645379/d4bcc3e2-b358-4d2c-bbf8-d142a0ca4200)

Refinements on the diagram above:

- Note that the text fields above the table are read only.
- Probably need another read only text field for the parent event that the DCE layer belongs to.
- Maybe add a radio button above the table with the two options:
    - Import Fields (default checked)
    - Ignore Fields (this just brings the geometries in and leaves all fields blank for the operator to handle later)
- Maybe add another column beside the target field showing the data type of the target field (int, float, string).

# Considerations

- The original feature class geometry type must match the DCE geometry type. (i.e. if we are importing dam points, the user must pick a point layer. Maybe they can pick a multi-point and we explode the features duplicating the attributes?)
- Reproject the input data into the spatial reference of the DCE layer.
- The input fields dropdown musts be of the appropriate data type (integer, float, string) of the target field. This might be slippery! Different storage types (Shapefile, GeoPackage, Postgres etc) have subtly different storage types (int16, int32, int64). I think the tool needs to allow matching across the three broad categories of int, float, string.
- Be careful with strings. I think ShapeFiles do not allow null values, so we want to avoid empty strings in the DCE layer.
- Each field from the original feature class can only be selected once.
- Lookups might be problematic. We use normalized attributes in QRiS (e.g. dam type is a side table with IDs that join back to the main feature class table). Most legacy data probably uses strings ("Log Jam", "Beaver Dam"). We need to handle this or the utility of the tool will be very limited.
- When the process is complete report back the number of new features added to the DCE layer as well as the number of features in the original feature class.
- A "would be nice feature" would be to add metadata somewhere in QRiS as to the original feature class and FID of each feature imported. Makes for a nice audit trail.
- Probably want to perform geometry validity checks to ensure only clean geometries are coming in.

# Other Notes

- Note that this tool is only for DCE layers. Most other vector types (AOI, profiles, transects etc) already have an "import existing" right click menu option.

# Future Enhancements

The importer will never be perfect. We could have a checkbox for "Create copy of input feature class with final FIDs". This would duplicate the input feature class (alongside the original one) with the QRiS FIDs appended as an attribute column. This gives the user the option to join the QRiS DCE layer to this temporary copy and perform manual attribute updates using basic QGIS functionality.

FYI @joewheaton @Jdgilby

**Comment by KellyMWhitehead** [comment]
This is built and ready for testing in the next release (0.2.1?). 
- The interface is modified from the initial proposal, and is instead driven by the input fields and what 'action' to apply for each one:
![image](https://github.com/Riverscapes/QRiS/assets/10746997/088da91f-28f6-481b-82b1-bbc37ae69d63)
- Fields can be ignored (not imported), added to the metadata json for that feature, copied directly to a target field of the same type (target fields may only be used once) or value mapped to one or more fields (based on lookup fields. Perhaps we can relax this to user defined values in the future?).
- Value Map Interface:
![image](https://github.com/Riverscapes/QRiS/assets/10746997/114ade4c-0c00-4265-8aff-3c7697ee89ba)
- Note the value map only works for target fields with an assigned lookup table.

**Comment by philipbaileynar** [comment]
Outstanding issues after some testing:

- [ ] Try filtering the QGiS layer browser to the correct geometry type. I have an example of this in QRiS somewhere already. It's pretty easy. (No harm in keeping the existing code check in place as a backstop.)
- [ ] I was able to select an empty feature class. Please add a check for this. Warn the user and then abort the import before the "Import DCE Layer" form appears.
- [ ] I was able to select a feature class with no/undefined projection. Please add a check for this. Warn the user and then abort the import before the "Import DCE Layer" form appears. The easiest way I have found to replicate this is to create a ShapeFile, digitize a few features, then delete the `*.prj` file.
- On the Import DCE layer form:
    - [ ] change the form title to be same as right click menu text "Import DCE Layer From Existing Feature Class"
    - [ ] change the label "Event" to "Data Capture Event".
    - [ ] change the label "Targer Feature Class" to "Target Layer".
    - [ ] Move the radio buttons up onto the same horizontal line as the "Fields" label (if possible. Not a biggie.)
    - [ ] Stub an empty help page out so the help button doesn't go to a 404 page.
- [ ] Missing Existing Values (see bug text below)

## Missing Existing Values

Steps to reproduce:

1. Tried to import [this ShapeFile](https://github.com/Riverscapes/QRiS/files/12186673/point_cloud_1996_utm.zip)
 into dam and jam points.
2. For the `EL` field I chose "Map Values".

Observed

On the map values form the existing values did not show up in the left column

Expected

Should we allow existing floating point columns to use `Map Values`? I guess it might be useful....

<img width="664" alt="Screenshot 2023-07-27 at 11 26 31 AM" src="https://github.com/Riverscapes/QRiS/assets/8645379/4e30b7c1-1671-44c9-9b24-6123322b1e92">

**Comment by KellyMWhitehead** [comment]
A few notes:
> Try filtering the QGiS layer browser to the correct geometry type. I have an example of this in QRiS somewhere already. It's pretty easy. (No harm in keeping the existing code check in place as a backstop.)

I'm using the 'browse_vector' method we use in other places. The filtering for [QgsDataSourceSelectDialog](https://qgis.org/pyqgis/master/gui/QgsDataSourceSelectDialog.html) appears to be at the [raster layer vs vector layer level](https://qgis.org/pyqgis/master/gui/Qgis.html#qgis.gui.Qgis.LayerType), but I don't see anywhere that sets a geometry filter. Fixing this would improve the other places we browse out for vector datasets.

Missing Existing Values

- Fixed the missing values bug (just needed to convert the value to string in the cell)
- I removed real types from the Map Value option, as this tool works best for categorical data.
- I now also do not make the Map Value option available for fields that do not have any values.

**Comment by Jdgilby** [comment]
Ive been messing around with this and so far its very useful. But definitely have some feedback.
https://youtu.be/rEk4HWkNAqw
