### ISSUE TITLE
Mac Closing Error

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#222]
Hey - I think that QRiS causes an 'unexpectedly quite' error on macs. It has been there for at least the last couple version but thought I should bring it up. Happens when you close Q. attached a text file with the message.

[closing error.txt](https://github.com/Riverscapes/QRiS/files/12074380/closing.error.txt)

![Screen Shot 2023-07-17 at 4 15 17 PM](https://github.com/Riverscapes/QRiS/assets/34071692/d357daa7-13c9-4b47-bd36-ccde06952209)

**Comment by joewheaton** [comment]
@nick4rivers closing for now as I haven not heard about this in recent releases. Reopen with more specifics if it is recurring.
