### ISSUE TITLE
Promote Watershed Catchment to AOI

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#224]
Add right click menu to the watershed / stream catchment item in the QRiS project for "Promote to AOI".

@joewheaton likes to teach folks to use these catchments to define the AOI.

**Comment by KellyMWhitehead** [comment]
Added to version 0.2.1.

**Comment by Jdgilby** [comment]
@joewheaton @philipbaileynar Should we also have the ability to promote to sampling frame. Makes sense if importing DGOs from RV into context that they can be promoted to sampling frame rather than having to browse back into the .gpkg for it.
