### ISSUE TITLE
Add Temporary layers to QRiS

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#226]
@Jdgilby mentioned that he likes to use QGIS temporary layers for ephemeral GIS data. @joewheaton also uses these to subtract the watershed catchment polygons to derive the drainage wings for a reach. It would be nice if we can import these temporary QGIS map layers into QRiS.

The problem I foresee is that we probably have no way of adding to the right click menu on a layer in the QGIS map ToC. Please research whether this is true.

A backup strategy is that most QRiS project tree items already have a right click menu with "Import Existing...." and "Create New...". We could add a third item that is "Import From Temporary Layer...". This would pop up a simple modal dialog with a list of the current temporary layers in the map. The user picks one and we import the geometry into the relevant layer that they right clicked on in the QRiS project tree. This approach would be easy to implement for all vector QRiS project tree items.

**Comment by philipbaileynar** [comment]
Currently most things in the QRiS tree have two right click menu items:

- Import existing
- create new

We could add a third "Import from temporary layer...". this pops up a modal dialog that lists all current temporary layers in the map (of the correct geometry type) and let's the user pick one to get imported into the QRiS layer type that hte user right clicked on.

**Comment by KellyMWhitehead** [comment]
Explored adding right click to the layer tree menu. I was able to add a custom menu item but had trouble integrating it with the existing menu items or restoring the menu when qris closes. I will proceed with adding the import from temporary layer menu item to the qris project tree.

**Comment by philipbaileynar** [comment]
There's always going to be a match-up challenge....

If you right click in the qgis ToC then you have to pop a modal of which qris later to target. 

Or if you right click in qris then you have to pop a modal of which map layer to source. 

So I recommended the latter because filtering the map layers (by geometry type etc) probably gives you more control.

**Comment by KellyMWhitehead** [comment]
ready for 0.2.4

**Comment by Jdgilby** [comment]
@KellyMWhitehead  A few things I have found, Only works in AOI and not in Context. It must be reprojected to EPSG 4326, it doesn't reproject like other imports do.

**Comment by KellyMWhitehead** [comment]
Updates for 0.2.6:
- Fixed the projection transformation issue, the import will now reproject layers to epsg 4326.
- This should now be working for all layer types, including DCE and context.

**Comment by Jdgilby** [comment]
@KellyMWhitehead Temporary import does not seem to work on Sample Frames. Everything else appears to work. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/ec2419b5-ff52-4c26-aff3-5ebb7c0ce1bf)

**Comment by KellyMWhitehead** [comment]
Fixed in version 0.3.21.

**Comment by joewheaton** [comment]
This works. Open with more specific bugs or feature enhancements if appropriate.
