### ISSUE TITLE
Export Metrics Table

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#227]
Add a button to the analysis dockable window to "Export Metrics Table". This will pull up a modal dialog with the following controls:

- Radio button for:
    - Current Data Capture Event
    - All Data Capture Events
- Radio Button for:
    - Current Sampling Frame Polygon
    - All Sampling Frame Polygons
- Drop down for format:
    - CSV (default)
    - XML
    - JSON

Additional Idea:

What about adding ShapeFile to the export formats? This would produce a feature class with the sampling frame polygon and all the metrics as columns? Unsure how we would handle multiple DCE:
    - Duplicate feature for each DCE? Probably confusing for users.
    - Duplicate metric columns? Could be lots of DCE!

FYI @joewheaton @jtgilbert @Jdgilby @nick4rivers

**Comment by philipbaileynar** [comment]
Overall this is really good!

1. Put the format and export path in a grid so they align left and right.
2. Help page needed.
3. Expand both DCE and SF acronyms.
4. Got this error opening the Excel spreadsheet. Here's the [export_analysis.xlsx](https://github.com/Riverscapes/QRiS/files/12383590/export_analysis.xlsx). I was using Microsoft Office Professional Plus 2019.

# Idea

Occurs to me that we might want an export like this available on the right click of the Anaylsis folder in the QRiS project tree that is capable of exporting data from all analyses? Don't need the UI form because it would just do all analyses and all DCE and SF.

**Comment by KellyMWhitehead** [comment]
There is a potential issue with creating xlsx documents on mac. Additional research and testing is required, so removing excel option for now.

**Comment by KellyMWhitehead** [comment]
It appears the only excel option available without pip installing another library is xls. 

I will reinstate the excel export with .xls format only.

**Comment by KellyMWhitehead** [comment]
changes for version 0.2.5:
- xls format added
- right click on an analysis in project tree brings up the form, but only to select the output format and path. All other options are hidden and will export all dce and sampling frames for that analysis
- right click on analysis folder in project tree will allow you to export all analyses in one table. The form will open to specify format and file path. This option only appears if there are one or more analyses in the project.

**Comment by joewheaton** [comment]
I tested this. It seems to be working nicely for all three formats. I'm fine with `*.xls` instead of `*.xlsx`
