### ISSUE TITLE
Analyses not working right.

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#228]
I swear Ive got this to work before...Anyways, I tried to do an analysis and it doesnt appear to calculating dam and jam count. Also just curious about other metrics. Will method/layer/i dont remember what were calling it have an associated metric for analyses? Vegetation extent, channel unit points, thalwegs, etc.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/e3a0f336-cacd-4c3a-8b5e-248f0c31463d)

**Comment by Jdgilby** [comment]
@KellyMWhitehead Different project today. Tried to run an analysis and got this error.

WARNING    Traceback (most recent call last):
              File "C:\Users/joshu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 228, in cmdCalculate_clicked
              self.load_table_values()
              File "C:\Users/joshu/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_analysis_docwidget.py", line 112, in load_table_values
              mask_feature_id = self.cboSampleFrame.currentData(QtCore.Qt.UserRole).id
             AttributeError: 'NoneType' object has no attribute 'id'

**Comment by philipbaileynar** [comment]
@Jdgilby it can be time consuming to develop datatests to properly test all the potential metric calculation pathways. Can you zip and send this project to @KellyMWhitehead please?

**Comment by KellyMWhitehead** [comment]
@Jdgilby Please send a copy of the project that produces this error when you get a chance. Thanks!

**Comment by Jdgilby** [comment]
@KellyMWhitehead Sorry for the delay. Most recent testing I did on updated QGIS version and the newest QRIS didn't have any issues but [here](https://drive.google.com/file/d/15xD9ofM-zYHTnfS0i7_2HkCa_Tg3xysC/view?usp=sharing) it is if you wanna poke around in it.

**Comment by philipbaileynar** [comment]
@Jdgilby unfortunately the zip file appears to be corrupt.

It's 6Gb which should be fine for box, but might have gotten interrupted on upload. Can you try and zip and send again please.

(Maybe make sure that all software accessing the data is closed - especially ArcGIS - so that there are no lock files during the zip.)

**Comment by Jdgilby** [comment]
@philipbaileynar Alright try this [one](https://drive.google.com/file/d/165IZe-CSAQtMGnpoQ3XG2eIypBQbEVgR/view?usp=sharing)

**Comment by philipbaileynar** [comment]
Worked on Windows (not on Mac). Also worked for Kelly. Thanks @Jdgilby

**Comment by KellyMWhitehead** [comment]
@Jdgilby please reopen if this issue pops up again.
