### ISSUE TITLE
Window doesn't close when editing Project Properties

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#230]
Small issue. The feature to edit does work but when you make the edits and hit ok the window does not close. Can see this causing confusion about whether edits were saved.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/a4bf3103-cbd0-48a8-a3c0-aa5893bd128c)

**Comment by KellyMWhitehead** [comment]
fixed for version 0.2.1
