### ISSUE TITLE
Ability to merge features in editing session

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#231]
When digitizing features its useful to be able to digitize chunks of a feature rather than draw out the entire polygon, especially with larger more complex areas. When trying to merge features this error is thrown. Sometimes features will but most the time they wont, issue with digitizing? **"Merge failed: Resulting geometry type (multipart) is incompatible with layer type (singlepart)"**
![image](https://github.com/Riverscapes/QRiS/assets/97305413/6c95151b-6b02-4910-b078-6d1a70d97f10)
The work around is do qgis processing steps and reimporting, which seems to go against one of the use cases of having premade containers for layers.

**Comment by Jdgilby** [comment]
@KellyMWhitehead A further update to this. sometimes the merge happens with no error but then both features disappear altogether.

**Comment by KellyMWhitehead** [comment]
@Jdgilby 

It seems that there might have been a bug in Qgis that was causing some merging issues. I downloaded the latest (3.32) and seem to be having better success with merging features. I suggest giving that a try and let me know if you see improvement.

**Comment by Jdgilby** [comment]
@KellyMWhitehead I'll poke around with it some more, however, I forgot to comment and say I believe I found that the issue was that the layer was opened and being edited simultaneously in 2 DCEs. Do we need to open another issue that mentions this and find some sort of way to handle that potential problem?

**Comment by KellyMWhitehead** [comment]
@Jdgilby The latest version (0.2.4) will prevent two qris layers from being in edit mode at the same time, which should address this issue. 

It seems that the merging issue is resolved for now? I am going to move this ticket along, but please reopen if there are still issues with merging that I have not yet resolved.
