### ISSUE TITLE
Add DCE Layers

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#234]
Add a new button below the DCE layers `Add >>`. The new button will have the text `Add From DCE >>`.

This button brings up a modal that has a dropdown of any existing DCEs. The user selects an existing DCE and returns to the main form where the layers from the selected DCE are moved across to the list on the right. This is nothing more than a shortcut to get the same layers in the new DCE: "These are the layers I used last time, help me start a new DCE with the same layers".

<img width="623" alt="Screenshot 2023-07-27 at 4 06 36 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/94b038f3-02a8-48df-bc0c-4c7f22d445af">

FYI: @joewheaton @Jdgilby

**Comment by KellyMWhitehead** [comment]
Included in version 0.2.6

**Comment by joewheaton** [comment]
This is working well.
