### ISSUE TITLE
Copy Features From Existing DCE Layer

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#235]
The goal is to make it quick for users to reuse existing features from an earlier DCE. For example, when digitizing the second DCE in a project, one might want to get started with the Thalwegs from the original DCE, then just tweak them to the latest configuration.

Add a right click menu item to all DCE layers with the text "Copy From Existing DCE Layer...". Choosing this menu item pops up a modal that has a dropdown of existing DCEs (same modal as #234 ??). Once the user picks a DCE the features of the corresponding layer in that DCE are copied to the selected DCE.

FYI @joewheaton @Jdgilby

**Comment by KellyMWhitehead** [comment]
ready for showtime in 0.2.6

**Comment by joewheaton** [comment]
Works.
