### ISSUE TITLE
Error creating new project in 0.2.1

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#239]
Reported by @nick4rivers:

> Hey, it's probably me but I keep getting this a python error in QGIS 3.30 when trying to create a project - I think it's some dependency thing. Install doesn't work in 3.22, another weird error. Tried a couple user accounts on each Q version and got the same thing. Let me know if I can test anything else that might help find the bug, or my bug?

![image](https://github.com/Riverscapes/QRiS/assets/8645379/ebec3016-673c-45c3-b4d7-6c0d2d3e41eb)

**Comment by KellyMWhitehead** [comment]
@nick4rivers I have identified a bug when creating new projects. I will have a fix out shortly.

I have been developing using Qgis 3.28, the current LTR.
