### ISSUE TITLE
Create a website using template

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#24]
We should stub out a documentation website using [the template](https://github.com/Riverscapes/riverscapes-jekyll-theme) and put in docs folder of this repo. @nick4rivers, you should include tasks for every tool/feature that include the documentation as we go.  Each time we create something, we can just put a little standard tool description in the help, and/or record a video or take a screen shot. It will force us to populate things as we go. An issue should not be closed until a task in it that includes the documentation is done. This will be critical to getting Anabranch employees (and ETAL) to be able to use it.  This is much more important on what will be operational grade or professional grade tools (fundamental for commercial grade). Many of our other tools and active repos are production grade models, where such documentation is important, but not as mission critical. 

Just, minimally paste following into each enhancement ticket:
` - [ ] Create documentation entry in website`

Also, you are doing such a nice job specifying your enhancement requests, that those are essentially the first cut of mark down for the tool documentation.

**Comment by nick4rivers** [comment]
@joewheaton - this is on my list, I would love to have a decision on a name #25  before setting this one up.

**Comment by joewheaton** [comment]
There is a website at: https://riverscapes.github.io/QRiS/
