### ISSUE TITLE
Fix passing properties to form for Editing of DCE properties in tree

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#244]
Two things here, you right click to edit and it brings up the initial window when creating a DCE, whatever was initially input should be preserved. Right now everything defaults back to blank. I was just trying to change the name of my asbuilt. And secondly it wont save any changes. Heres the error. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/a8933ef3-107c-4959-8f83-8993063f0c8b)

**Comment by KellyMWhitehead** [comment]
Found and fixed the bug for this. Will be included in version 0.2.3
