### ISSUE TITLE
Cannot save geometry in design mode

### ISSUE THREAD

**Issue by guswathen** [Riverscapes/QRiS#248]
I am trying to do a new structural design using 0.2.2 QRIS. When I draw structure lines or points I cannot save the edited geometry.
![image](https://github.com/Riverscapes/QRiS/assets/142433902/87d063cb-23cc-4f9f-a00f-ed64e999d038)
Here is the error message
Could not commit changes to layer Structure Lines

Errors: ERROR: 1 feature not added.
  
  Provider errors:
      OGR error creating feature -10: failed to execute insert : FOREIGN KEY constraint failed

**Comment by guswathen** [comment]
I deleted the whole project and started over. Seems to be saving now. I accidentally left the former project open a long time without saving the recorded geometry, so the fault is mine

**Comment by KellyMWhitehead** [comment]
Thanks for the update - these types of issues are important to document so we can try to build in some guardrails to keep things running smoothly.

**Comment by philipbaileynar** [comment]
@guswathen please close this issue if it is resolved

**Comment by guswathen** [comment]
Well this same issue has occured again. I just opened a project and started adding new features, and when I tried to save I could not:
![image](https://github.com/Riverscapes/QRiS/assets/142433902/fdf7935a-1db8-471b-935f-52163b50b302)

**Comment by philipbaileynar** [comment]
@guswathen what version of ARiS and QGIS please?

**Comment by guswathen** [comment]
qgis - 3.28.8
qris - 0.2.5

I have been drawing structure lines on two different creeks as part of the same qris project. To differentiate within the attributes table, I called the first creek event id "1" and the second creek event id "2". The First creek saved but second creek would not. In poking around the properties of structure lines under Source I see there is a "Provider Feature Filter" of event_id = 1. I changed the event id of creek 2 to "1" and was able to save the features.

**Comment by guswathen** [comment]
Since I was able to find a resolution, do you want me to close this issue @philipbaileynar ?

**Comment by philipbaileynar** [comment]
I'm concerned that you needed to resort to "poking around". Any chance we can get a quick video showing the problem and your workaround please?

**Comment by guswathen** [comment]
Yes I can do that tomorrow morning

**Comment by joewheaton** [comment]
Did this get resolved?

**Comment by KellyMWhitehead** [comment]
I think this is resolved, the issue was caused when edits were being made to a QRiS managed field.
