### ISSUE TITLE
Easy Metrics Requested

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRiS#249]
Easy in the sense of "let's get any low hanging metrics in the QRiS system". 

What we currently have:
- dam and jam count
- Dam Crest Length
- Valley Bottom Area
- Centerline Sinuosity
- Centerline Gradient

We currently have a metric calculation library that can produce counts, lengths, areas, sinuosity and gradients for any of our existing dce/design layers. I am also happy to expand this library if there are other simple calculations we need to add.

**Comment by joewheaton** [comment]
Thanks @philipbaileynar for this prompt. I had an inkling we started this at one point and I was write. We made a `[QRiS Protocols Methods and Layers Google Sheet](https://docs.google.com/spreadsheets/d/18NRAJyO16WeUhOpaYJbjUdmKzbFAkJglrsdWvmzPcAU/edit#gid=0)' and that had a tab for metrics we never populated. I'm going to start addressing this there.

**Comment by joewheaton** [comment]
WORKING... WAIT
> What we currently have:

> - dam and jam count


> - Dam Crest Length


> - Valley Bottom Area


> - Centerline Sinuosity


> - Centerline Gradient

## From "Available Layers"
dam and jam count
Dam Crest Length
Valley Bottom Area
Centerline Sinuosity
Centerline Gradient
### Dam/Jam Survey
- Dam Crests
- Dam Points
- Jam Points

#### Riverscapes Context
- Valley Bottoms
- [ ] Valley Bottom Area 
- [ ] Valley Bottom Centerline Length
- [ ] Integrated Valley Bottom Width (Valley Bottom Area/Valley Bottom Centerline Length)
- [ ] Valley Bottom Area / Unit Length (e.g. _Hectares/Km_ or _Acres/mile_)

### Channel Units
- Riverscapes Context
- 
### Beaver Dam Survey
- BRAT CIS
  - BRAT CIS
  - BRAT CIS Reaches
### Methods without a Protocol
- Test Orphan Method
  - Thalwegs
  - Centerlines
  - Valley Bottoms
### Layers without a Method
- Active Extents
- Inundation Extents
- Junctions
- Geomorphic Unit Extents
- Geomorphic Unit Points
- Tier 3 Geomorphic Units
- Channel Evolution Model Stages
- Vegetation Extents
- Floodplain Accessibility
- BRAT Vegetation Suitability
- Channel Unit Points
- Channel Unit Polygons

**Comment by joewheaton** [comment]
We have what we need now.
