### ISSUE TITLE
Hyperlink metadata item

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#250]
Detect when a metadata item is a URL, make sure that it highlights (i.e. blue and underline) and can be clicked to launch browser.

You might need to fake this if Qt can't put a hyperlink in a cell natively.

**Comment by philipbaileynar** [comment]
FYI the same feature might be needed in QRAVE.

**Comment by joewheaton** [comment]
@philipbaileynar, I still really, really want this.

**Comment by KellyMWhitehead** [comment]
This has been on the books for a while, here it is! Version 0.9.5

![Image](https://github.com/user-attachments/assets/9892e2e9-277e-4e22-835f-a49c87cf4810)
