### ISSUE TITLE
Add button to left of metric calculations in Analysis

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#255]
Its not obvious at all that you can click into each metric to look at/calculate individual values. See below:
![image](https://github.com/Riverscapes/QRiS/assets/97305413/ce4a7a66-6d9a-44de-aea3-f325010b48d2)
A button here to get to here:
![image](https://github.com/Riverscapes/QRiS/assets/97305413/414602f5-5942-435b-9141-ed49b02f71a6)

**Comment by philipbaileynar** [comment]
Thanks for the feedback @Jdgilby.

Can we sit on this one for a short while? I feel that double clicking on rows in a table is pretty standard behaviour to access properties/edit the row. However if you feel strongly that this is too subtle and after some reps you still finding it confusing, then we can consider a column of buttons.

**Comment by joewheaton** [comment]
This is good feedback to consider as we revisit Analyses shortly.

**Comment by Jdgilby** [comment]
@philipbaileynar @joewheaton @KellyMWhitehead I still feel like this feature is not obvious at all. I actually forgot it was possible until coming back to this issue.

**Comment by KellyMWhitehead** [comment]
A single click on the edit icon will open up the metric calculation form. Double clicking the row will also bring up the form.

![image](https://github.com/Riverscapes/QRiS/assets/10746997/6ebb184c-4bf0-40b1-9d54-8541979b93a5)
