### ISSUE TITLE
Feedback on Release 0.2.4

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#256]
## Added
- [x] Add Delete Right-Click to Watershed Catchments
- [ ] Ability to import temporary layers to qris project
See issue #226 (reopened)

## Changed
- [x] Limit editing to only one QRiS layer at a time (does not apply to non-QRiS layers)
- [x] Disabled exporting metrics table to excel format (temporary)
Mentioned in #251 
- [x] Right Click "Edit" menu changed to "Properties" and associated window titles fixed

**Comment by joewheaton** [comment]
@Jdgilby, continue to do this for new releases, but assign it to yourself. This is now moot.
