### ISSUE TITLE
Fail to import DCE layer from existing feature class, specifically for Structure Lines and Points

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#258]
I've tried multiple workarounds and get this issue everytime. I was able to successfully import Complexes.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/f2d69f99-695c-449d-badb-7c3f6988e8c3)
It does however show in the attribute table that 45 out 102 features in this case were imported.

![image](https://github.com/Riverscapes/QRiS/assets/97305413/1c5168bf-c741-4a4f-afd9-089de71738d9)
They only appear after closing and reopening the project. Dont see any pattern to what was ignored vs imported.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/79e0ea65-a56a-4473-8f83-9f92e7db7a0e)
Green lines are what failed to import.

**Comment by KellyMWhitehead** [comment]
@Jdgilby could you please zip up the and share shapefile you are trying to import? Thanks!

**Comment by Jdgilby** [comment]
[design Structures.zip](https://github.com/Riverscapes/QRiS/files/12542883/design.Structures.zip)

**Comment by KellyMWhitehead** [comment]
@Jdgilby Feature with fid 147 does not have a geometry, this was throwing off the import tool. All of the features before this one imported correctly, then the tool stopped (why you see only some of the features copy over). 

I have added a check to pass over features with no geometry. A message will now appear in the log if this is the case:

![Image](https://github.com/Riverscapes/QRiS/assets/10746997/0353b582-075a-4fb5-9177-0064c761ae2c)

This will be included in v 0.2.6.

**Comment by joewheaton** [comment]
I think this is fixed. Reopen if not.
