### ISSUE TITLE
Export Design as RS Project

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRiS#259]
- [x] Ensure designs can capture 4 feature classes:
   - structure points
   - structure polylines
   - ZOIs 
   - complexes
- [x] Ensure a design can be exported as a new riverscapes project type "LTPBR Design". 
   - [x] USE THE NEW PIP MODULE to write the project file.
   - [x] Project bounds
   - [x] Need to remove space from project name.
- [x] Prepare data exchange to upload new project type.
   - [x] Project Type: LTBPRDesign
   - [x] Name: LTPBR Design
   - [x] Summary: Low-Tech Process Based Restoration Design
   - [x] Description: Low-Tech Process Based Restoration Design exported from the QGIS Riverscapes Studio plug-in (QRiS). This project contains design structures (points, lines, complexes) and zones of influence.
   - [x] Icon: use QRiS logo 
   - [ ] URL: 
- [x] Prepare Business logic. 
- [x] Symbology files (placeholders).
- [ ] Need to discuss what metadata (project, design attributes) and where to put it (project level, realization level).
- [ ] help and documentation

**Comment by joewheaton** [comment]
FYI @Jdgilby and @nick4rivers

**Comment by KellyMWhitehead** [comment]
Duplicate of #405 now that we are using RiverscapesStudio projects instead of stand alone Design.
