### ISSUE TITLE
Display Issue when adding all data to map at once  from a DCE 

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#260]
https://youtu.be/uTd_Dn_gz0E

**Comment by KellyMWhitehead** [comment]
Very strange, was able to reproduce the error. Investigating...

**Comment by KellyMWhitehead** [comment]
This ended up being a gnarly bug...

Technical Explanation
When setting the layer substring to filter the features to the event_id, qgis seemed to retain the filter in the background with each new QgsVectorLayer object getting created. This is similar to an issue we encountered with rs tools when setting attribute filters on a gpkg. 

Technical Takeaways (notes for future development): 
1) Try adding the subset string to the 'path' when creating a new QgsVectorLayer. This seems safe.
2) Be careful when using layer.setSubsetString method when adding multiple layers at once. I also tried resetting this right after I created each new vector layer, but did not seem to have an effect.
3) Adding layers to the map is simple, but is proving to be a bit complicated if we try to do several things before the layer is actually added. This is related to issue i am having when trying to set the map srs when the map is empty.

Simple takeaway: 
@Jdgilby This is fixed for version 0.2.7. Please give this some careful testing to make sure the correct attribute filters are getting applied to the newly added map layers.
