### ISSUE TITLE
Author business logic for how to expose design layers in a QRiS project (or LTPBR design project temporarily)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#266]
@KellyMWhitehead, will you point @Jdgilby to appropriate path to do this? For now I presume he could use: https://github.com/Riverscapes/RiverscapesXML/blob/master/RaveBusinessLogic/V2/LTPBRDesign.xml ?

@Jdgilby please think about how exactly you want the tree to be exposed when a) QRiS project is opened in any viewer, and b) when these are added to the Map Layers from QRiS. This is what I get opening your `QML Curation.qgz` project from #265:
![image](https://github.com/Riverscapes/QRiS/assets/9723905/07f806d0-9c7c-4b74-96df-c61eee47a898)

I don't think that is what you want. Think about the collector nodes (parent folders) and the nodes that represent the actual layer. It will be something more like:

- 'Design Name' - LTPBR Design
  - Structures
    - Structure Points
    - Structure Crests
  - Complexes
  - Zones of Influence
  - Observation Notes & Logistics
    - Point(s)
    - Route(s) or Margin(s)
    - Areas(s) 

Remember these can be labeled and called anything (more verbose is okay). Right now Kelly just exposed these as:
``` xml
            <Node label="Design">
                <Children>
                    <Node label="Structure Points" xpath="Datasets/Geopackage/Layers/Vector[@lyrName='structure_points']" type="point" symbology="structure_points" id="structure_points"/>
                    <Node label="Structure Lines" xpath="Datasets/Geopackage/Layers/Vector[@lyrName='structure_lines']" type="line" symbology="structure_lines" id="structure_lines"/>
                    <Node label="Structure Complexes" xpath="Datasets/Geopackage/Layers/Vector[@lyrName='complexes']" type="polygon" symbology="complexes" id="complexes"/>
                    <Node label="Zones of Influence" xpath="Datasets/Geopackage/Layers/Vector[@lyrName='zoi']" type="polygon" symbology="zoi" id="zoi"/>
                </Children>
            </Node>
        </Children>
```

**Comment by philipbaileynar** [comment]
Next steps:

1. @philipbaileynar to test Kelly's latest QRiS build with the "three feature class" approach.
2. @KellyMWhitehead to provide @Jdgilby with this latest version.
3. @Jdgilby to
    - create a new QRiS project
    - create a new design
    - digitize some features
    - export the project to a riverscapes project
    - Open the riverscapes project in QRAVE:
        - revise business logic until correct appearance achieved
        - revise symbology until correct appearance achieved
    - upload business logic and symbology into Riverscapes XML git repository (Philip or Kelly to help)

**Comment by joewheaton** [comment]
This is superseded now.
