### ISSUE TITLE
Provide modifications to design properties form

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#267]
@nick4rivers and @Jdgilby we need to review carefully the "Create New Design" form (same as Properties) and all its tabs. We should get wordsmithing, labels, functionality, user-interactivity, everything just like you want. To provide spec, I suggest editing this description, adding the tasks (so we can create new issues), and once spec is agreed they get assigned to @KellyMWhitehead.

## Layers
Not implemented.

This tab is greyed out currently.  
- [x] Expose all optional layers and let them choose which they include in a design
  - [x] Make mandatory layers be the Complex Polygon
  - [x] Make optional layers to be Structure points, structure crests, ZOIs, Observation Points, Observation Lines, Observation Polygons.

## Basic Properties
Currently:
![image](https://github.com/Riverscapes/QRiS/assets/9723905/dd7d5ead-c6dd-4a56-a58b-c815300ef86c)
- [x] Add at top a `Project Phase`, and allow user to provide a text label. Add a tool tip (e.g. `"Phase 1", "Phase 2", "Pilot", "Demo", "Maintenance of Phase 1", etc.)`.  
- [x] Remove `Design completed at`? Is it redundant with `Design Sources`
- [x] Remove `Representation` . It is a concept important for normal DCEs, but by definition, all designs are "future" and all as-builts are "current", and monitoring DCEs are "current". If keep, grey out, and just populate with "Future".
- [x] Add a slider control for `Percent Complete` allow incrementing by 5%. This will be optional to communicate design "status".
- [x] Change `Desktop Analysis (Remote)` in `Design Status` to 
- [x] Change  `Design Status` to `Design Status Label`, and make list:
  1. In Progress
  2. Provisional (awaiting review)
  3. Final
![image](https://github.com/Riverscapes/QRiS/assets/9723905/aaf87a54-986a-492c-a6da-af30ab0fd9f7)

## Surfaces
 Currently:
![image](https://github.com/Riverscapes/QRiS/assets/9723905/e0894020-46c4-4031-bb9e-aa1fe5f832fe)

- [x] Change to tab label `Bases for Design`
- [x] Implement a `Surfaces` Library grid picker, which loads surfaces in surface library, exposes their date, and type (columns) allows sorting), and has a checkbox to use as basis for this design.
- [x] Implement a `Based on: Data Capture Event(s)`, which allow the selection of an "Existing", "Historic", and "Future (recovery potential", basis for the current design (i.e. a collection of DCEs representing planning).  

## Description
Currently:
![image](https://github.com/Riverscapes/QRiS/assets/9723905/2b85e20b-02f6-43ae-9e43-0aed8bf2ac8b)

- [x] Allow a description for the design DCE
- [x] Add metadata tag key value pair grid (for finding in Data Exchange)

**Comment by Jdgilby** [comment]
@nick4rivers Hey Nick, I added some edits. Do you wanna go through this and see if I'm missing anything and edit if necessary?

**Comment by joewheaton** [comment]
@KellyMWhitehead and @philipbaileynar I think we lost sight of this. @Jdgilby and @nick4rivers and I provided some updated instructions. Can we make sure the next release (0.3.6 or 0.3.7) reflect these changes. Get in touch if you have any questions.

**Comment by Jdgilby** [comment]
@KellyMWhitehead We still need these changes implemented.

**Comment by KellyMWhitehead** [comment]
@joewheaton @Jdgilby These are ready for the next release (0.3.25). Let me know if anything needs to be adjusted.

![image](https://github.com/Riverscapes/QRiS/assets/10746997/3f7d8ab1-0184-443c-b740-e2fc036418b9)
![image](https://github.com/Riverscapes/QRiS/assets/10746997/688fbd7d-18f5-4ab8-82da-1c947cc9f70c)
![image](https://github.com/Riverscapes/QRiS/assets/10746997/96f4914d-4643-4074-af0b-f061dab4656f)

Description and Metadata tab are same as DCE and As-Built.
