### ISSUE TITLE
Provide modifications to design as-built form

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#268]
@nick4rivers and @Jdgilby we need to review carefully the "Create New As-Built Survey" form (same as Properties) and all its tabs. We should get wordsmithing, labels, functionality, user-interactivity, everything just like you want. To provide spec, I suggest editing this description, adding the tasks (so we can create new issues), and once spec is agreed they get assigned to @KellyMWhitehead.

## Layers
Not implemented.

This tab is greyed out currently.  
- [x] Expose the only two layers that constitute an as-built `Structure points` and `Structure crests`, user can choose both, or just one, but they have to choose one. By default, that would be structure ponts.

## Basic Properties
Currently:
![image](https://github.com/Riverscapes/QRiS/assets/9723905/dd7d5ead-c6dd-4a56-a58b-c815300ef86c)
- [x] Add at top a `Project Phase`, and allow user to provide a text label. Add a tool tip (e.g. `"Phase 1", "Phase 2", "Pilot", "Demo", "Maintenance of Phase 1", etc.)`. 
- [x] Remove 'Design completed at'
- [x] Remove Representation . It is a concept important for normal DCEs, but by definition, all designs are "future" and all as-builts are "current", and monitoring DCEs are "current". If keep, grey out, and just populate with "Current"
- [x] Remove 'Design Status'
- [x] Add at top of form the option to specify which `Design this As-Built is based on` (not mandatory)
- [x] Change the date picking to specify 'Date of As-Built Survey' and allow resolution of Date as currently is by year, month and/or day.
- [x] Add a new optional field to `Date of Construction` and allow it to re use the Single Point in time and Date Range picker functionality.
- [x] Change `Designers` to `Observer(s)`
- [x] Change `Design Sources` to `As-Built Observations`

## Surfaces
 Currently:
![image](https://github.com/Riverscapes/QRiS/assets/9723905/e0894020-46c4-4031-bb9e-aa1fe5f832fe)

- [x] Change to tab label `Bases for As-Built`
- [x] Implement a `Surfaces` Library grid picker, which loads surfaces in surface library, exposes their date, and type (columns) allows sorting), and has a checkbox to use as basis for this design.
- [x] Implement a `Corresponding Data Capture Event`, which allow the selection of a single DCE. 
- [ ] Add option when As-Built DCE is close in date to DCE, to prompt to associate with closest DCEs  

## Description
Currently:
![image](https://github.com/Riverscapes/QRiS/assets/9723905/2b85e20b-02f6-43ae-9e43-0aed8bf2ac8b)

- [x] Allow a description for the As-Built DCE
- [x] Add metadata tag key value pair grid (for finding in Data Exchange). Maybe auto-populate with some?

**Comment by Jdgilby** [comment]
@nick4rivers Hey Nick, I added some edits. Do you wanna go through this and see if I'm missing anything and edit if necessary?

**Comment by joewheaton** [comment]
@KellyMWhitehead and @philipbaileynar (similar to #267, I think we lost sight of this. Can we get this incorporated into the next release please?

Also referenced in #261

**Comment by Jdgilby** [comment]
@KellyMWhitehead We still need these changes implemented.

**Comment by KellyMWhitehead** [comment]
@Jdgilby Could you please elaborate on these two requests for the surfaces tab:
>Implement a Corresponding Data Capture Event, which allow the selection of a single DCE.
 Add option when As-Built DCE is close in date to DCE, to prompt to associate with closest DCEs

Is this intended to apply the associates surfaces from the selected DCE to the As-Built?

**Comment by Jdgilby** [comment]
@KellyMWhitehead 

I'm not entirely sure, I didn't add those ones. It must have been @joewheaton

**Comment by KellyMWhitehead** [comment]
@joewheaton, @Jdgilby Here is what I believe are the requests in this ticket. I did not get "Add option when As-Built DCE is close in date to DCE, to prompt to associate with closest DCEs" due to some complexity. I will get this added in a future release.

Ready for 0.3.25

![image](https://github.com/Riverscapes/QRiS/assets/10746997/4fc3d9fb-f52d-4836-8667-0e4982561614)
![image](https://github.com/Riverscapes/QRiS/assets/10746997/7e685f9b-68b3-4de5-816e-b5707e1da222)
![image](https://github.com/Riverscapes/QRiS/assets/10746997/21c774b0-ab04-496e-9b56-348ac7d80992)
![image](https://github.com/Riverscapes/QRiS/assets/10746997/bf974caa-c355-4400-96d9-9093ac3c7884)
![image](https://github.com/Riverscapes/QRiS/assets/10746997/265905da-2c39-4ac6-95f1-ef84ef3c60cb)
