### ISSUE TITLE
Add Planning Construct to DCE → LTPBR drop down

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#272]
We want to add a construct/concept, of a Planning event as defined in the LTPBR Manual. Planning is nothing more than three DCEs packaged together representing: Existing, Historic and Future Conditions

The Future Conditions, is where 'recovery potential layer' should go. 

![image](https://github.com/Riverscapes/QRiS/assets/9723905/cbf0c47c-7869-4eca-a440-401e71194e6a)

From this menu, add 'Create a Planning Collection'

**Comment by joewheaton** [comment]
@philipbaileynar you and I need to discuss how we want to do this. I'm thinking it is a simple as a new "planning" table, that allows collections of `eventID` for at least two, but typically three (a current, historic and future) DCEs.  We need to discuss how this is exposed in the tree, and used for planning analyses or reports.

**Comment by philipbaileynar** [comment]
The brilliance of QRiS is that the digitizing for the LTPBR lifecycle can be quite a messy process. I'm not talking about the geometries, I mean which layers are relevant for the various types of events that can occur (planning, design, as-built, monitoring). It's all very flexible and needs to support users/sites needing different workflows.

The brilliance of QRiS is that it has a fairly simple data structure (even simpler now with the 3 feature classes) together with a generic concept of a DCE that can be extended for specific purposes (planning, design, as-built, monitoring etc).

I think your suggestion is fine so long as it fits into this data model. As you suggest, a plan can include three DCEs (past, present, future), created from the right click menu above. How we represent these in the tree can be discussed.

We have the option of adding two new database tables called `plans` and `plan_dce` that relate the three DCE together. Or we could just burry the relationship in the DCE hidden metadata JSON.

**Comment by joewheaton** [comment]
Okay, lets take 15 minutes, decide which way to go, and proceed. I will rope in @Jdgilby and @nick4rivers to think about the few missing layers. As you say, everything fits nicely in the constructs of DCEs and the three feature class deal. This also is crucial to addressing @AldenShallcross suggestions/questions of how do people articulate intent with their projects and measure progress (i.e. effectiveness) towards reaching those goals. These planning DCEs are crucial to that roundtrip taking place in the context of Analsyes.

**Comment by joewheaton** [comment]
This is done.
