### ISSUE TITLE
Error Creating DCE with Beta 2

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#274]
# Steps to reproduce

1. Installed `0.3.0 beta 2`
2. Created new project (suceeded)
3. Right click on DCE and choose create new DCE
4. Provide a name
5. Add dam/jam survey method layers to DCE
6. Click OK

# Observed 

<img width="1709" alt="CleanShot 2023-10-17 at 09 09 59@2x" src="https://github.com/Riverscapes/QRiS/assets/8645379/0f2e18b3-4947-4c0b-bd27-35a850a93186">

**Comment by KellyMWhitehead** [comment]
DCE layers were temporarily removed while we focus on design. We will bring them back as part of the three feature class strategy.
