### ISSUE TITLE
Project tags

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#275]
On the project properties page add a textbox for "tags". 

Tooltip should explain to the user that this field can be used for a comma separated list of tags.

Make sure to strip leading and trailing whitespace for both the whole string and either side of the comma characters.

Tags aren't that useful in QRiS itself, but we will be able to use these tags when we upload the project into the Data Exchange.

**Comment by joewheaton** [comment]
I like this @philipbaileynar. Could the tags someday actually auto populate as you type from tags on the data exchange, or is that a non-starter? Fine if answer is no ;)

**Comment by philipbaileynar** [comment]
Querying the Data Exchange to find out what tags exist would require credentials and being signed in. 

I'm not saying "no" and eventually QRiS might have so many Exchange interactions that it becomes routine to sign in to Riverscapes once and QRiS remembers the token.

**Comment by KellyMWhitehead** [comment]
Added for 0.3.3

These are stored in the metadata under 'tags' key.

The properties form is smart enough to harvest the tags so they do not show up under the metadata tab.
