### ISSUE TITLE
Add as metadata even when mapping values

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#276]
We have the excellent "Map Values" form that is used during the import of external feature class.

Add a checkbox to this form, just above the values table. The checkbox label should be "Retain original values as Metadata" and the default state of the checkbox should be checked.

During the import the code should then retain the original string value from the feature class being imported and store it as metadata on the QRiS feature.

**Comment by KellyMWhitehead** [comment]
This is added for 0.3.2.

1) I currently do not have any field checking logic set up. There is the possibility of a value getting overwritten (e.g. input field named Structure Type trying to map output to expected Structure Type field in the layer).
2) Do we want user to specify the output field name? Or add a prefix?

**Comment by philipbaileynar** [comment]
Does your second question suggest that we are storing official attributes alongside discretionary user metadata inside the same JSON structure?

# I Suspect We are Doing this

This is the entire JSON structure inside the metadata field for a single feature in any DCE layer. The first key `structure_type_id` is an official protocol defined attribute. But `structure_type` and `description` are keys that were created during the import of any existing feature class. The concern you raise above is that if the user imports a feature class with a field called `structure_type_id` then it could collide with the official field.

```json
{ 
    "structure_type_id": 4,
    "structure_type": "My old BDA type",
    "description": "blah blah blah"
}
```

# Better Way

Separate the data that the software relies on to work, from the discretionary data that users have imported.

```json
{
    "attributes": {
        "structure_type_id": 4
    },
    "metadata": {
        "structure_type": "My old BDA type",
        "description": "blah blah blah"
    }
}
```

**Comment by KellyMWhitehead** [comment]
Restructured the metadata to reflect this pattern. Projects with the old structure will need to be updated.

The last bit of checking will be to add some logic that ensures each target field is only mapped to once.
