### ISSUE TITLE
Feedback on LTPBR V2 Symbology

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#279]
@Jdgilby and @nick4rivers. Please see my feedback [in this video](https://youtu.be/w6_ht24SEhg)
https://youtu.be/w6_ht24SEhg

There are two main suggestions in my feedback. 
## Organization of "Layers" (i.e. what becomes Business Logic)
The first is reorganizing LTPBR v2 DCEs a little more thematically:
![image](https://github.com/Riverscapes/QRiS/assets/9723905/a893fb67-1d9d-4ffd-9ef7-8664ef3549dd)
At a high level, this is breaking DCEs into **Observations** and **Assessments**.  I dump the BRAT stuff under *Beaver Dam Building* in **Assessments** and the Cluer & Thorne CEM stuff under *Geomorphic Condition*.  These are not arbitrary. I'm thinking about this in terms of a) organization of the protocol document, b) pedagogically how we teach and structure this, and c) from how this is organized by groups in the layer tree for turning on and off thematically.  I then divide the real meat, under **Observations** into:
- Structural Elements
- Geomorphic Mapping
- Hydraulic Mapping
- Vegetation Mapping
- Other (our equivalent of observation points)

You'll see everything we're doing slots in nicely for now in those places. It also aligns with the Fluvial Taxonomy well enough and what we've done with GUT and RIM and BRAT. 

## Symbology feedback
Secondarily, I provide some specific feedback and edits on the symbology. For the most part, I'm trying to point you to places where we already have something (e.g. other models, or my [class tutorials](https://capstone.restoration.usu.edu/Course_Topics/WATS_5350/Low-Tech/Projects/birch/birchplanning.html). 

## What I used
@Jdgilby [here](https://drive.google.com/file/d/1zHFbFiRCEKYxYx8FSPtbXOEwrKuMEY5e/view?usp=sharing) is `[Specs.gpkg](https://drive.google.com/file/d/1zHFbFiRCEKYxYx8FSPtbXOEwrKuMEY5e/view?usp=sharing)` updated as I show in the video. The Riverscapes Projects links will be broken, but the content that was in the geopackage will work.

For reference those projects are here: https://data.riverscapes.net/c/227e5bfd-1367-4bac-9c61-7629e6eea70f/projects

## Next Steps
- [x] @Jdgibly and @nick4rivers review suggestions and decide if you agree
- [x] @Jdgilby to curate all the individual layers for DCEs (not there are no new additions)
- [x] Provide the "tree" to @KellyMWhitehead as either business logic or just in a *.qgz and he can translate to QRiS tree and/or business logic.
- [ ] We fully populate a few of these for Willow Springs DCE and Bailey Flat DCEs
- [ ] We import some older DCEs into this new system

Thoughts?

**Comment by Jdgilby** [comment]
@joewheaton @nick4rivers Joe thanks for the feedback, [here'](https://youtu.be/5syqs7XIZbI)s a response and request for further feedback on forms and a few attributes. But other than that I think we are basically at the point of really pushing this along.

**Comment by nick4rivers** [comment]
@joewheaton and @Jdgilby there's a lot for me to unpack here. @Jdgilby, once you incorporate Joe's approach to organization could you send me the updated geopackage and project for feedback

**Comment by philipbaileynar** [comment]
I talked to Joe. Let's keep the changes small, incremental and heading in the right direction.

@KellyMWhitehead please implement just the following for now:

Add a `hierarchy` value to the layer definition JSON for each layer. This will be used to generate the hierarchy for the map ToC, project tree, and DCE layer picture control.

For example, the "structure points" layer will have a `hierarchy` value of `Observations/Structural Elements`. Wherever this layer is displayed (project tree, ToC, layer picture) it will then appear as:

```
Observations
    Structural Elements
        Structure Points
```

This is a powerful, flexible way that the people defining the layers can choose to have a layer appear in any hierarchical structure. It could be zero or many levels deep!

**Comment by KellyMWhitehead** [comment]
Hierarchy capability has been added for version 0.3.5, however I have not made any changes to the project schema until we have the structure in place.

**Comment by Jdgilby** [comment]
@KellyMWhitehead Ill have .gpkg sent today with what we want to include.

**Comment by joewheaton** [comment]
This is superseded by newer issues and updates.
