### ISSUE TITLE
Export Polygon Surface

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#28]
Python error when exporting polygons.

![Screen Shot 2021-06-29 at 1 37 34 PM](https://user-images.githubusercontent.com/34071692/123864625-d3580600-d8df-11eb-9a9a-92ee8c229c60.png)
![Screen Shot 2021-06-29 at 1 41 13 PM](https://user-images.githubusercontent.com/34071692/123864635-d5ba6000-d8df-11eb-9f68-1dc22c75e45f.png)

**Comment by joewheaton** [comment]
@nick4rivers is this fixed? If so, where are commits fixing it? If closing for another reason, explain.

**Comment by nick4rivers** [comment]
@joewheaton - this was a windows - mac path issue, I think Kelly got it dialed.
