### ISSUE TITLE
Riverscapes logo on plugin

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#280]
The old riverscapes logo still appears in the plugin explorer:

<img width="942" alt="Screenshot 2023-12-12 at 12 11 53 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/f57f1c8d-8e72-4b5b-abdd-caf73f88d60e">

Note that I went digging in the [online plugin repository](https://plugins.qgis.org/plugins/experimental/?sort=-latest_version_date) and the same logo appears there.

<img width="908" alt="Screenshot 2023-12-12 at 12 13 53 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/11c5d4c7-3962-4f2d-a694-51d71be5c2e1">

**Comment by KellyMWhitehead** [comment]
Change has been made. Will need to wait until new version is uploaded to see if it sticks.

**Comment by joewheaton** [comment]
@KellyMWhitehead this is still NOT working. We should try to fix this for change to 1.0

**Comment by KellyMWhitehead** [comment]
Fixed for 1.0.1.

FYI make sure file is always named `icon.png` for this to show up properly in the plugin manager, even if it is named and specified correctly in `metadat.txt`.
