### ISSUE TITLE
Attribute Table not Retaining Fields 

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#281]
I tried to import multiple fields from an existing attribute table into QRiS (version 0.3.4) as-built survey but one field was excluded from the metadata while the other was kept. From screenshot 1, I tried to retain both structure type & imagery date as metadata, but only the imagery date field was kept as shown in screenshot 3. Screenshot 2 shows the the original classification of structure types and their new, transformed classifications for QRiS. As shown in screenshot 3, the new classifications were kept but the original classifications were not.  

Screenshot #1:
 ![Screenshot 2023-12-12 QRiS Error 1](https://github.com/Riverscapes/QRiS/assets/150490067/69f79f69-0b35-49f2-882c-ffe10b440773)

Screenshot #2: ![Screenshot 2023-12-12 QRiS Error 2](https://github.com/Riverscapes/QRiS/assets/150490067/ceaf0bf9-54c9-4a8b-b3cc-9f3e8f1381f7)

Screenshot #3: ![Screenshot 2023-12-12 QRiS Error 3](https://github.com/Riverscapes/QRiS/assets/150490067/317aa6ad-74f9-4647-ae88-b1e343c17c78)

**Comment by KellyMWhitehead** [comment]
@zburgert1997 could you please zip and upload the data you are trying to import? I suspect the data might be saved properly, but there might be a field display issue since "Structure Type" exists both in QRiS and import file.

**Comment by zburgert1997** [comment]
Sure, here is the QRiS geopackage with the data.

Zach

**Comment by KellyMWhitehead** [comment]
@zburgert1997 

Looks like the file did not attach properly. Try dropping the file right in the comment box on GitHub.

**Comment by zburgert1997** [comment]
[2021_46_AS_Bailey_Flat_Riverscape_Restoration_OR.zip](https://github.com/Riverscapes/QRiS/files/13678390/2021_46_AS_Bailey_Flat_Riverscape_Restoration_OR.zip)

**Comment by zburgert1997** [comment]
Just uploaded it to GitHub.

**Comment by KellyMWhitehead** [comment]
This should be fixed for version 0.3.6. The attributes were getting saved properly, but the duplicated field names were causing an issue when creating the layer.
