### ISSUE TITLE
Remove Delete Project Option

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#282]
I think it's an error, but regardless we don't want the "Delete Project" option when you right click on a project in QRiS:

<img width="359" alt="Screenshot 2023-12-13 at 7 18 21 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/6b9ca2a8-afe3-4900-81c6-05de9c467770">

**Comment by KellyMWhitehead** [comment]
Delete project option removed for 0.3.5
