### ISSUE TITLE
QRiS not Displaying Structure Types/Classifications for Digitized Features in Attribute Table (possible bug)

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#283]
When I manually digitize structure points or lines, the attribute table is not displaying structure type values (Screenshot #1). I have to exit out of the project and reload it using the plugin for the attribute table to display the classifications I set them to be (Screenshot #2). I tested the previous version (0.3.3 I believe) of QRiS and this was not an issue as the attribute table displayed the structure types I set them to be after classifying them in the widget. 

Screenshot #1:
![Screenshot 2023-12-12 QRiS Error 4](https://github.com/Riverscapes/QRiS/assets/150490067/3310a863-8886-4b49-bd63-c988328ae5b7)

Screenshot #2:
![Screenshot 2023-12-12 QRiS Error 4 1](https://github.com/Riverscapes/QRiS/assets/150490067/8b8d7482-92cf-4f50-a13d-f7ab71bfcc52)

**Comment by joewheaton** [comment]
@KellyMWhitehead and @philipbaileynar this is a pretty major bug (but a simple fix). Absolutely needs to be included in 0.3.6 release. QRiS Designs are useless without.

**Comment by KellyMWhitehead** [comment]
Fixed - virtual field is updating correctly now when digitizing features. Ready for 0.3.6

**Comment by joewheaton** [comment]
I think this is addressed from my testing in #300
