### ISSUE TITLE
Help Dialog Content

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#287]
Loving the new look and feel of QRiS in 0.3.5. Minor problem:
![image](https://github.com/Riverscapes/QRiS/assets/9723905/90a9d45c-54ba-4bf6-9fb2-a9c09e4e92ea)
Now that we switched https://qris.riverscapes.net to Gatsby, pointing the Help to https://qris.riverscapes.net/about/acknowledgements/ is no longer a md and so does not display. 
- [ ] Fix to load content of Acknowledgements

Also, Can we please add two links in top part above `Discussions` 
- [ ] Add "QRiS Knowledge Base          https://riverscapes.freshdesk.com/support/solutions/folders/153000068961
- [ ] Get Support                                   https://riverscapes.freshdesk.com/support/tickets/new
 
And
- [ ] Change `Discussions` label to `Development Discussions`

**Comment by KellyMWhitehead** [comment]
@philipbaileynar I updated the link to the new acknowledgement page, but the page isn't rendering very well. Is there a different page I should be using for this?

**Comment by philipbaileynar** [comment]
We are going to need @MattReimer help for this. I recall he was doing some gymnastics to get these screens to render. If it proves difficult I am going to recommend that we strip down the about forms and link to the information online.

**Comment by MattReimer** [comment]
I believe we can accomplish this without too much issue.

**Comment by KellyMWhitehead** [comment]
@MattReimer This is affecting RS Viewer too.

**Comment by MattReimer** [comment]
I've upgraded the gatsby theme. You can now add

like so:

```
https://qris.riverscapes.net/about/acknowledgements/?render=noFrame
```

https://qris.riverscapes.net/about/acknowledgements/?render=noFrame


And it will not render the sidebar, topbar or footer. 

if you want the large banner to go away remove `banner: true` from the frontmatter

**Comment by KellyMWhitehead** [comment]
@MattReimer Still seems to be trying to load the frames. I can give a quick demo and show you what's going on...

**Comment by MattReimer** [comment]
Yup. seems like Qt control doesn't render any of our CSS, load any of our fonts or run any of our javascript. 

That really restricts the tools I have to work with here. I'll see if I can find a better control for it .

**Comment by KellyMWhitehead** [comment]
This is now just a link to load the site in an external browser.

**Comment by joewheaton** [comment]
Why don't we just revert to referring the markdown files? If I understand, the markdown renders (we don't need fonts, just basic markdown and basic images). Also, the new Gatsby sites DO NOT render the *.md and only *.mdx.  It is crucial to me that the sponsors of these software are acknowledged within the software, and not just on the website. It worked before, we can make it work again.

**Comment by MattReimer** [comment]
We can't refer to the markdown files anymore because they stopped existing when we migrated to gatsby.

There's probably a quick and dirty way to do this and a more thorough way to do it right.

I see your point so like you said, I'm sure we can figure this out

**Comment by philipbaileynar** [comment]
Is there a rich text QT control? Let's just put the text with hyperlinks directly in the software. 

We are pumping out frequent releases. Virtually no benefit to independently published web page of acknowledgements that we embed inside a QT form.

**Comment by MattReimer** [comment]
We were actually using the text control. We just need to hardcode some html with the software... for now

**Comment by KellyMWhitehead** [comment]
![Image](https://github.com/Riverscapes/QRiS/assets/10746997/fc7d5035-18f2-4537-887b-4508cbcea3d4)

**Comment by joewheaton** [comment]
This is fixed.
