### ISSUE TITLE
Implement layers and forms for regular DCE

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#293]
This is for tracking purposes. @KellyMWhitehead already has this [Specs.zip](https://github.com/Riverscapes/QRiS/files/13729106/Specs.zip) that has editing forms specified, layer legend hierarchy laid out, and layers to implement in a regular DCE.

**Comment by KellyMWhitehead** [comment]
Ready for 0.3.6. Please comment to this ticket if I missed anything.

**Comment by joewheaton** [comment]
So I am noticing in #302 something I am a little concerned about @KellyMWhitehead and @Jdgilby and I would like @KellyMWhitehead and @philipbaileynar advice on.  @Jdgilby curated a bunch of symbology, but it was all based on a version of these DCE layers in which the layers are symbolized off an integer value, and the QMLs specified a Legend value. 
<img width="913" alt="image" src="https://github.com/Riverscapes/QRiS/assets/9723905/7c024ff6-5938-4621-8670-5e1ac108fb82">
In the `Structure Points` example above, _structure_type_id_ is the old field @Jdgilby symbolized off of, and the new field @KellyMWhitehead is now using in the [schema definition](https://github.com/Riverscapes/QRiS/blob/16905bac043af5eeabe5c8d201c618d5fa00a91d/src/db/schema.sql#L73C2-L73C2) is actually now `Structure Type` and it is of type _text_ and the Value and Legend would be the same. 
![image](https://github.com/Riverscapes/QRiS/assets/9723905/1a321f87-d38f-4aa8-8949-ff96415bbace)

At one level, this is fine, however, some of the symbology logic that @Jdgilby uses is based on condition logic, which works with > < ranges tied to those integer fields, but not the rest. Can we discuss either a work around with this new system or strategy?

**Comment by Jdgilby** [comment]
@Joewheaton I dont think this should be a big deal. I knew the symbology rules would change when we switched to the 3FCE and attributes based on metadata. Thats why I was hesitant to finalize any sort of .qml until a release of QRIS was made with all the layers and attributes finalized. Now I can just copy the symbology and change the rules in which its symbolizing based on.
I think.
