### ISSUE TITLE
Add notes to every layer in Designs, As-Built, and regular DCEs

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#294]
Another tracking issue. I already talked to @KellyMWhitehead about this. We want to add a notes attribute to every layer in all 3 DCE types.

**Comment by KellyMWhitehead** [comment]
Added this to 0.3.6. All dce/design/as-built layers should have this field now.

**Comment by joewheaton** [comment]
Thank you @KellyMWhitehead, this is working nicely. Is it possible to make the text box bigger? In other words multiline instead of single line? 
![image](https://github.com/Riverscapes/QRiS/assets/9723905/dc80e4f4-af36-48a1-81b2-9cc34354f1bd)

**Comment by KellyMWhitehead** [comment]
I've changed the widget from QLineEdit to QTextEdit. This will now be multiline.

Version 0.3.26
