### ISSUE TITLE
Changes to As-Built layers 

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#295]
A few tasks to clean up As-Builts

- [x] Get rid of ZOI layer
- [x] Get rid of Complex Extents layer
- [x] Get rid of Observations Lines and Observations Polygons
- [x] We need a new layer for Observations Points (not just bringing over the same layer from Design). This Observation Points layer only needs a notes attribute and photo import capability.

**Comment by KellyMWhitehead** [comment]
Ready for 0.3.6
