### ISSUE TITLE
Trim down Structure Type lists for Design and As-Builts for LTPBR V2

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#297]
Provide new Structure Type list for Structure Points and Structure Lines. The original list in the base protocol has something like 42 types. @nick4rivers wants to slim this down. This should be for both Design and As-Built layers.

**Comment by nick4rivers** [comment]
I would remove BDA Large and BDA Small. Also see attached image. Why are rock dams and other things under root mat production?

![Screen Shot 2024-01-09 at 10 11 27 AM](https://github.com/Riverscapes/QRiS/assets/34071692/cfb70fa2-5fdc-482d-8647-c1d25f3dc596)

**Comment by nick4rivers** [comment]
Hey, my only real comment on this one is removal of BDA Large and BDA Small

**Comment by Jdgilby** [comment]
@KellyMWhitehead We still need to remove Small BDA and Large BDA from the list.

**Comment by KellyMWhitehead** [comment]
These are removed in version 0.9
