### ISSUE TITLE
Regular DCE in wrong place in legend hierarchy

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#299]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/69ca2c73-50c9-4c9f-8fe9-6feb6c1f27e4)
@joewheaton Correct me if I'm wrong but don't we want these separated? Right now both an as-built DCE (2)and a regular DCE (3) are both lumped under the as-built group in the legend. Shouldn't a regular DCE have its own grouping?

**Comment by KellyMWhitehead** [comment]
@Jdgilby 
I have tested this, and it seems to be working for me. Is this an older project or version of qris?

If this is still an issue, I might need to look a the specific qris project.

**Comment by KellyMWhitehead** [comment]
Figured it out and fixed the logic. Ready for 0.3.7
