### ISSUE TITLE
Build LTPBR Design projectrs.xml and Project

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#30]
Work with @MattReimer to write script in QRiS that

- [ ] Generates empty `ltpbrDesign.gpk` and project folder
- [ ] Generates the `project-rs.xml`

Then provide to Chalese for https://github.com/Riverscapes/RiverscapesXML/issues/181

**Comment by nick4rivers** [comment]
This seems really old and worth removing
