### ISSUE TITLE
Update Latest Release from 0.1.1 to actual published experimental QGIS releases 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#301]
Now that we have [QRiS properly in QGIS Plugin Library](https://plugins.qgis.org/plugins/qris_deploy/#plugin-about), please update on GitHub the Latest to the actual latest (i.e. stop making these as Pre-Releases):

Currently the latest (0.3.6) is a pre-release and the [latest ](https://github.com/Riverscapes/QRiS/releases/latest) is listed as 0.1.1. 
![image](https://github.com/Riverscapes/QRiS/assets/9723905/27e8fe89-6adb-40de-afc1-2dc90bc7522e)

We want https://github.com/Riverscapes/QRiS/releases/latest to point to latest in Plugin Library.

@philipbaileynar do you agree?

**Comment by philipbaileynar** [comment]
Yes. Whenever a release is submitted to the plugin store, it should be a public GH release and appear as the "latest" (regardless of whether the plugin is listed as experimental)

**Comment by KellyMWhitehead** [comment]
updated 0.3.6 as the latest release and will do so moving forward. Closing ticket.
