### ISSUE TITLE
Upload Correct QMLs for all QRiS LTPBR V2 layers

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#302]
@Jdgilby and @nick4rivers, with [0.3.6](https://github.com/Riverscapes/QRiS/releases/tag/version_0.3.6), we are now unlocked to connect the QMLs we want for each layer. @KellyMWhitehead is now properly giving us everything we have asked for in terms of order in the tree, the attributes, etc., but we need to provide the QMLs in [RiverscapesXML/Symbology/qgis/QRiS](https://github.com/Riverscapes/RiverscapesXML/tree/master/Symbology/qgis/QRiS). 

The workflow for each layer is:
1. Identify the layer you wish to curate and it's correct QML from the [schema definition](https://github.com/Riverscapes/QRiS/blob/16905bac043af5eeabe5c8d201c618d5fa00a91d/src/db/schema.sql#L73C2-L73C2)

For example, for the example below, which is `Dam Crests`, you can scroll across and see the qml is `dam_crests.qml`
``` sql
INSERT INTO layers (id, fc_name, display_name, geom_type, is_lookup, qml, description, metadata) VALUES (1, 'dam_crests', 'Dam Crests', 'Linestring', 0, 'dam_crests.qml', NULL, '{"fields": [{"machine_code": "structure_source_id", "label": "Structure Source", "type": "list", "lookup": "structure_source"}, {"machine_code": "dam_integrity_id", "label": "Dam Integrity", "type": "list", "lookup": "dam_integrity"}, {"machine_code": "beaver_maintenance_id", "label": "Beaver Maintenance", "type": "list" ,"lookup": "beaver_maintenance"}]}');
```

2. Curate dam crests symbology as you wish (i.e. from your old geopackage QGZ) and save to the local folder of the QRiS project (QRiS looks first in the project folder (for an overide) and then in the Viewer/Resources folder, which is updated from Riverscapes XML, for the sybmology file (in the example above, if you saved your qml as `dam_crests.qml` with exact same spelling to the folder of the QRiS project you are testing it in, and re-added it to the map, it will preview how QRiS will behave.
3. Clone and/or update with a Pull to the latest version of RiverscapesXML repo locally. Create a branch to make your changes on and check it out. 
4. Once you are happy, copy that qml to your local copy of RiverscapesXML repo and overwrite the `*.qml` in the `Symbology/qgis/QRiS` folder. 
5. Commit that change locally. Push your changes on that branch.
6. Repeat until you have enough done and create a pull request.

I illustrate that in [this video](https://youtu.be/S92igc_h7hw) for you:
https://youtu.be/S92igc_h7hw

I did observation points in the video. I attempted Structure Points and got in trouble (that one is complicated), but you will see why. Do the ones you can, and the ones that are difficult turn into sub-issues, and we'll get help from @KellyMWhitehead on.

## Layers to update
- [ ] dam_crests | Dam Crests | dam_crests.qml
- [x]  active_channel | Active Channel(s) (bankfull) | active_channels.qml
- [x]  active_extents | Active Extents | active_extents.qml
- [x]  centerlines | Centerline(s) of Active Channel(s) | centerlines.qml
- [x]  inundation_extents | Inundation | inundation_extents.qml
- [x]  channel_junctions | Channel Junctions | channel_junctions.qml
- [x]  geomorphic_unit_extents | Geomorphic Units | geomorphic_unit_extents.qml
- [x]  geomorphic_units | Geomorphic Unit Points | geomorphic_units.qml
- [x]  cem_phases | CEM | cem_phases.qml
- [x]  vegetation_extents | Vegetation Extents | vegetation_extents.qml
- [x]  brat_vegetation | Brat Vegetation Suitability | brat_vegetation.qml
- [x]  zoi | Zones of Influence | zoi.qml
- [x]  complexes | Structure Complex Extents | complexes.qml
- [x]  structure_points | Structure Points | structure_points.qml
- [x]  structure_lines | Structure Lines | structure_lines.qml
- [x]  brat_cis | BRAT CIS | brat_cis.qml
- [ ]  brat_cis_reaches | BRAT CIS Reaches | brat_cis_reaches.qml
- [x] observation_points | Observations | observation_points.qml
- [x] observation_lines | Observations | observation_lines.qml
- [x] observation_polygons | Observations | observation_polygons.qml
- [x] observation_points_dce | Observations | observation_points_dce.qml
- [x] observation_lines_dce | Observations | observation_lines_dce.qml
- [x] observation_polygons_dce | Observations | observation_polygons_dce.qml
- [x] structural_elements_points | Structural Elements | structural_elements_points.qml
- [x] structural_elements_lines | Structural Elements | structural_elements_lines.qml
- [x] structural_elements_areas | Structural Elements | structural_elements_areas.qml
- [x] observation_points_asbuilt | Observations | observation_points_asbuilt.qml

**Comment by KellyMWhitehead** [comment]
I think the above list is out of date. Use the following:

|fc_name|display_name|qml|
|-------|------------|---|
|dam_crests|Dam Crests|dam_crests.qml|
|active_channel|Active Channel(s) (bankfull)|active_channels.qml|
|active_extents|Active Extents|active_extents.qml|
|centerlines|Centerline(s) of Active Channel(s)|centerlines.qml|
|inundation_extents|Inundation|inundation_extents.qml|
|channel_junctions|Channel Junctions|channel_junctions.qml|
|geomorphic_unit_extents|Geomorphic Units|geomorphic_unit_extents.qml|
|geomorphic_units|Geomorphic Unit Points|geomorphic_units.qml|
|cem_phases|CEM|cem_phases.qml|
|vegetation_extents|Vegetation Extents|vegetation_extents.qml|
|brat_vegetation|Brat Vegetation Suitability|brat_vegetation.qml|
|zoi|Zones of Influence|zoi.qml|
|complexes|Structure Complex Extents|complexes.qml|
|structure_points|Structure Points|structure_points.qml|
|structure_lines|Structure Lines|structure_lines.qml|
|brat_cis|BRAT CIS|brat_cis.qml|
|brat_cis_reaches|BRAT CIS Reaches|brat_cis_reaches.qml|
|observation_points|Observations|observation_points.qml|
|observation_lines|Observations|observation_lines.qml|
|observation_polygons|Observations|observation_polygons.qml|
|observation_points_dce|Observations|observation_points_dce.qml|
|observation_lines_dce|Observations|observation_lines_dce.qml|
|observation_polygons_dce|Observations|observation_polygons_dce.qml|
|structural_elements_points|Structural Elements|structural_elements_points.qml|
|structural_elements_lines|Structural Elements|structural_elements_lines.qml|
|structural_elements_areas|Structural Elements|structural_elements_areas.qml|
|observation_points_asbuilt|Observations|observation_points_asbuilt.qml|

**Comment by Jdgilby** [comment]
Checklist updated in Joes original comment from Kelly's list provided.
