### ISSUE TITLE
Structural elements forms need fixed

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#304]
[Heres](https://youtu.be/fTT4mBeip3w) a link to whats going on.

This is related to issue #293 where the layers/attributes/and forms for each layer were specified. 

@joewheaton just fyi after watching your video from #300

**Comment by joewheaton** [comment]
Thanks @Jdgilby. Form our conversation yesterday, @KellyMWhitehead I think was aware of this (maybe not the mix up between points and polygon), but that he had not plumbed the other part. He ran out of time for the 0.3.6 release. I'm not sure if he is working today or not, but thanks for documenting this.

**Comment by KellyMWhitehead** [comment]
I fixed the attributes for two DCE Layers:

- Structure Points: added count, length, width, depth and LW count.
- Structure Areas: Removed count, length width, and depth

I have also added some logic in the metadata to make these dependent on structure type in the future, but do not have this ready in the QRiS toolbar yet (#285). 

@Jdgilby Are any other layers missing attributes?

**Comment by Jdgilby** [comment]
@KellyMWhitehead I think just BRAT CIS Reaches

**Comment by Jdgilby** [comment]
@KellyMWhitehead The attribute forms shown in the video should still be implemented if possible

**Comment by KellyMWhitehead** [comment]
Got this working. Finally! Ready testing for 0.9.6. Please make sure I have the logic correct. 

Note: it was much easier for me to enable/disable the widgets than show or hide them. I can revisit this in the future, but I think this is good for 1.0.

**Comment by Jdgilby** [comment]
@KellyMWhitehead It is working but the rules are backwards. Jam, Dam, Root Mass, and other should default structure count to 1, and have the ability to fill in width/length/height/wood count. Jam Complex and Dam Complex should allow you to only change structure count, everything else should be blocked.

**Comment by KellyMWhitehead** [comment]
Fixed for 0.9.5
