### ISSUE TITLE
A QML updated in RiverscapesXML, is not updating... and not available to QRiS via Q-Viewer

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#305]
I may be posting this in wrong placed @philipbaileynar and @KellyMWhitehead and this may be a Viewer or RiverscapesXML issue. Move as you see fit. However, the symptom revealed itself here and comes from me attempting to demo to @Jdgilby how to update QMLs correctly in #302. I tried to do that and it is represented in this Pull Request, which I merged: https://github.com/Riverscapes/RiverscapesXML/pull/674

My understanding of what has happened in the past and is supposed to happen, is that when updates are made via commits and pull-requests to the Main (and my file IS [here](https://github.com/Riverscapes/RiverscapesXML/blob/master/Symbology/qgis/QRiS/observation_points.qml)) they automatically get updated to the Viewer Resources folder in QViewer (formerly QRAVE):    On my machine, that is: `C:\Users\joemw\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\riverscapes_viewer\resources`.

However, when I use the `Update resources` command it returns:
```
2023-12-22T10:18:29     INFO    Requesting digest from: https://xml.riverscapes.net/index.json
2023-12-22T10:18:29     INFO    SETTINGS SET: initialized=True of type '<class 'bool'>'
2023-12-22T10:18:29     SUCCESS    QRAVE Sync Syccess: 466 files checked, 0 updated
2023-12-22T10:18:30     INFO    SETTINGS SET: lastDigestSync=1703265509 of type '<class 'int'>'
```

The worrying thing is both the `SUCCESS` and `0 updated`.  And when I go to the resources folder, my `observation_points.qml` is not there. I still have installed, but unchecked QRAVE, and I checked in `C:\Users\joemw\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qrave_toolbar\resources\symbology\QRiS` and it is not there either. 

## Questions
1. Has anyone checked to confirm update resources is still working in new Q Riverscapes Viewer? 
2. Am I doing something wrong in my workflow I showed @Jdgilby (other than approving my own pull request)?
3. Is this a bug in Q Viewer?

**Comment by philipbaileynar** [comment]
Matt fixed the caching on the CloudFront copy of the resource files digest. Joe reports that this is now working. No QRiS release necessary.
