### ISSUE TITLE
Resource Folder Inconsistencies

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#306]
I can't tell if this is a QViewer or QRiS issue.

The symptom is that @joewheaton is failing to get new resources (QML files) synchronized. He gets "0 updates" when he performs "Update Resources" from which QViewer toolbar menu. However, resources are updating correctly for me on my Mac with the latest QViewer and QRiS.

Digging into Joe's plugin folder he has two resource locations: `qrave_toolbar` presumably from the old QRAVE and that wasn't cleaned up during uninstall. And now he has `riverscapes_viewer`.

# Task

Please review all synchronization related code to check that the folder used to download and verify the versions is correctly using the correct folder. I recommend stepping through the code as it checks if there are updates available. It smells like the code that does the checking and downloading might be a using a different location than the symbology loading code.

If this doesn't work then we can delete the old folder on Joe's computer, but I don't want to alter his machine until we know what's really going on or we risk being unable to recreate the problem.

<img width="1063" alt="CleanShot 2024-01-02 at 16 13 48@2x" src="https://github.com/Riverscapes/QRiS/assets/8645379/ccd5161a-22fc-4e70-aeb1-13a0ecd1ea19">

**Comment by joewheaton** [comment]
@philipbaileynar. I think we are "unblocked" and fixed for syncing resources, but it seems like there is still some housekeeping to clean up associated with what we saw above?

**Comment by philipbaileynar** [comment]
The legacy folders are just orphans after uninstalling QRAVE. Nothing any software can do about this. 

Please manually delete the unused folders. New users should never experience this.
