### ISSUE TITLE
QRiS won't allow me to import from exisiting feature class

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#307]
I tried to import dam points & inundation extents from an exisitng feature classes but QRiS keeps giving me this error when I try to define the map values for output. This didn't happen in older versions. 

![Screenshot 2023-12-12 QRiS Error 5](https://github.com/Riverscapes/QRiS/assets/150490067/20073e82-6bc1-4aa4-9381-54a38a65f00d)

**Comment by Jdgilby** [comment]
@KellyMWhitehead I just went through this with Zach. The issue was because he was opening an older QRiS project in 0.3.6.

**Comment by Jdgilby** [comment]
Closing for now unless 0.3.6 is supposed to support functionality beyond just  viewing old projects.

**Comment by joewheaton** [comment]
I know @philipbaileynar has said on multiple occasions we have to be able to support opening old projects. I am fine with letting that slide and just holding that standard from 0.3.6 forward.
