### ISSUE TITLE
Make it easier for user to understand what are empty placeholders, versus what has data.

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#309]
The project tree in QRiS and when added to the map for individual DCEs is overwhelming.  

We can manage user's understanding better with the following modifications to QRiS tree:
- [x] Change default behavior of what gets added to Layer Manager, after event of creating or editing a DCE to add nothing. Only add to map and layer tree when manually right clicked from QRiS tree.
- [x] When creating a new DCE, change default QRiS Tree expand node state to largely collapsed.
- [x] When adding to the map, change layer state to not be expanded to show legend.
- [x] Different display of "layer" for empty (e.g. non bold or different lighter color) 
- [x] Append node label "(empty)" or "(n features)" to right of every layer label in tree
- [x] Different display for layer in QRiS tree for layer currently being edited
- [x] Adding a 'Add all layers with features to Map' to the Parent folder/DCE nodes command
- [x] Change the 'Add to Map' command for parent folder/DCE nodes to `Add all layers to Map`

**Comment by joewheaton** [comment]
Revised slightly based on conversation with @Jdgilby

**Comment by KellyMWhitehead** [comment]
What I have so far:

> Change default behavior of what gets added to Layer Manager, after event of creating or editing a DCE to add nothing. Only add to map and layer tree when manually right clicked from QRiS tree.

The create DCE/Design form has an add to map checkbox. I changed this to unchecked on default. I also made this visible when editing DCEs (again, unchecked by default). I can remove the check box entirely if wanted.

![Image](https://github.com/Riverscapes/QRiS/assets/10746997/8c3691ca-aaa1-44c6-a475-5eb9df61ecd0)

>  When creating a new DCE, change default QRiS Tree expand node state to largely collapsed.

I adjusted the DCEs to be collapsed when creating a DCE or opening a project. Please let me know if you would like to have the collapse levels adjusted.
 
> When adding to the map, change layer state to not be expanded to show legend.

Done

>Different display of "layer" for empty (e.g. non bold or different lighter color)

Need to do.
 
>Append node label "(empty)" or "(n features)" to right of every layer label in tree

Assuming this is for the map ToC? I now turn on the Show Feature Count setting for each layer added to the map. This is managed by QGIS and should adjust as features are added/deleted.

>Different display for layer in QRiS tree for layer currently being edited

Editing will now bold the text in the project tree and add "(editing)" to the name, and reverts when editing is stopped.  

![Image](https://github.com/Riverscapes/QRiS/assets/10746997/fd167ca9-0a0c-41fa-b876-62392cdf72bc)
 
> Adding a 'Add all layers with features to Map' to the Parent folder/DCE nodes command

Done

> Change the 'Add to Map' command for parent folder/DCE nodes to Add all layers to Map

Done

**Comment by KellyMWhitehead** [comment]
I have implemented the items on this list. Please review in the next release and comment here if changes are needed, or close if this looks good.
