### ISSUE TITLE
Unknown issue when opening project

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#312]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/7a85b91f-ec94-4d6d-8ee8-dde858c5935d)

This has happened two times.

Once when zipping up a project. After unzipping and trying to open this was the error.
The other was simply after making a new DCE in which layers were imported using the import from existing feature class tool. After saving and closing this error was given when trying to reopen. 

I think it happened after trying to edit the DCE properties and add an additional layer (which also failed, will post additional issue ASAP)

@joewheaton This is what was happening when trying to get together Willow Springs for Alden. Finding out getting existing data in is still quite buggy.

Edit: Me and @KellyMWhitehead looked into this and found its due to empty metadata field stored in either dce points, dce polygons, dce lines. Happens sometimes when importing data.

**Comment by KellyMWhitehead** [comment]
Error cleaned up for version 0.3.7.
