### ISSUE TITLE
Remove layers from layer tree when closing Qris project

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#314]
@joewheaton @KellyMWhitehead This issue might already exist somewhere but I couldn't find anything. I think that this should behave like projects opened through the viewer does. When closing through the plugin it should remove all layers from the layer tree.

**Comment by KellyMWhitehead** [comment]
Added an option under settings:
![image](https://github.com/Riverscapes/QRiS/assets/10746997/83e2d41b-fdd3-48cc-a6bc-728763f6668f)

Version 0.3.21

**Comment by joewheaton** [comment]
Implemented.
