### ISSUE TITLE
Downloading from Drive splits files up

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#315]
@joewheaton @KellyMWhitehead This probably doesn't belong here, however, the issue maybe not a big deal since our goal is to host on the exchange not on drive. But when downloading a project from the containing folder, drive split it up into 3 separate downloads instead of zipping in the proper QRIS folder setup. So in this case two surfaces were missing from the project and you had to go back to downloads and add them back in. 

Alden was having problems with this.

**Comment by joewheaton** [comment]
@Jdgilby I noticed this too. At a minimum we should have freshdesk Knowledge Base Article on best practices and guidance in Anabranch @nick4rivers.  It seems that if you want to share with someone, you are better to zip up the entire project (not just geopackage) and share link to zip file. 

A thought is we might add a Share command or combine with the Export to create a zip file. A zip file is ultimately what we need for Data Exchange. I still think we will be sharing and using a lot of QRiS projects that we do not necessarily put on Data Exchange. I see what we put up there somewhat sparingly, like how often we create a public share link for Google Drive. As @nick4rivers mentioned yesterday, we may have other platforms and ways for sharing with in the company. Good find.
