### ISSUE TITLE
Sampling Frame Improvements

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#317]
# Goals

## map labels

    - text label field (not JSON)

## Topology

    - "flows into FID" integer field (or JSON field)
         - simple and transparent
         - but requires manual editing (but we could develop a script)

    - node based approach used by NHD and sample frame polygons have a "fromNode" and "toNode" field
         - more complex
         - hard to do manually

    -  Each sample frame polygon simply has a floating point valley distance value

## Categories

    - store within feature JSON field
        - Question about whether we can control with a value list
        - Question how does the user define the categories and lookup lists. Need UI for this?
        - Question about how to "import existing feature class" particularly from VBET
        - Do we allow NULL values for category values?
        - Only text values?

# Multi-level path

    - Store as explicit text field (NAME?) with values such as "Reach 1", "Reach 2" etc...
        - Can populate with NHD level path values when importing from VBET
        - User can populate with familiar stream names "Big Creek", "Little Creek" etc...
        - Can default all features to some value like "Unknown" so that most projects are single level path without the user needing to do anything

# ACTIONS

1. mock up UI for defining new sample frame
    - categories and lookup lists in "create new sample frame". Could be tree on a tab. Or combo and list.
    - level path default (textbox with "Unknown" or "Level Path 1" as the default)
    - topology values?
        - leave blank or
        - require centerline and infer (see tool below)
1. How can we use the centerline tool but on a sampling frame (i.e. multiple features down the valley, as opposed to a single sausage like we get from the bankfull slider.) i.e. the tool unions all the sampling frame polygons together before running the centerline.
1. Mock up UI for importing existing feature class
    - categories (existing map values capabilities)
    - level path (existing text field)
    - topology (provide centerline?)
   
1. Think about right click tool on sample frame for "infer topology" (by using distance down centerline)

**Comment by joewheaton** [comment]
@philipbaileynar I think this is no longer relevant.
