### ISSUE TITLE
Digitizing Error in QRiS from Sam (Adding New Fields in Attribute Table?)

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#318]
All,
Sam contacted me this morning with an error she got while digitizing in QRiS. It seems that she created a new field in the attribute table (layer: Structure Lines) for calculations, but after creating the field, QRiS wouldn't allow her to digitize new features without this error popping up. She tried deleting the field but the same error kept popping up. Is the issue because she created a new field in the attribute table, and is there a way around it so she doesnt have to redigitize features?

<img width="1045" alt="Screen Shot 2024-01-12 at 12 15 34 PM" src="https://github.com/Riverscapes/QRiS/assets/150490067/c3567325-1bf9-4572-a0ca-e2ee662009f7">

**Comment by Jdgilby** [comment]
All she needed to do was close the project and reopen it. I might stand corrected on this but I don't think we have the ability to add and save new attributes in a QRIS layer. That why we tried to define all attributes in every layer.

@joewheaton @KellyMWhitehead This brings up another issue though, Structure Lines does not have a length field.... so its use case for estimating material quantities is currently not working. Simple fix I believe is to just add a length field to Structure Lines in both designs and As Builts.

**Comment by joewheaton** [comment]
@Jdgilby can we close this issue now? Please make a new issue for length field @Jdgilby if you have not already.

**Comment by KellyMWhitehead** [comment]
Closing issue. Issue transferred to ticket #330.
