### ISSUE TITLE
New error when trying to edit properties of a DCE and add a new layer

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#321]
Tried to edit an existing DCE that had two layers. Tried to add another layer to it and got this error.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/957e7044-0db5-4a39-a5bd-6db8c42c2ec7)

It had worked on the DCE prior with the same exact layers.

**Comment by Jdgilby** [comment]
@KellyMWhitehead I still get this same error on random DCEs while others in the project might not have any issues

**Comment by Jdgilby** [comment]
@KellyMWhitehead Let me know if you want the specific project this is happening on zipped up.

**Comment by KellyMWhitehead** [comment]
> [@KellyMWhitehead](https://github.com/KellyMWhitehead) Let me know if you want the specific project this is happening on zipped up.

@Jdgilby I've seen this on occasion. This is one of those elusive bugs that's hard to pin down. Please attach the project and hopefully I can recreate.

**Comment by Jdgilby** [comment]
@KellyMWhitehead https://drive.google.com/file/d/1kJgXt0NNRcTeegIW1XfKhu2vTLUOV7BU/view?usp=drive_link

I get the same error doing a number of things on this project. Ive got it when trying to add more layers to a dce in properties, and recently going back into properties to associate a surface with the dce.

**Comment by KellyMWhitehead** [comment]
I think I finally got this one fixed! Ready for version 0.3.26
