### ISSUE TITLE
Full Value by Value Mapping on Temporary Layer Import

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#323]
I was just importing structures from a **Temporary Layer** into a QRiS design structure layer and couldn't get the attributes for 'structure type' to import. Also tried pasting the records and that also didn't work. Can we get the full value mapping on import of temporary layers in designs and probably in other layers as well.

Thanks all

**Comment by Jdgilby** [comment]
@KellyMWhitehead This would be useful. Especially for out of qris processing and getting data back in after repairing or altering. Ive found this to be important since we switched to the 3 feature class structure, and copy and pasting is no longer a good option.

**Comment by KellyMWhitehead** [comment]
Added for version 0.3.21
