### ISSUE TITLE
Feature count not properly counting 

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#324]
The feature count is properly counting, but not distinguishing between the categories found within the attribute. The count is getting lumped into the all other features bin even though it is displaying properly. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/c652280a-fa52-464f-9040-b60c8d8227ef)

**Comment by KellyMWhitehead** [comment]
I've noticed this happens occasionally.  This is a QGiS bug/issue (QRiS just turns this on in the layer).

I will do some investigating...
