### ISSUE TITLE
Suggested changes for LTPBR v2 Protocol

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#332]
@nick4rivers @joewheaton I think were basically there, just a few minor changes. These are changes that seem agreeable after conversations we've all had. But suggest differently if you disagree.

- [x] Change 'CEM' layer to 'SEM Cluer & Thorne' 
- [x] Change the attributes in SEM from a simple 0-8 to add descriptions of each stage
     - 0 Anastomosing
     - 1 Sinuous Single Thread
     - 2 Channelized
     - 3 Degradation
     - 4 Degradation and Widening
     - 5 Aggradation and Widening
     - 6 Quasi Equilibrium
     - 7 Laterally Active
     - 8 Anastomosing
- [x] Add categories in 'Vegetation Extents', not sure what these are, but something like "Woody Riparian", "Emergent Riparian, "Upland". I don't think it matters much what we decide on, but users are going to want options whether we use them or not.
- [x] Remove BDA small and BDA large from structure type list, mention in issue #297 

I think that's everything but please add anything I'm missing. 

I believe these are all changes @KellyMWhitehead has to make but if I can make any of these changes just assign me.

**Comment by joewheaton** [comment]
I like those. Go for it!

**Comment by KellyMWhitehead** [comment]
Changes added to version 0.9
