### ISSUE TITLE
Importing Surfaces Not Retaining Metadata 

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#333]
This was an issue I had in 0.3.7 and now 0.3.9 (very minor issue/bug). When I import a raster surface (in this case, drone imagery) into QRiS, the metadata I typed in initially (Screenshot #1) will not carry over when its done uploading. When I check the metadata afterwards, nothing is retained (Screenshot #2). 

Screenshot #1: 
![Screenshot 2023-12-12 QRiS Error 6](https://github.com/Riverscapes/QRiS/assets/150490067/537637dc-ad18-49ae-999a-2b2621921ba4)

Screenshot #2: 
![Screenshot 2023-12-12 QRiS Error 6 1](https://github.com/Riverscapes/QRiS/assets/150490067/2b2532fe-e696-4d93-aa3c-040b3b57370e)

**Comment by KellyMWhitehead** [comment]
Can you please attach the geopackage (i don't need the rasters) for this project? I need to see if the metadata is getting saved and not displaying properly, or if the metadata is not getting stored at all.

Thanks

**Comment by zburgert1997** [comment]
Sure, here is a link to the geopackage: (https://drive.google.com/open?id=1B-sU5A6Lmu226cY_5UrFBa8a8O3Deyvu&usp=drive_fs).

**Comment by KellyMWhitehead** [comment]
@zburgert1997 Please test with the latest version of QRiS and let me know if this is still an issue. 

I tested and was able to see the metadata (it seems to have been saving properly).

**Comment by zburgert1997** [comment]
Kelly, I checked to see if importing surfaces retained metadata and I got this error (Screenshot #1). I also got this error when I tried to add metadata when creating a new QRiS project (Screenshot #2). 


Screenshot #1: 
![Metadata Error Importing Surfaces](https://github.com/Riverscapes/QRiS/assets/150490067/170946bd-9c21-49c3-9fcd-dab23718e54f)

Screenshot #2: 
![Metadata Error New Project](https://github.com/Riverscapes/QRiS/assets/150490067/9500a86b-c446-438a-a080-6e85728eafd7)

**Comment by KellyMWhitehead** [comment]
@zburgert1997 I just released version 0.3.16 that should fix this issue. I should be approved and available by Monday morning.

Please let me know if this resolves or does not resolve the issue for  you.

**Comment by zburgert1997** [comment]
Sounds good, thanks @KellyMWhitehead.
