### ISSUE TITLE
Issue with Uploading Drone Imagery

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#334]
On certain instances, QRiS will display this error message when I try to upload drone imagery into an existing project. This issue is pretty erratic since sometimes the imagery will not upload (Screenshot #1 along with a message that I don't have permissions to the file) and sometimes the imagery will upload with no issues. I thought it was due to the size of the drone imagery but due to the finicky nature of this issue, I'm not so sure. 

Screenshot #1:
![Screenshot 2023-12-12 QRiS Error 7](https://github.com/Riverscapes/QRiS/assets/150490067/2f9a351c-2c01-4435-b0a9-b8879beb35f2)

**Comment by KellyMWhitehead** [comment]
The random nature and permissions issue make me wonder if this is related to #315. 

If this happens again, try manually coping the raster to your local machine and then import into qris from there. 

Please report if this is issue is still happening.

**Comment by joewheaton** [comment]
This I think is gone. @zburgert1997 reopen if you see this happening.
