### ISSUE TITLE
Difficulty Uploading an Exisiting QRiS Project (Willow Springs, completed in 0.3.6.)

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#335]
So far, I haven't had any issues with uploading older QRiS projects into 0.3.9. except with Willow Springs (completed in 0.3.6.). I keep getting this message when I try to upload the Willow Springs QRiS project into a qgz file. 

![Screenshot 2023-12-12 QRiS Error 8](https://github.com/Riverscapes/QRiS/assets/150490067/1bce195c-04d6-451d-853d-b2da9960653c)

**Comment by joewheaton** [comment]
Please provide link to project for @KellyMWhitehead and maybe show video.

**Comment by Jdgilby** [comment]
@joewheaton @KellyMWhitehead This is tied to issue #328. Got past surfaces this time but it looks like its held up somewhere else now. I get the same error. Kelly should already have the project from when I opened #328

**Comment by Jdgilby** [comment]
@KellyMWhitehead Im even getting this issue/error trying to reopen a project I just created in 039.

**Comment by zburgert1997** [comment]
@KellyMWhitehead Here is a short video showing the issue (link: https://youtu.be/yNWXZJD5ncg) & a link to the QRiS data where the issue is occurring for me (link: https://drive.google.com/open?id=1xxCf7w2Nx9Wkzq75yTCt607yVJVl7E1f&usp=drive_fs).

**Comment by Jdgilby** [comment]
@KellyMWhitehead Same error exists when trying to import a vector feature to the Context folder.

**Comment by KellyMWhitehead** [comment]
@Jdgilby @zburgert1997 

I lost track of this ticket, but I think it is fixed as of version 0.3.14. Please let me know if this is not the case.
