### ISSUE TITLE
Watershed catchments Not delineating watershed

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#336]
Ive had this error in this version and recent versions, the pour point gets created but nothing is delineated. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/c9e1b752-9e1f-47ee-9e76-004323cccfd4)
I also cant find the data anywhere in the .gpkg (if it were creating and failing to display)

**Comment by joewheaton** [comment]
This is important to be working again for next week.

**Comment by KellyMWhitehead** [comment]
Fixed for 0.3.10
