### ISSUE TITLE
QRiS Version 0.3.10 Tasks

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRiS#337]
Project Tree Refreshing
- [x] Project tree layer remains "empty" after digitizing
- [x] DCE layers after Import

Watershed Catchments (Pour Points)
- [x] Pour Point Symbology
- [x] Symbology Folder error with catchment polygon

Context
- [x] Surfaces (rasters) symbology error
- [x] Import from QRV 
  - [x] retain symbology
  - [x] Refresh project tree
 - [x] Import Existing Vector Layer
   - Does not show up in Project tree
   - Project locks up on opening
   - Delete context.gpkg unlocks project
  - [x] Import Temporary layer
  - [x] Error importing Ownership layer
  - [x] Retain Symbology from QRV

Sample Frame
- [x] empty layer with Import DGO, leave fields blank

Profile
- [x] Not reprojecting imported features
- [x] Fix Import form (drop down)

Cross Sections Tool
- [ ] Only works on first feature (not multiple, or multipart?)

Valley Bottom/Centerline Tool
- Removal of centerline tool from AOI has removed access to this tool
- [x] Add to Context Polygons for now
- Need to add Valley bottom to model?

DCE
- [x] Add Photo to Observation Points (Recent change to 3FC seems to have removed this)
- [x] Copy from Existing DCE produces Coordinate Reference Error

Analysis
- [x] Columns need to adjust to values (numbers getting cut off) and probably metric name

Notes:
- All testing to be done on Willow Springs Demo project, to ensure this works for workshops
- Target release for Friday (push version Thurs PM) to allow for testing and workshop prep, and potential second release if needed before workshop
- No new enhancements or features before first workshop. Bug fixes and stability improvements only!

**Comment by Jdgilby** [comment]
@KellyMWhitehead There still seems to be numerous refresh issues. Most common is layers not showing that data was actually imported/promoted (and showing empty, with no data being added to map) until closing and reopening the qris project. Ive also seen feature count not updating properly or the count being entirely off.

**Comment by KellyMWhitehead** [comment]
> @KellyMWhitehead There still seems to be numerous refresh issues. Most common is layers not showing that data was actually imported/promoted (and showing empty, with no data being added to map) until closing and reopening the qris project. Ive also seen feature count not updating properly or the count being entirely off.

I figured out the issue with the project tree not updating, should be fixed for the next release. 

The feature count issue in the layer tree is a pure QGIS tool, I only turn on the Show Feature Count option for the layer as it is added to the map. I have seen a few forum posts with others having this problem, but no real solutions exist. Our current options
1) Leave as is, specify in the documentation or knowledge base that it is an as-is QGIS feature.
2) Disable QRiS automatically turning this on option for now (users can always turn on or off on their own).
3) I can attempt to write a widget in QRiS to do this, but this is probably a lower priority right now.

**Comment by Jdgilby** [comment]
@KellyMWhitehead I would suggest going with option 2 for now, it seems to be confusing people.

**Comment by KellyMWhitehead** [comment]
These are by and large done, or new tickets have been created.
