### ISSUE TITLE
Cant open a 0.3.8 export in QRiS if surfaces weren't included in export

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#338]
Tried exporting and opening the exported project  without surfaces and got an error when opening.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/c314e8f7-f661-438c-bd19-8cedbc6dbf92)
I reexported but included surfaces this time and everything opened great,

**Comment by Jdgilby** [comment]
@KellyMWhitehead and as a sidenote the name given at export is not how it appears after saving. It just defaults to qris.gpkg

**Comment by joewheaton** [comment]
@Jdgilby I think this is no longer relevant. Reopen if still happening.
