### ISSUE TITLE
editing layer in DCE not updating feature counts in specific types

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/QRiS#343]
@ MT workshop. A participant created a data capture event with only inundation as layer type. When she brings it into the map, it's not symbolized correctly. Then, when editing, the overall feature count shows up, but no features actually show up mapped and the feature count of the specific types (Ponded, Overflow, Freeflowing) don't show up.

**Comment by joewheaton** [comment]
I think this is fixed. Reopen if I am wrong.
