### ISSUE TITLE
Duplicate Metadata Warning

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#348]
Identified by @joewheaton 

# Steps to Reproduce

1. Create a new QRiS project.
2. Open QViewer and load a VBET project.
3. Right click on the DEM in QViewer project tree (or any other layer that originates further upstream than VBET. e.g. slope)
4. Import to QRiS
5. When the QRiS properties form appears simply click OK

# Observed

Error message "Duplicate Metadata Key" modal dialog.

# Expected

I think this is occurring because the DEM and other "upstream layers" are coming into QRiS with multiple sets of metadata. The VBET riverscapes project includes all upstream project metadata (RSC, CA, tauDEM). But the QRiS metadata editor correctly disallows multiple entries with the same key.

The easiest solution is - during the moment we import RS project metadata - apply uniqueness to the keys by suffixing with an integer. ("Source_1", "Source_2") etc. This could get confusing for things like HUC... (HUC1, HUC2 etc)

More enhanced would be to suffix the metadata key with a project type machine code or some other unique identifier.

**Comment by philipbaileynar** [comment]
<img width="653" alt="Screenshot 2024-03-21 at 1 19 14 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/7219c9aa-40b8-4dd4-befd-a37ee1ac2c77">

**Comment by KellyMWhitehead** [comment]
Sorted this out. Added "Project" to metadata coming from the source project, and "Layer" to the metadata coming from the source layer. Solution is clean and the metadata looks nice and informative. Can revisit adding suffixes to the keys if needed, but I think this will fix the issue. 

Ready for 0.3.17

**Comment by KellyMWhitehead** [comment]
I also removed the blank 'source' and 'acquisition date' metadata for rasters that are imported from an RS project.
