### ISSUE TITLE
Make upstream riverscapes project URL more useful on import

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#349]
When importing a layer into QRiS that was download from the Data Exchange we should do more to link back to the original project. The fundamental, most important requirement is:

Grab the project GUID from the warehouse tag of the project and make a URL out of it.

Then the question becomes what to do with it:

# Ideas

1. Either include this URL in the metadata tab (in which case make it clickable!)
2. Store the Url as a special metadata key called `sourceUrl`. Then add a link control on the main tab of the layer properties dialog to link to this dataset (perhaps below "Source Path"). This value would be a "special citizen" metadata value that is teased out and shown on the main tab, but always stored back in metadata.
4. Perhaps if there's a source URL for a layer, it is available as right click menu option in the QRiS project tree.

<img width="653" alt="Screenshot 2024-03-21 at 1 10 33 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/37305273-e965-4fce-b327-6a469ccce22e">

**Comment by joewheaton** [comment]
@philipbaileynar are we doing this to your satisfaction now? I think we might be, but maybe a pass through to identify areas it could be preserved and improved?

**Comment by KellyMWhitehead** [comment]
Making sure the project url is getting added to the metadata. Together with #250, this should be working now.

version 0.9.5

**Comment by philipbaileynar** [comment]
Do you have a screenshot of how this appears in the QRiS user interface?

**Comment by KellyMWhitehead** [comment]
![Image](https://github.com/user-attachments/assets/9892e2e9-277e-4e22-835f-a49c87cf4810)
