### ISSUE TITLE
Add GeoTagged Photos

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#35]
A long time ago, we envisioned this as a RAVE feature, but maybe it belongs in QRiS instead (or also):
github.com/Riverscapes/RaveAddIn/issues/40

> Many have asked to see geo-tagged photos in Riverscapes projects. I'm incorporating this in the Planning LTPBR projects and I know @nick4rivers will include it in his LTPBR Design stuff.
> 
> ## Manual Option
> ESRI has an easy way to do this where you just put your Geotagged photos in a folder (inside project if you want it there), and point to it and run this really simple [geoprocessing tool](https://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/geotagged-photos-to-points.htm). It produces a shapefile that points to pictures and grabs geotag to make shapefile.
> 
> ![image](https://user-images.githubusercontent.com/9723905/82101103-c3279c00-96c8-11ea-9dcf-bdfd9d039de5.png)
> 
> [This article](https://www.esri.com/news/arcwatch/0912/import-geotagged-photographs-into-arcmap.html) ellaborates.
> 
> Then we just plug it in project.
> 
> ## Requests
> ### Open Source Photo Point Generator
> @philipbaileynar asked to see if @MattReimer could figure out an open-source alternative to this (i.e. for generating the shapefile and attribute table from photos with geotags on them in a folder like a Riverscapes Project folder).
> 
> ### Riverscapes Features
> * Right Click Photo type and **Add to map**: If geotagged photos are in a RS project folder, then one shapefile or geojson object gets generated from them and anytime a user wants to add any photo to the map (by right click) it does.
> * Right Click and **View** geotagged photos should bring up a nice looking dialog that allows preview of photo, navigating by advancing to next or previous photo, and highlights (by select) the photopoint in the photopoint shapefile on map and zooms at same zoom level to that photo in map,  and show photo metadata below on same dialog.

**Comment by joewheaton** [comment]
See also: https://github.com/Riverscapes/RiverscapesXML/issues/222

**Comment by KellyMWhitehead** [comment]
Photos can be imported to Point Observations since version 0.3.2.
