### ISSUE TITLE
Better handling of RS project metadata?

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#350]
Can we do better than showing the raw tuple when showing riverscapes project metadata? Clickable URLs? At the very least strip off the tuple perenthises and type etc....

<img width="653" alt="Screenshot 2024-03-21 at 1 13 58 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/d74f558c-b9ca-4f03-b606-07e939a29128">

**Comment by KellyMWhitehead** [comment]
Stripped the tuples to just their values for now. We can revisit in the future if we want to retain the type for the metadata values.
