### ISSUE TITLE
Streamstats not functioning in 0.3.13

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#352]
I went back to 0.13.3 after testing the plotting on 0.3.13.1. Streamstats wont work and this is the error. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/d3e12160-90c3-4b97-ac11-bb06ca397dd8)

**Comment by Jdgilby** [comment]
@KellyMWhitehead Seems to be working again.

**Comment by KellyMWhitehead** [comment]
Working for me, please reopen if this pops up again.
