### ISSUE TITLE
Metric Documentation

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#353]
This issue provides an overview of the documentation for the new QRiS metric functionality. The goals are:

1. Provide @Jdgilby with instructions on how to manage (create, edit and delete) QRiS metrics:
    - What's the schema he has to follow
    - How to Export to JSON
    - How to import from JSON
2. Provide @Jdgilby and any users of [Analyses](https://qris.riverscapes.net/software-help/analyses/) a reference library of the GIS operations available to QRiS metrics. 

Item number 1, might be fairly ephemeral, or at least will evolve a lot as QRiS metric workflows evolve. Item number 2 should have a long shelf life as valuable QRiS content that end users will want to reference to understand how QRiS is hoovering up digitized geospatial data into metrics.

---

# Managing Metrics

Create a page under "Technical Reference" called "Managing Metrics". The ToC for this page:

- Managing Metrics
    - Introduction
        - what is a metric, how are they used
        - They are stored in project, but the view is that there will be a central repository that all users can pull from
    - Viewing Metrics
        - how to get to the new list of metrics in a QRiS project
    - Exporting Metrics to JSON Files
        - Explain one file per metric
        - Explain JSON schema
    - Creating New Metrics
        - Steps to create a new metric JSON file.
        - Rules that must be followed
        - How to validate (i.e. Visual Studio Code helping check for errors)
    - Editing Existing Metrics
        - Rules that must be followed (i.e. don't change machine code)
    - Deleting Metrics 
        - Implications ( i.e. cascade delete on metric values in a project?)
    - Importing Metrics
        - How to import JSON files back into QRiS Project

# Metric Calculations

- Separate page under "Technical Reference". Each metric should have a section with an H2 header (so that the URL anchor can be used within the QRiS GeoPackage allowing for easy reference.).
- Plain English describing the methodology with accompanying map screenshot illustrating concept (e.g. dam points within sample frame polygons).
- Properties table:

Property | Value
--- | ---
Name | Dam Count
Data Type | Float
Minimum | 0
Maximum | Infinity

**Comment by KellyMWhitehead** [comment]
Documentation is up:
https://qris.riverscapes.net/technical-reference/managing_metrics/
https://qris.riverscapes.net/technical-reference/metric_calculations/
