### ISSUE TITLE
Error When Clipping Drone Imagery to AOI

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#358]
When I try clipping drone imagery to the AOI, I keep getting this error (Screenshot #1). The clipping function works for DEMs and Hillshades but not drone imagery. 

Screenshot #1: 
![Clipping to AOI Error for Surfaces ](https://github.com/Riverscapes/QRiS/assets/150490067/9080acff-ef73-4832-9c2f-05cc512dd388)

**Comment by KellyMWhitehead** [comment]
What is the format/file extension of the drone imagery that you are using?

**Comment by zburgert1997** [comment]
They are .tif files.

**Comment by KellyMWhitehead** [comment]
Thanks, I will have to dig in to this deeper.

**Comment by KellyMWhitehead** [comment]
I was unable to reproduce this error with a drone image that I had. 

@Jdgilby are you experiencing the same issue?

**Comment by Jdgilby** [comment]
@KellyMWhitehead I haven't had it happen to me on any projects. I haven't really been doing this much lately though.

**Comment by zburgert1997** [comment]
I tried this function of 0.3.17 an it seems to be working for me. Not sure what caused the error 0.3.16. I think we can close this issue @KellyMWhitehead unless there is soemthing about it you would like to look into.
