### ISSUE TITLE
Temporary Layer Import Error 

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#359]
I have been having mixed success with importing temporary layers. For some QRiS functions it works, and for others I get errors. For Cross Sections, I get this error (Screenshot #1) and for sample frames I get this error (Screenshot #2). Importing temporary layers works for AOI and Profiles but not for these functions. 

Screenshot #1: 
![Temporary Layer Error Cross Sections ](https://github.com/Riverscapes/QRiS/assets/150490067/91ebf954-6f14-4ca3-a821-f72578560a9c)

Screenshot #2: 
![Sample Frame Temp Layer Error](https://github.com/Riverscapes/QRiS/assets/150490067/9ee89f42-209d-468c-84c6-75b8fc7d3b12)

**Comment by KellyMWhitehead** [comment]
Fixed for 0.3.17
