### ISSUE TITLE
Error when Trying to Manually Delineate Cross Sections 

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#360]
After I select the option to manually delineate cross sections, I fill out the dialogue (name and description) but when I click OK, the layer is not added and the dialogue screen (Screenshot #1) freezes with the OK function no longer clickable. 

Screenshot #1: 
![Manual Cross Section Error](https://github.com/Riverscapes/QRiS/assets/150490067/a5911022-eb2b-41cc-8381-7a28c26b10c5)

**Comment by KellyMWhitehead** [comment]
Fixed for 0.3.17
