### ISSUE TITLE
Error When Generating Sample Frames from Cross Sections

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#361]
When I try to generate sample frames from cross sections, I get this error (Screenshot 1). 

Screenshot 1:
![Sample Frame Error](https://github.com/Riverscapes/QRiS/assets/150490067/b5670a91-e108-4154-9e5d-31053548ea2b)

**Comment by KellyMWhitehead** [comment]
Fixed for 0.3.20
