### ISSUE TITLE
Error When Trying to Import Existing Feature Layer as Sample Frame

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#362]
When I try to import a sample frame from an existing feature class, I get this erro (Screenshot #1). 

Screenshot #1: 
![Sample Frame Import from Existing Feature Class Error](https://github.com/Riverscapes/QRiS/assets/150490067/ff9be953-f1f5-4f7e-bef6-12029e528b74)

**Comment by KellyMWhitehead** [comment]
@zburgert1997 Can you elaborate on this - are you importing a sample frame from an existing qris project, or is this a shapefile, gpkg layer, etc?

If so, could you please give me a zip of the data? Thanks!

**Comment by zburgert1997** [comment]
It seems like I get the error when I try to import from a geopackage. I'll send a zip of the data later today.

**Comment by zburgert1997** [comment]
@KellyMWhitehead Here is a copy of the geopackage where I get this error. When I try importing the shapefile "Sample Frames" from the geopackage, I get this error which differs than the one I posted above. 

![Screenshot 2024-05-15 160550](https://github.com/Riverscapes/QRiS/assets/150490067/3be2e481-2a15-42ce-82cb-91d9dbd69323)


[Sample Frame Data Testing.zip](https://github.com/Riverscapes/QRiS/files/15327401/Sample.Frame.Data.Testing.zip)

**Comment by KellyMWhitehead** [comment]
This was an annoying OGR issue trying to get the value of the 'fid' field. Fixed for 0.3.21
