### ISSUE TITLE
Ability to update existing project export

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRiS#363]
1. Grab the project warehouse id tag
2. Export new project.xml with the tag
3. Overwrite or new project export?
4. Other considerations??

**Comment by joewheaton** [comment]
@KellyMWhitehead it seems like you are doing this correctly now? @Jdgilby feedback. If you both agree. Close.

**Comment by KellyMWhitehead** [comment]
ready for 0.9.6.

@Jdgilby Please test this out:
1) export and upload a project to the Data Exchange (or use one you have already uploaded).
2) Open in Qris and make a change.
3) Export the project: Select 'Update Existing' and browse to the project.rs.xml of the uploaded project. Ideally this should be exported to a new folder.
4) Upload this new project to the data exchange. It should upload as an existing project.

Let me know right away if there are any issues, or the workflow is too complicated. I think we can make it easier, but should suffice for now.

**Comment by KellyMWhitehead** [comment]
For Version 0.9.5: 
 
1. Done - the form opens before you specify the output folder.
2. I adjusted the form a little bit - hopefully it is a little more helpful. We should still revisit this in the future.
 
![Image](https://github.com/user-attachments/assets/8e9d37d4-93a1-427a-a0fa-3d3d8fc96980)

**Comment by Jdgilby** [comment]
This is working and much more straightforward. I successfully exported to a new folder updating the old xml as well as exported to the existing folder updating outputs as well as xml. Closing for now, we can start a new issue if we want changes in the future.
