### ISSUE TITLE
Create Project Focus

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#367]
Minor request...

When the create new project form opens can you set focus on the project name text box so that I can start typing straight away without any mouse clicks. Thanks!

<img width="506" alt="Screenshot 2024-05-07 at 2 56 22 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/9be8a984-6b14-4e03-bcc6-6f81e584bb9b">

**Comment by KellyMWhitehead** [comment]
One line of code. Easy!
