### ISSUE TITLE
Redundant Menu Choice

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#369]
Do we still need the "download" menu choice? I would prefer to keep this action just inside the dockable window.

<img width="499" alt="Screenshot 2024-05-07 at 3 02 21 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/a13a4124-89fe-4a93-a2ba-db4a5991d7a3">

**Comment by KellyMWhitehead** [comment]
@philipbaileynar Should I retain the view/expand nodes menu items as well? do we anticipate child nodes here?

**Comment by philipbaileynar** [comment]
Good call. Remove.

**Comment by KellyMWhitehead** [comment]
Completed for 0.3.19
