### ISSUE TITLE
Export just NHDPlus Catchment Wings that intersect "project area"

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#37]
Need to run the select by location to grab just these areas:
![image](https://user-images.githubusercontent.com/9723905/82102630-582c9400-96cd-11ea-9058-dc5b1dd463ff.png)

Similar to Riverscapes/LTPBR-Planning#1

**Comment by joewheaton** [comment]
This is something we might want to bring over to QRiS

**Comment by joewheaton** [comment]
So @philipbaileynar  this is interesting as a "Scratch Space" Import feature. Essentially, instead of a vector import to scratch space clipping to a mask, this would be an intersection import. This could be really useful (e.g. importing drainage wings as shown here or importing the whole level path, but not all the level paths).

**Comment by philipbaileynar** [comment]
It's a bit semantic, but I don't think you mean intersection... Surely you mean "spatial select"? i.e. bring in all the features of a layer in the map that touch my mask. i.e. bring them in in their entirety; don't perform an intersection.

**Comment by joewheaton** [comment]
> It's a bit semantic, but I don't think you mean intersection... Surely you mean "spatial select"? i.e. bring in all the features of a layer in the map that touch my mask. i.e. bring them in in their entirety; don't perform an intersection.

Sorry... yes you are correct @philipbaileynar.

**Comment by joewheaton** [comment]
This is now done with import from RS-Context project from Riverscapes Viewer.
