### ISSUE TITLE
Climate engine date range

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#370]
Some of the CE metrics have BIG date ranges (I just triggered a download from 1951!)

Please insert a dropdown above the start and end date controls with a label to the left "Date Range". Items in the drop down are:

- 1 Year
- 3 Years
- 5 Years
- 10 Years
- Full Data Extent
- Custom

Should be obvious what all these do.... The default should be one year. The date controls stay disabled unless custom is selected.

**Comment by KellyMWhitehead** [comment]
0.3.19
