### ISSUE TITLE
Climate Engine Space Time Continuum

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#371]
Radio button says space but graph is time.

<img width="1400" alt="Screenshot 2024-05-07 at 3 38 18 PM" src="https://github.com/Riverscapes/QRiS/assets/8645379/8000ced0-2669-461b-8316-f9672ccccad6">

**Comment by KellyMWhitehead** [comment]
I have disabled the "Space" option until we decide what this should show. Currently we only have time series, so we will need some type of summary to display the values along the riverscape.

**Comment by KellyMWhitehead** [comment]
0.3.19
