### ISSUE TITLE
Suggestion for Stream Gage Explorer Widget

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#377]
You can open the explorer and see the stored data from previous download. When you click on a gage, this error is given if the layer isnt added to the map for visual representation. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/46b3f6fc-9bdd-4098-96ae-40c16890b3c8)

My suggestion is, if you open the stream gage explorer any previously downloaded data that is stored makes the data points for the layer automatically add to the map... or when you click the gage in the explorer it adds it to the map. Otherwise you get annoying python errors everytime you click on a gage.

**Comment by KellyMWhitehead** [comment]
[Version 0.3.20] I have fixed the error that appears if the Stream Gage Layer isn't in the map while selecting a Stream Gage.

The stream gage map layer should be getting added to the map when the stream gage tool is opened. It might need to be manually re-added by right clicking in the project tree and selecting Add All Layers to the Map ("Add all Stream Gages to the Map" in next version).
