### ISSUE TITLE
Generate Centerline Tool Error

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#379]
When I try generating a centerline for a polygon under 'Context', I can't capture/generate the start and end points so the tool won't run to create a centerline. 

![Generate Centerlines Error](https://github.com/Riverscapes/QRiS/assets/150490067/630376b4-1d3b-4809-8cb4-79b46429e039)

**Comment by KellyMWhitehead** [comment]
@zburgert1997 Centerline tool is working for me, so I will need some more information:

The screenshot indicates you are using the AOI Hillyard Canyon layer, and the first feature has been selected (should be yellow in the map).

Is there any warning message? Are the capture buttons non-responsive?

Could also be the data and map are in different projections?

**Comment by zburgert1997** [comment]
@KellyMWhitehead I was just using the tool wrong. For capturing the start and end points, I didn't realize it was a click and drag to generate a linestring. I thought it was a click to generate a point. My bad, you can close this issue.
