### ISSUE TITLE
Can't Select Map Values for the CEM Layer

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#380]
When I try to import a layer into the CEM layer, it won't allow be to change the map values so it can translate over. 

![CEM Error](https://github.com/Riverscapes/QRiS/assets/150490067/f2e2356f-5df5-4c60-b99d-b708eb85c48e)

**Comment by Jdgilby** [comment]
@KellyMWhitehead It appears we never set attributes for this layer. The specifications are in #332

**Comment by KellyMWhitehead** [comment]
The layer attributes for CEM/SEM have been updated in version 0.9. Please test with this version and report back if problems persist, or close the ticket if this is resolved.

**Comment by joewheaton** [comment]
@Jdgilby close if you are satisfied, and reassign to @KellyMWhitehead if they need more work. Enlist @zburgert1997 to help test if needed.

@philipbaileynar and @Jdgilby and I missed these in our roundup of 1.0 release tasks. I am assigning this to [1.0](https://github.com/Riverscapes/QRiS/milestone/3), if it is unrealistic, you can move this to [1.1](https://github.com/Riverscapes/QRiS/milestone/4).
