### ISSUE TITLE
No graphical representation of Climate Engine

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#382]
Im able to do everything in climate engine, but after successfully downloading timeseries it fails to plot. The streamgage explorer does successfully plot for me though. Im using QGIS 3.34.4

**Comment by KellyMWhitehead** [comment]
@Jdgilby In the Climate Engine Explorer panel, have you checked at least one sample frame feature and selected one time series in the metrics tab?

**Comment by Jdgilby** [comment]
@KellyMWhitehead 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/aa4a2c5b-7e7c-4930-bc2c-3fa7f5180a22)
I get through this point, hit ok and then close. Then nothing shoes up in the climate engine metrics.

**Comment by Jdgilby** [comment]
@KellyMWhitehead I think the issue is data not existing for the given area or timeframe. On a different project I was able to get it to work. However it gives no warning if nothing is downloaded. I think something that would be helpful is to show the date range available for the metric. As of now you can only see that if you change from the default 1 year to full data range.
