### ISSUE TITLE
Provide descriptions of Climate Engine variables

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#383]
As they are now most variables to select are not intuitive. you would still have to go to climate engine to understand what to pull down. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/36b66081-56cf-42ec-af98-1280bc45f011)
For example: No idea what SHR, TRE, etc. stand for

**Comment by KellyMWhitehead** [comment]
Unfortunately, the API does not provide me with the descriptions for the variables. This might be something we can as the Climate Engine folks about.

In the mean time, the descriptions can be found here: https://docs.climateengine.org/docs/build/html/variables.html. Might be worth adding a link to these descriptions on the form?

**Comment by philipbaileynar** [comment]
Kelly, can you put a small square button beside the word "Variables" with an info icon (I think we are using question mark). This links to the URL you posted.

**Comment by KellyMWhitehead** [comment]
Button added for 0.3.20. We can revisit this if we gain access to the variable descriptions.

**Comment by EricRJensen** [comment]
We have our Climate Engine team meeting tomorrow and we'll discuss this. I think we can probably add an endpoint for metadata/dataset_variables_names or similar and pull on the dictionaries in our datastore. I'll followup after that.
![image](https://github.com/Riverscapes/QRiS/assets/33233973/2336079c-c968-4fbf-8178-b0555ceb47d2)

**Comment by EricRJensen** [comment]
We think we will add a list of variable names to the JSON returned from /metadata/dataset_variables, so there will still be the 'variables' key with a value of a list of variable names needed to run requests and then will also have a key of something like 'variables_names' with a value of a list of human readable variable names. I'm going to be on leave traveling from May 20-June 7, so @osheak will be in touch once we have a solution.

**Comment by EricRJensen** [comment]
Variable descriptions are now added in the metadata/dataset_variables endpoint 
![image](https://github.com/Riverscapes/QRiS/assets/33233973/dbf269f5-d7a1-40e1-b0e3-5d4e3b226c4d)

**Comment by KellyMWhitehead** [comment]
Thanks @EricRJensen, this integrated nicely. 

The download form looks much better!

![Image](https://github.com/Riverscapes/QRiS/assets/10746997/c5e10136-dffa-4cc3-bd60-018f77c7288b)

Ready for version 0.3.24
