### ISSUE TITLE
Units in Analysis

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#385]
Units in the analysis output would be great. An easy way would be adding it to the name of the metric. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/964c9588-8b4a-45b2-bc5b-b64b7d7ea3f5)
Since this is just displaying the name from the metric JSON, we could just include it in the name in the JSON metric file (e.g Jam Density (#/km). You can reassign to me if this seems like the best way to do it.

**Comment by joewheaton** [comment]
Model after GCD please

**Comment by KellyMWhitehead** [comment]
closing this as this is a duplicate of #415
