### ISSUE TITLE
Add sort functionality to Right-Click of DCE

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#392]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/7e7355d7-6fe9-484c-b29e-4ba6745ef170)
Add a sort button here, with ability to do it by: Date specified in properties, or alphabetically.

**Comment by KellyMWhitehead** [comment]
I have the name sorting for 0.3.20. Will get the date sorting in a future release (this will take a little more work).

![sort](https://github.com/Riverscapes/QRiS/assets/10746997/3b79ed12-005b-4d35-8f48-0ee483eeed23)

**Comment by KellyMWhitehead** [comment]
Added the date sorting for version 0.3.21
