### ISSUE TITLE
Add sort functionality to right-click of surfaces node

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#393]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/0270f254-87be-42a5-a977-25893f56dc5c)
Right click on surfaces give option to sort by: date, alphabetically by name, or alphabetically by surface type)

**Comment by KellyMWhitehead** [comment]
Name sorting ready for 0.3.20. Others to follow...

**Comment by KellyMWhitehead** [comment]
date and surface type sorting have been added. 0.3.21
