### ISSUE TITLE
Surfaces form should have a date specification similar to the DCE forms

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#394]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/4b7d8e4a-425e-47b9-8df6-b7299195eb1f)

Add date to form like those in DCE properties
![image](https://github.com/Riverscapes/QRiS/assets/97305413/cb0d0414-dc45-494e-9c59-bcaf25e5717d)
 This will allow to sort by date as mention in issue #393 as well as reduce liklihood that user will fail to input date in the name or metadata.

**Comment by joewheaton** [comment]
I think this is fixed. If anyone disagrees, reopen with something specific.
