### ISSUE TITLE
Add a source dropdown in surfaces properties.

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#395]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/6eac2664-8d46-45f3-acfd-55b2f3aee369)
 Add a source dropdown to Surface Properties form.
Options include our current workflows: Satellite (generic, may include google screenshots or historic usgs downloads etc.), drone, Dronedeploy, Pleadies-Neo Satellite.

Other thoughts on this.
-Surfaces imported through viewer autopopulate source as Riverscapes Project and bring across metadata. 
-Not sure how to best deal with other surfaces like detrended surface that are derived elsewhere

@joewheaton You might have specific ideas here beyond what I've mentioned. This one could get a bit more complicated or we could keep it simple.

**Comment by philipbaileynar** [comment]
@Jdgilby can we use a free form textbox for "source"? Dropdown is quite limited and I'm unsure if we know the definitive list of options. Adding and changing the list would require updating the software.

**Comment by Jdgilby** [comment]
@philipbaileynar Ya that seems like it would be a good way to do it.

**Comment by KellyMWhitehead** [comment]
I implemented this as the best of both options: a dropdown with the common types that @Jdgilby listed above, but the box is also freeform so the user can type in a custom type if they want. 

Ready for 0.3.22
