### ISSUE TITLE
Add ability to attach metadata to surfaces in properties form

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#396]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/5675dd04-8023-46f6-97b5-a801b37b3430)
Rather than rely entirely on user filling out the vague key value pair add a spot in the main form to attach a metadata file.

Reasons this is important.
-Satellite data comes with an .xml that specifies the properties of the imagery such as band assignments. Qgis does not get this right if its more than RGB. You need to know which bands are what, which is different on different satellite sources. Also includes capture date, etc.
-Drone deploy creastes a report that is important to the accuracy assessment of the data. I've encouraged this shouldnt be ignored and should be downloaded with drone deploy exports/surfaces. [Here](https://storage.googleapis.com/dronedeploy-assets-prod/dcddcd0962_F509AA2845OPENPIPELINE/report.pdf?GoogleAccessId=web-sa-prod@dronedeploy-public.iam.gserviceaccount.com&Expires=1716145200&Signature=RFujNBA8oYaI51bsoIxcEqi9P%2FvPbMLlDfzIfk80VVxUoaFcsJNSpIAwREEE8iBO3u5MFsiL7KLlW8o0zjfrJ4zrH0RyXed098u58bsktYa9spiuhnfLEkFYJ36irLCxpuKivwSar1CKXQJfihTYz%2BLUl2GmBdwCT5G9%2FIUqTKS5rxGj5oAV4gvaC9PvUZQVc7IQVP5ifRm7wcaY4QezoHmhgwbNHG4gCAzAA%2FlXrkQhMkt1Yjjt4J90OnQZNDVgxveH%2FxZjxzN%2Boo17XYVG82SC%2B8p6n0XOsRi6cu%2BzHWJX8yliKadA5q4GEJ1PkoKSA3T0Jdx6WX%2FMcPUtxQq34g%3D%3D)s a link to one of those reports.

**Comment by joewheaton** [comment]
See also #250 and #438

**Comment by Jdgilby** [comment]
@KellyMWhitehead Closing for now. Seems to be solved by #437 and #250 #438
