### ISSUE TITLE
Add Riverscapes node to Qris Tree

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#397]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/3ca8903d-3f0f-4e29-843e-b9f6abb33adf)
If following the LTPBR manual of assessing and planning a design, delineating a VB is the first step in the process. This can be a basis for other layers in future steps of a project but it should exist on its own separate from DCEs or SFs.

-Should be first node, call it riverscapes.
-Right clicking node gives the following options
>1. Add valley bottom 
>> Import from existing vector feature class
Manually digitize
Import temporary layer

Additionally, since data brought from riverscapes projects ends up in context, right clicking on an imported level path valley bottom should have the option to 'Promote to Riverscapes valley bottom' the same way dgos can be promoted to SF.

Multiple VBs can exist in this node, separate level path VBs in same project or separate reach.

**Comment by philipbaileynar** [comment]
I'm somewhat OK with this. I get the "first step in the process" importance of this layer. But I have some questions...

1. What is the longitudninal extent of this polygon? i.e. entire project, or level path or reach or geomorphic unit or DGO?
2. What is the lateral extent of this polygon? Is it valley wall to wall? Or active or inactive?
3. Can there be multiple features?
4. What attributes are needed?
5. How does this relate to sample frames?
6. How does this relate to analyses?

I'm OK if the answer is, "the process of capturing this polygon is more important than the actual feature class itself". i.e. sample frames remain the driver of metrics, but this riverscapes feature class is somewhat ceremonial or even just a cookie cutter similar to AOIs.

**Comment by Jdgilby** [comment]
@philipbaileynar In the conversation I had with @joewheaton we had decided on a few things.
1. More of a reach scale extent but multiple could exist in a project if there are multiple reaches within one project. If were importing from VBET think more like level path clipped to AOI, not DGO. 
2. Valley wall to wall. We have a separate layer already for active/inactive.
3. Yes, as mentioned in 1. I don't think it matters if there are multiple features in one VB feature class or if there are multiple vb feature classes, similar to AOIs and SFs.
4. No attributes needed. Nothing to define, were just after VB extent. Just the standard notes and area that come on every polygon feature.
5. Could be used as the extent for Sample Frames but it shouldn't be required for or tied to SFs. You Could use it as a reach scale SF if you wanted to analyze at scale larger than DGO. 
6. Not necessary for analysis, this is more planning and context, as well as the starting point for layers that split up the VB (active extents, recovery potential) As mentioned in 5 it could be used as a SF, the polygon used when creating your own SFs, But shouldnt be required for any analysis. 

More similar to an AOI than a SF, but needed for planning and riverscape context.

**Comment by philipbaileynar** [comment]
Cool. I say proceed.

Some things to think about @KellyMWhitehead:

1. Do we need a "QViewer import into Valley Bottom" option?
2. do we need a "Promote to Valley Bottom" right click on context layers?

**Comment by KellyMWhitehead** [comment]
Valley bottoms added for 0.3.25. @Jdgilby feel free to add a a symbology file (valley_bottoms.qml) if you want.

![Image](https://github.com/Riverscapes/QRiS/assets/10746997/0d7353b0-125d-4e6b-8d89-d2b6ac7131e6)
