### ISSUE TITLE
DCE properties include dropdown for specifying associated valley bottom

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#398]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/119fd6ab-3679-4a89-8438-9b17bbac0203)

If issue #397 is implemented this should follow.

Add a dropdown to select the associated valley bottom with the data capture event, just as we associate a surface. Adds organization for multi-reach projects. 

@joewheaton please clarify if this is too vague or doesn't give enough context to the importance of this.

**Comment by KellyMWhitehead** [comment]
Added in 0.3.25
