### ISSUE TITLE
Add right-click 'import geometry from valley bottom' on layers that use valley bottom extent

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#402]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/7e0dbb02-fb26-4f40-a889-f86e4bb99bf8)
Do this for the following layers:
- Active Extents
- CEM
- Recovery potential (layer not yet implemented)

Reasoning for this is to have any easy starting point from already created valley bottom. It provides a way to slice up into different categories in a more controlled, geometry consistent way, with less potential for geometry errors in digitizing.

This is dependent on issue #397

**Comment by KellyMWhitehead** [comment]
ready for 0.3.25
