### ISSUE TITLE
Add recovery potential layer to LTPBR protocol

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#403]
Add layer to LTPBR protocol.
-no attributes, its either recoverable or empty. Similar to vegetation extents. 
-should exist under the assessment node
-should be event type future. (not sure how to handle this. Possibly only available under 'layer' tab in properties if future has been specified in properties) 
-Recovery potential layer lives in Planning Event (new node from #391)>Planning DCE>Assessment>Recovery Potential

Other things to think about... Does it exist amongst all the layers in methods?
![image](https://github.com/Riverscapes/QRiS/assets/97305413/997f1836-44eb-41a2-b35e-d1323b597a90)

Or is that issue solved with #401 which would make it known that it is a planning layer.

@joewheaton the framework is here, I just think its a little complicated. Thoughts?

**Comment by KellyMWhitehead** [comment]
0.3.23
