### ISSUE TITLE
Metadata DCE type in project.rs.xml is wrong for AsBuilts

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#406]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/97f37849-b4a1-40e0-a3ff-9debc3735a92)
Looks like both designs and asbuilts get the same meta name tag of "Design". This makes it so I cant organize as built events in the business logic.

**Comment by KellyMWhitehead** [comment]
Fixed for 0.321
