### ISSUE TITLE
BRAT CIS layer needs points added to the name

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#411]
Currently we have the 2 layers brat_cis and brat_cis_reaches in the QRIS layers database. When writing business logic this causes an issue where the same layer is brought into the viewer twice since @lyrname, 'brat_cis' recognizes both layers.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/5ae6be6f-19f5-4d59-bf09-bb6bb91946e4)
![image](https://github.com/Riverscapes/QRiS/assets/97305413/c3040bad-7b3b-49d9-9163-a53f85480d3f)
My thought was to change brat_cis to brat_cis_points. 

@KellyMWhitehead let me know if its better to just change the business logic

**Comment by KellyMWhitehead** [comment]
@Jdgilby try this in the business logic:
```
<Node label="BRAT CIS" xpath="Datasets/Geopackage/Layers/Vector[contains(@lyrName, 'brat_cis') and not(contains(@lyrName, 'reaches'))]" type="point" symbology="brat_cis" id="brat_cis"/>
```

**Comment by Jdgilby** [comment]
@KellyMWhitehead Seems to be working. Thanks.

**Comment by KellyMWhitehead** [comment]
Fix made to BL, no changes needed in QRiS. Closing.
