### ISSUE TITLE
Riverscapes Viewer fails to show features exported as multiline or multipolygon

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#412]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/93efbd6b-dd0c-45d4-bea3-a849ba31a924)
Looks like a change in business logic would fix it. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/6230f1ec-e66c-4c3a-a8b2-2daf9677ed7c)
Just wanted to make it known incase we wanted to convert layers from multi to single on export.

**Comment by KellyMWhitehead** [comment]
I will make the change in the project export to just points, lines, polygons. Keep the business logic as is.

**Comment by Jdgilby** [comment]
@KellyMWhitehead Will the ones that end up being multi just be left out or converted to single prior to export?

**Comment by KellyMWhitehead** [comment]
@Jdgilby 

Those layers will remain multipart. The viewer doesn't really care about multi vs single, it just needs to know the base geometry type.

**Comment by KellyMWhitehead** [comment]
@Jdgilby 
Ok, I've changed my mind (sorry!). Lets try changing the business logic first:
```
<Repeater label="Points" xpath="Datasets/Geopackage/Layers/Vector[contains(Summary, 'context_point') or contains(Summary, 'context_multipoint')]">
<Repeater label="Lines" xpath="Datasets/Geopackage/Layers/Vector[contains(Summary, 'context_linestring') or contains(Summary, 'context_multilinestring')]">
<Repeater label="Polygons" xpath="Datasets/Geopackage/Layers/Vector[contains(Summary, 'context_polygon') or contains(Summary, 'context_multipolygon')]">
```

If that doesn't work, then I will make the change in QRiS.

**Comment by Jdgilby** [comment]
@KellyMWhitehead That looks like it worked, thanks.

**Comment by KellyMWhitehead** [comment]
Fix made to BL, no changes needed in QRiS. Closing issue.
