### ISSUE TITLE
Select all / none buttons on create analysis form

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#414]
On the create analysis form, add buttons for select all/none. 

In the demo today, Josh had to visit nearly all metrics to turn them off for his needs.

**Comment by KellyMWhitehead** [comment]
![analysis](https://github.com/Riverscapes/QRiS/assets/10746997/33a9a8df-afc6-4720-85f9-f176da4d8088)

**Comment by KellyMWhitehead** [comment]
0.3.23
