### ISSUE TITLE
Metric Formatting and Units

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#415]
1. **MUST** see units somewhere on the screenshot below.
2. Each metric should have a format string in the metric JSON. Just have a string link `'{0.2}'` or whatever the Python syntax is. Then the code just puts the value through this using a print statement.

<img width="408" alt="Screenshot 2024-06-03 at 10 12 42 AM" src="https://github.com/Riverscapes/QRiS/assets/8645379/311a9168-6f21-4151-92a5-62db51036903">

**Comment by KellyMWhitehead** [comment]
@jtgilbert You can set the precision of the display value in the metric definition:
```
  "metadata": {
    "precision": 2
  },
```
In this example, the value will be displayed to 2 decimal places. If there is no precision defined, it will display the full float. This does not affect the value stored, only the display.

**Comment by joewheaton** [comment]
I would also like to see a column between value and uncertainty for units. 

Eventually, I would love to be able to have a settings ⚙️ cig in this dialog that allows user to switch view of units. I personally would love a return to volumetric units of US Beer Barrels

**Comment by KellyMWhitehead** [comment]
Here is the current implementation of unit labels:
![image](https://github.com/Riverscapes/QRiS/assets/10746997/b6343fea-e94f-4a18-9f6e-238e94f7206a)

1. Base units are inferred from the calculation method, which always uses (i.e. reprojects geometry) to SI units.
1. Several of the metrics with % in the metric name use the proportion calculation, which the output is a ratio. When unit conversions are implemented, we could set the default display units to percent (specify in the metric definition).
2. If these unit labels are too verbose, I can scale them back if desired.
3. No guarantee on units for manually entered metrics. Its whatever the user provides.

**Comment by philipbaileynar** [comment]
1) Let's have an abbreviation for each unit as well as a verbose string. For counts per unit length this can be "#/m". 
1) Having the units in the same column as the metric name makes the metric names harder to read quickly. Let's move the units into their own column. Make it a narrow column that just displays the abbreviation with the full unit name as a tooltip.
1) Let's put a "Units" button just above the table, right aligned, the same level as the metric/indicators radio buttons. This form has three drop downs: 1) Linear units based on... 2) Areal units based on... 3) Ratios displayed as (% or raw ratio). Then all the metrics respond accordingly.

**Comment by KellyMWhitehead** [comment]
Units and Unit conversions added in 0.3.23.

Please review and advise if any additional changes are required.
