### ISSUE TITLE
Error opening and closing projects in 0.3.22

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#418]
I installed this version today. First thing I did was get a successful export. Then I closed the project to open in the viewer. When I tried to reopen the project through QRIS I got this error.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/1512131f-c1a1-4b10-929a-25faa34937f3)
I now get the same error when closing the project, the project does close however. 
Once I've closed and got the error I cant open a project until restarting Q.

**Comment by KellyMWhitehead** [comment]
Fix ready for 0.3.23

**Comment by Jdgilby** [comment]
@KellyMWhitehead I imagine its the same thing but this also happens when trying to go into settings under help
