### ISSUE TITLE
Error when trying to go to properties of a watershed catchment 

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#420]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/2794f075-d78d-4fd4-bb10-d8738ce3fca8)

**Comment by KellyMWhitehead** [comment]
Looks like the basin characteristics don't always return values. Modified the form to display N/A if the value(s) are not present:
![image](https://github.com/Riverscapes/QRiS/assets/10746997/a29bb861-cf19-4944-9000-0d9d64c33cd3)

Ready for 0.3.23
