### ISSUE TITLE
Sample Frame issues

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#421]
Finicky import of Sample Frames. I cant pinpoint whats going on. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/301a5ad2-dc59-4968-b84f-4042757a2cd6)
I sometimes cant get past this form. Hitting OK does nothing. Its worked a few times by making sure none of the dropdowns are left as 'None'. But even in that case it has failed to work a few times. 

This is applicable to both options of creating a Sample Frame from a temporary layer as well as creating an empty sample frame to digitize.

Looking into it further it appears that some actually did make it into the project database even though no features were imported.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/d6387e81-1d18-41a8-bfcd-9881ca953888)

And even weirder is Sample Frames that failed to be created and never even made it into the sample_frames table show up as an option in climate engine.
![image](https://github.com/Riverscapes/QRiS/assets/97305413/08a7aa32-9bf4-4ff1-a5c5-232a689ed496)

Closing and reopening the project fixed the climate engine finding non existent sample frames and displayed the other missing ones in the qris tree. But part of the issue is its failing to bring in the data but still storing it as an empty feature. But that isnt even apparent until closing and reopening.

![image](https://github.com/Riverscapes/QRiS/assets/97305413/f709aed7-ff03-41a2-b9ec-9ecbe52c2a4f)

**Comment by KellyMWhitehead** [comment]
I think this is fixed for version 0.3.26, or at least improved. 

I will keep this open for a while, please respond if this behavior persists.
