### ISSUE TITLE
Cant open existing Sample Frame properties

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#422]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/2b4d7bf3-d705-4183-badc-6a8ebad4c825)

**Comment by KellyMWhitehead** [comment]
@Jdgilby is this an older project, or newer?

**Comment by KellyMWhitehead** [comment]
Figured this one out. Should be fixed for 0.3.26
