### ISSUE TITLE
Error Message When Opening Older QRiS Project into 0.3.26

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#434]
I keep getting this error message when I load my old QRiS project (completed in 0.3.24) into 0.3.26. All the data seems to load in fine but this message keeps popping up whenever I load my current qgz file or load the project in a new qgz file. 

![Screenshot 2024-07-03 220903](https://github.com/Riverscapes/QRiS/assets/150490067/b83cd51e-b857-4fd7-90d6-56540a66e95a)

**Comment by KellyMWhitehead** [comment]
@zburgert1997 I will need to take a look at the project. Please attach here. Thanks!

**Comment by zburgert1997** [comment]
Here is a link to the zipped file of the project since it is too big to upload to GitHub: 

https://drive.google.com/open?id=1LHolii4pddC1KHPbuR2bBzTqWiRIJVLx&usp=drive_fs

**Comment by zburgert1997** [comment]
Thanks Kelly. I have three other older projects (all completed in 0.3.24) which have the same problem and don't ingest the QRiS symbology. Want me to send you those as well to fix?

**Comment by KellyMWhitehead** [comment]
@zburgert1997 sorry I lost track of this ticket. If you send me the other three projects, I can fix those as well.
