### ISSUE TITLE
New Container for Uploading URL Links

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#436]
It would be nice to have a seperate container where the user can upload URL links into a QRiS project. For example, the container could contain links to the LT-PBR Explorer, the project proposal, a storymap, etc. By clicking on those links in the container, the user would be redirected to the assoicated webpage.

**Comment by joewheaton** [comment]
I like this idea @Jdgilby. Lets flesh it out a bit more with @philipbaileynar and @KellyMWhitehead. I think we want to make most of these project information, but some might be DCE or AS-Built, or Design specific. Lets revisit post 1.0.

**Comment by KellyMWhitehead** [comment]
URL links are now available in the Metadata Tab for all Containers with a Properties form. If this is sufficient, then please close the ticket. Otherwise, I am happy to discuss other options.

**Comment by KellyMWhitehead** [comment]
Closing for now. Please reopen if someone wants a different way of storing urls other than as metadata.
