### ISSUE TITLE
Move metadata along with layer when the layer is promoted to another feature

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#439]
![image](https://github.com/Riverscapes/QRiS/assets/97305413/f7c18549-1351-4482-97d6-b94a77dbd5c1)
When data from projects is brought into context it has metadata. If that layer is promoted (say to Riverscapes, Sample Frames, etc) the metadata doesn't come with it. 
![image](https://github.com/Riverscapes/QRiS/assets/97305413/ce2a6b4c-f639-48f5-836d-30708a8603c1)

**Comment by joewheaton** [comment]
This is important. But it can wait until 1.1.

**Comment by KellyMWhitehead** [comment]
Ready for 1.0.1
