### ISSUE TITLE
Move the generate centerline tool

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#440]
Right now the only place you can access the Generate Centerline tool is through polygons features in the Context node. The main purpose of centerline is tracking metrics over riverscape so the riverscape is where it should come form.
 Three requests:
1. Remove access to centerline tool in Context node, 
2. Add the centerline tool to right click in polygons in Riverscapes node.
3. To properties of saved centerline add the associated Riverscape valley bottom it was generated from.

I think importing a centerline from VBET and promoting will be a non issue because it will have that tracked through metadata.

**Comment by KellyMWhitehead** [comment]
1. Done for v0.9.6
2. Done for v0.9.6
3. The centerline tool already does this, however it saves this as 'system metadata' that QRiS does not currently exposed to the user. I should probably expose this to the user as a non-editable table (or similar format). We can start doing some 'smart' things with these feature associations in 1.1.
