### ISSUE TITLE
Allow cross section clipping to be VB Polygon from Riverscapes Node

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#441]
Currently can only clip to AOI
![image](https://github.com/Riverscapes/QRiS/assets/97305413/262c9472-7363-4554-866d-00ee6d54c259)
Suggestion is either change the 'Clip to AOI' to 'Clip to' and add polygons from Riverscapes node into dropdown with the AOI layers, or remove ability to clip to AOI restricting the user to go through the project through the riverscapes planning process.

**Comment by joewheaton** [comment]
This is important. If this is easy, I would love to see this in 1.0 please @KellyMWhitehead

**Comment by KellyMWhitehead** [comment]
This took a little restructuring, but we can now do this in other places if we want. Please give this some testing!

Version 0.9.6
