### ISSUE TITLE
Can't Add "Type" for Most Layers on New Feature Creation when Editing

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#442]
Can't add structure types, get a python errror. Will let you choose a type but it doesn't stick on saving edits.

<img width="696" alt="Screen Shot 2024-07-15 at 2 40 15 PM" src="https://github.com/user-attachments/assets/9f409d01-8642-4453-bfa3-73e1d76b19af">
<img width="920" alt="Screen Shot 2024-07-15 at 2 38 50 PM" src="https://github.com/user-attachments/assets/0d94b8f6-0b5d-477f-8956-5ee19f002710">

**Comment by nick4rivers** [comment]
This is basically any of the dropdown attributes for most layers when editing

**Comment by jtgilbert** [comment]
I'm having a similar issue with attributes not saving for structural element point features.

**Comment by Jdgilby** [comment]
@KellyMWhitehead Hey I meant to post this issue last week. I get the same thing when adding any new features. It happens as soon as you click or delineate the feature. So prior to ever choosing the type. Existing projects with existing data seem to functioning fine.

**Comment by KellyMWhitehead** [comment]
This should be fixed for 0.3.27, but let me know if it continues to come up.

**Comment by Jdgilby** [comment]
@KellyMWhitehead I temporarily had an issue, not sure why, but after trying to get to the bottom of it its working. We'll see if anyone else runs into it.

**Comment by KellyMWhitehead** [comment]
Closing for now. Reopen if it happens again.
