### ISSUE TITLE
Make Sample Frames 'create from QRIS features' defualt polygon layer to Riverscapes node Valley Bottom

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#443]
![image](https://github.com/user-attachments/assets/60918542-f7aa-405a-825a-f4a3a1d6b9bf)
Currently allows polygon selection from AOI and Context. Need to add selections from Riverscapes and remove from Context. 
If a Valley Bottom in Riverscapes exist make this the auto populated default.

**Comment by joewheaton** [comment]
@KellyMWhitehead did you get this done?
