### ISSUE TITLE
Centerline not appearing in 'Create Sample Frame from QRIS features' until closing and reopening project

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#444]
![image](https://github.com/user-attachments/assets/9f5b97b0-22c8-48c2-b281-273454a779c5)
![image](https://github.com/user-attachments/assets/81b284ae-fb82-4e6f-b98a-e3751bee4ab5)
 Even though CL5 is saved in the project its not being recognized in the dropdown menu until closing and reopening the project.

**Comment by KellyMWhitehead** [comment]
@Jdgilby I'm not getting the same behavior - the centerlines are appearing in the dropdown as expected. How was CL 5 created in the project?

**Comment by Jdgilby** [comment]
@KellyMWhitehead It was when generated and saved from the centerline generator tool

**Comment by KellyMWhitehead** [comment]
fixed for 0.9.1

**Comment by joewheaton** [comment]
@Jdgilby close if you are satisfied, and reassign to @KellyMWhitehead if they need more work.

@philipbaileynar and @Jdgilby and I missed these in our roundup of 1.0 release tasks. I am assigning this to [1.0](https://github.com/Riverscapes/QRiS/milestone/3), if it is unrealistic, you can move this to [1.1](https://github.com/Riverscapes/QRiS/milestone/4).
