### ISSUE TITLE
Missing dropdown options in Design form. 

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#447]
In the Bases for design tab, the future (recovery Potential) dropdown is not populated with existing DCEs like Existing and Historic is. 
![image](https://github.com/user-attachments/assets/a648642d-6984-4297-aa9c-5f1d272d3fce)

**Comment by KellyMWhitehead** [comment]
@Jdgilby The Future dropdown is currently filtered to Planning type DCE's. Should this be changed to generic DCE's (or planning and generic)?

**Comment by KellyMWhitehead** [comment]
I will rework this for the next release. Replace the individual drop downs with an event library widget (similar to the planning container) so we can have multiple DCEs. Users will be able to add DCE's manually or reference a Planning Container.

**Comment by KellyMWhitehead** [comment]
Duplicate issue of #482. Closing this ticket.
