### ISSUE TITLE
New feature class for beaver dam censusing 

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/QRiS#448]
We want lab techs to be using QRiS for dam censusing going forward, so we need a new feature class available in DCEs.

One layer should be 'beaver_dam' with attributes: 
- 'dam_cer': 'high', 'medium', 'low'
- 'dam_type': 'active_dam', 'inactive_dam', 'relic'
- 'type_cer': 'high', 'medium', 'low'

The other layer is 'beaver_sign' with attribute:
- 'type': 'bank_lodge', 'bank_den', 'pond_lodge', 'chew_stick', 'clipped_vegetation', 'felled_tree', 'harvested_branches', 'food_cache', 'slide', 'canal', 'scat', 'set_of_tracks', 'scent_mound', 'skid_trail', 'pond_excavation', 'other'

**Comment by KellyMWhitehead** [comment]
Where should this layers go within the hierarchy? 

![image](https://github.com/user-attachments/assets/0811632a-e170-41e9-aca1-b95ddb774096)

**Comment by jtgilbert** [comment]
Observations

**Comment by KellyMWhitehead** [comment]
@jtgilbert These are points layers, correct?

**Comment by jtgilbert** [comment]
@KellyMWhitehead correct!

**Comment by KellyMWhitehead** [comment]
Added to Version 0.9

**Comment by joewheaton** [comment]
This is in. Works for now. We will consider making a new protocol in 1.1.
