### ISSUE TITLE
Import Context Vector Layer from Feature Class Error

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#450]
Hey, getting a copy error when trying to import a Context vector layer.

[https://youtu.be/pJqpdDCyt00](https://youtu.be/pJqpdDCyt00
)

**Comment by joewheaton** [comment]
@KellyMWhitehead please investigate with @nick4rivers and see if it can be reproduced.

**Comment by KellyMWhitehead** [comment]
Unable to reproduce. There have been a few changes made to the import context tool recently, this might have been fixed with them. 

Please reopen if the error is encountered again.
