### ISSUE TITLE
Error when trying to edit properties of DCE (As Built)

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#451]
![image](https://github.com/user-attachments/assets/bca3c123-4d60-4229-a7b9-52adf4316339)

I had edited the properties previously and needed to go back in and change something and now I cant.

**Comment by joewheaton** [comment]
I get the same error. I was able to reproduce.

**Comment by KellyMWhitehead** [comment]
@Jdgilby could you please attach the offending project? I was unable to reproduce.

**Comment by Jdgilby** [comment]
@KellyMWhitehead I dont currently have one that it is happening on. Seems to be a sporadic issue.

**Comment by KellyMWhitehead** [comment]
Actually I figured it out. Construction Date was not formatting in the json correctly. Fixed for 0.9.6.

**Comment by KellyMWhitehead** [comment]
@Jdgilby please test and close ticket if this is resolved.
