### ISSUE TITLE
Changes to Vegetation Extents layer

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#455]
1. Add Attribute 'Type' with options 'Riparian' and 'Non-Riparian'
2. Add optional Attribute 'Tier 2 Type' with options 'Emergent Riparian' , 'Woody Riparian', and a custom user defined text box for any other types that might be wanted.
3. Lump Brat Vegetation Suitability into Vegetation Extents Layer. Add attribute 'Suitability' with options 'Unsuitable, Barely Suitable, Moderately Suitable, Suitable, and Preferred'

**Comment by KellyMWhitehead** [comment]
Version 0.9

**Comment by joewheaton** [comment]
@Jdgilby close if you are satisfied, and reassign to @KellyMWhitehead if they need more work.

@philipbaileynar and @Jdgilby and I missed these in our roundup of 1.0 release tasks. I am assigning this to [1.0](https://github.com/Riverscapes/QRiS/milestone/3), if it is unrealistic, you can move this to [1.1](https://github.com/Riverscapes/QRiS/milestone/4).

**Comment by Jdgilby** [comment]
@KellyMWhitehead Can we change the attribute "Suitability" to "Brat Suitability"?

**Comment by KellyMWhitehead** [comment]
Included in migration for 0.9.6

**Comment by Jdgilby** [comment]
@KellyMWhitehead Can we get rid of the BRAT suitability layer since it is now lumped with vegetation?

**Comment by KellyMWhitehead** [comment]
Brat Vegetation Suitability layer is removed for the next release 0.9.5
