### ISSUE TITLE
Finish Dam Crests layer

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#457]
This layer needs attributes:
"Structure Source" with options 'Natural', 'Artificial', and 'Unknown'
"Dam State" with options 'Breached', 'Intact', 'Blown Out'
"Crest Type" with options 'Active', 'Inactive'. 
"Confidence" with options 'High', 'Medium', 'Low'. 

This is a RIM layer

**Comment by KellyMWhitehead** [comment]
@Jdgilby Is this a new layer or retread of the existing Dam Crests layer (under Assessments/Beaver Dam Building)?

**Comment by Jdgilby** [comment]
@KellyMWhitehead Ya same layer as before, reworked a little. Things might change in the next version, but hopefully not.

**Comment by KellyMWhitehead** [comment]
Added to Version 0.9

**Comment by joewheaton** [comment]
@KellyMWhitehead there are a bunch of these that seem like maybe you did them, maybe you didn't? Please assign to @Jdgilby if they need testing. @Jdgilby close if you are satisfied, and reassign to @KellyMWhitehead if they need more work.

@philipbaileynar and @Jdgilby and I missed these in our roundup of 1.0 release tasks. I am assigning this to [1.0](https://github.com/Riverscapes/QRiS/milestone/3), if it is unrealistic, you can move this to [1.1](https://github.com/Riverscapes/QRiS/milestone/4).
