### ISSUE TITLE
Change Centerlines of active channels name

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#458]
Change to 'Active Channels Lines' to stay consistent with how other layers are named.

**Comment by KellyMWhitehead** [comment]
Changed for 0.9

**Comment by joewheaton** [comment]
@Jdgilby close if you are satisfied, and reassign to @KellyMWhitehead if they need more work.

@philipbaileynar and @Jdgilby and I missed these in our roundup of 1.0 release tasks. I am assigning this to [1.0](https://github.com/Riverscapes/QRiS/milestone/3), if it is unrealistic, you can move this to [1.1](https://github.com/Riverscapes/QRiS/milestone/4).
