### ISSUE TITLE
Analysis over time not working correctly in the Analysis Summary

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#463]
As you move between sample frames the output graph doesn't change. 
![image](https://github.com/user-attachments/assets/3913a45c-80b0-4081-a605-2a4c1ab375fb)
![image](https://github.com/user-attachments/assets/003a522c-33b3-4c19-a3ff-9f348c8ea443)

**Comment by joewheaton** [comment]
@KellyMWhitehead if this is a quick fix, please include in 1.0. If not, please punt to 1.1.

**Comment by KellyMWhitehead** [comment]
Fixed for 1.0
