### ISSUE TITLE
Fix the date display on analysis graphs

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#464]
![image](https://github.com/user-attachments/assets/f96b575d-d68f-477b-9b06-40985d7693b0)
The default size has all the dates overlapping, scaling fixed the problem.
![image](https://github.com/user-attachments/assets/cbf8e21c-7821-4d0c-b348-8ece99bc47de)
However by default we should size the popup to fit it all, or scale the graph/labels to fit the default pop up size.

**Comment by KellyMWhitehead** [comment]
Did a couple of tweaks to improve readability and try to keep the axes labels from getting cut off. This should be sufficient for now - this tool will is just a prototype and will need some polish and detail. I would like to avoid monkeying with the plots until we have a look and feel sorted out. 

Ready for 1.0
