### ISSUE TITLE
Changes to Geomorphic Units Layers

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#466]
@joewheaton Can you confirm I got this right before @KellyMWhitehead makes any changes.

I remember we decided to get rid of Tier 2( or potentially auto populate based on selection of tier 2.5)

New Attribute Will be 'Type' and options will be 'Pool', 'Riffle', 'Mid Channel Bar', Bank Attached Bar', 'Glide/Run', 'Pond', 'Rapid', 'Chute', and 'Cascade'

**Comment by KellyMWhitehead** [comment]
Added new fields to Geomorphic Unit Extent and Geomorphic Unit (points) layers. Version 0.9

Did not remove tier 2 field until I get the go ahead.

**Comment by joewheaton** [comment]
@Jdgilby close if you are satisfied, and reassign to @KellyMWhitehead if they need more work.

@philipbaileynar and @Jdgilby and I missed these in our roundup of 1.0 release tasks. I am assigning this to [1.0](https://github.com/Riverscapes/QRiS/milestone/3), if it is unrealistic, you can move this to [1.1](https://github.com/Riverscapes/QRiS/milestone/4).

**Comment by Jdgilby** [comment]
@joewheaton Do we still want Tier 2 or just go with 2.5?

**Comment by joewheaton** [comment]
Go with both, but 2.5 is only mandatory

**Comment by Jdgilby** [comment]
@KellyMWhitehead Im not sure the of the form functionality the way they're currently set up. If its possible ideally we would want Type as the first dropdown and its mandatory (especially since symbology is based off this field). And Type 2 Tier would be optional.

**Comment by KellyMWhitehead** [comment]
I have moved the Type field to the top and specified it as mandatory, however I need to plumb the logic into this. I don't think that part will be ready by v1.0.

**Comment by Jdgilby** [comment]
@KellyMWhitehead Thats fine, we will have to do this for other layers as well anyways. As long as the symbology communicates for V1 we are fine.

**Comment by KellyMWhitehead** [comment]
Mandatory fields will be added in #499
