### ISSUE TITLE
Changes to risk Layers

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#467]
Risk Potential (Points)
1. Leave attribute "Risk" and options 'Low, 'Medium', 'High'
2. Add attribute "Type" and options 'Culvert', 'Bridge', 'Diversion' and ability to type in custom (if possible) if not add 'Other'. This attribute should be optional. 
3. Label based on attribute "Type" if it is filled out. 

Risk Potential (Lines)
1. Same as Above
2.  "Type" options should be 'Road', 'Pathway/Trail', 'Canal', 'Railroad' and ability to type in custom (if possible) if not add 'Other'. This attribute should be optional.
3. Same as above

Risk Potential (Polygons)
1. Same as above
2.  "Type" options should be 'Infrastructure', 'Crop/Pasture' and ability to type in custom (if possible) if not add 'Other'. This attribute should be optional.
3. Same as above

**Comment by KellyMWhitehead** [comment]
Version 0.9 The new fields have been added, and was able to incorporate the ability for users to input custom text (or select from the drop down).

@Jdgilby Label changes will need to be made in the qml files. Make the necessary changes to the layer to apply the labels, and when you export the new qml, make sure "labels" is also checked.

![Image](https://github.com/user-attachments/assets/24edb9ea-2489-43e0-9f71-315d0e0d1dac)

**Comment by joewheaton** [comment]
@Jdgilby close when you are satisfied this is imple,mented, and reassign to @KellyMWhitehead if they need more work.

@philipbaileynar and @Jdgilby and I missed these in our roundup of 1.0 release tasks. I am assigning this to [1.0](https://github.com/Riverscapes/QRiS/milestone/3), if it is unrealistic, you can move this to [1.1](https://github.com/Riverscapes/QRiS/milestone/4).

**Comment by Jdgilby** [comment]
@joewheaton I forgot labels, Ill add this to the list of symbology changes to fix before 1.0
