### ISSUE TITLE
Overlapping check boxes on forms

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#468]
Ill keep a running list in this issue as I find them.
![image](https://github.com/user-attachments/assets/6092f295-991f-4ab8-99a1-a4c797412f35)
- [ ] Fix Add to map and Create Hillshade overlap in Import Surface Raster form

**Comment by KellyMWhitehead** [comment]
Moved some things around on this form for version 0.9. No more overlap.
