### ISSUE TITLE
Change date in Import Raster Form needs better usability

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#469]
![image](https://github.com/user-attachments/assets/8ead0d8d-decf-4a7a-b9f1-a2efd5dce27b)
You can backspace date but it wont let you type the date. The only way to type the date is to hit an up or down arrow first to get a date to populate. Then it will allow you to change it.

**Comment by KellyMWhitehead** [comment]
This was a little tricky, but I feel its working a little better now. When you click on the date and it currently reads 'No Date', it will update to the current date, allowing you to type in the new date. I also changed the widget to use the calendar popup, but can switch it back to the up/down if you want. Finally, added a 'Clear' button to clear the date back to "No Date".

![Image](https://github.com/user-attachments/assets/95c1c902-19e5-4008-aab5-bbd596e77c09)

Please close if this works for you.

**Comment by KellyMWhitehead** [comment]
@Jdgilby Give it a try and please close if this is satisfactory.
