### ISSUE TITLE
QRiS 0.0.0 Joe Test Drive

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#47]
Here's Joe trying this out
https://youtu.be/y80dI_Y6mkE
[![Video Link](http://img.youtube.com/vi/y80dI_Y6mkE/0.jpg)](https://youtu.be/y80dI_Y6mkE
 "")

@nick4rivers I added these from your thing below as if you add them in main first post on an issue, they a) get tracked as tasks in the issue, and b) make it easy to create sub-issues from.
ToDo's from Joe's review:

- [x] Remove QRiS from plugin title
- [x] Update version number to 0.01
- [x] Beware of MacOS extra files when zipping
- [x] Inhibit popup on drawing new project extent feature
- [x] Capitalize "n" on new QRiS project popup dialog
- [x] #63
- [x] Fix new extent dialog data entry. i.e., block out
- [x] Double check import and clip to extent
- [x] Total post calculation on the new structure type dialog can't handle 0 or blanks

**Comment by nick4rivers** [comment]
ToDo's from Joe's review:

- [ ] Remove QRiS from plugin title
- [ ] Update version number to 0.01
- [ ] Beware of MacOS extra files when zipping
- [ ] Capitalize "n" on new QRiS project popup dialog
- [ ] Remember layer tree state on adding a new layer
- [ ] Fix new extent dialog data entry. i.e., block out
- [ ] Double check import and clip to extent
- [ ] Total post calculation on the new structure type dialog can't handle 0 or blanks

**Comment by joewheaton** [comment]
@nick4rivers thanks for fixing the update version number. We will want to use the 0.00.00 convention and actually use this as 0.01.01. 

See: https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/Source_Code/#tag-your-releases
@MattReimer is trying to find post where he describes our standard for versioning releases. It is really good. I'll post here when he has it.

**Comment by MattReimer** [comment]
Yes except no zero padding `0.01.01` should be `0.1.1`

The verisoning strategy we use is called Semantic versioning. 
https://semver.org/

Check the FAQ on that page to answer a bunch of questions that come up a lot.

**Comment by nick4rivers** [comment]
Thanks guys I'll look into this.

@joewheaton I watched your video again and realized the clipping tool didn't work because you didn't first save your edits when you drew a new project extent feature.

**Comment by nick4rivers** [comment]
@joewheaton I went ahead and created issues for unresolved requests on this ticket and am going to close this out.
