### ISSUE TITLE
Cant import temporary layer into Sample Frame

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#471]
![image](https://github.com/user-attachments/assets/7207a9bf-18ab-48ef-ac5a-3c572f6f4de9)

**Comment by KellyMWhitehead** [comment]
Fixed 0.9.1

**Comment by joewheaton** [comment]
@Jdgilby close if you are satisfied, and reassign to @KellyMWhitehead if they need more work.

@philipbaileynar and @Jdgilby and I missed these in our roundup of 1.0 release tasks. I am assigning this to [1.0](https://github.com/Riverscapes/QRiS/milestone/3), if it is unrealistic, you can move this to [1.1](https://github.com/Riverscapes/QRiS/milestone/4).

**Comment by Jdgilby** [comment]
@KellyMWhitehead I no longer get an error, but nothing happens. No import.

**Comment by KellyMWhitehead** [comment]
I created a new issue (lucky #500) to track the new error. 
Closing this since the original error has been resolved.
