### ISSUE TITLE
Error importing existing profiles when using mask/AOI clip

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#472]
No issue when importing without mask/AOI clip selected. Error only occurs when trying to clip data to AOI. 
![image](https://github.com/user-attachments/assets/033f4bc3-c25b-4c15-95fe-941597c67e24)

**Comment by KellyMWhitehead** [comment]
Had a check to make sure the area of the output feature is greater than 0.0. Does not apply to lines! Fixed for 0.9.6.
