### ISSUE TITLE
Changes to Planning Container in DCE

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#473]
This is the next step from #391 
DRAFT
## What we Have
Currently, you have a `Add New Planning Event` node under `Data Capture Events` → `Low-Tech Process-Based Restoration`. This is good.
![image](https://github.com/user-attachments/assets/264d07cb-7812-4695-b3c7-2e5d99c458ce)

This brings up a `Create New Planning Event` Dialog
![image](https://github.com/user-attachments/assets/7f964f3e-8909-4034-bdca-bd7f1198c572)

This event type, on creation only allows adding of the "Planning" layers of Recovery Potential and Risk Potential.  

## What we Need

We need a way of organizing in the tree multiple DCEs to define a planning event.  We simply need to expose the planning layers of recovery potential and risk potential in normal DCEs. We DO NOT need a planning specific DCE. Within a Planning Container, we have the option of associating regular DCEs with it. A typical LTPBR Planning exercise as defined in manual, includes at least two but potentially three associated DCEs. The two are `Current` and `Historic` _Representation_ DCEs (controlled in Basic Properties tab of DCE). An optional third is a `Future`. It allows us to control the display in the tree of DCEs where those DCEs can exist on their own (and be sorted) at first level in tree, and/or duplicated and referenced and accessed under a planning container node.  

### How we will use it
We use it to organize and provide access to planning events that took place for LTPBR, typically prior to doing design. 

## Changes
- [x] Change  `Add New Planning Event` to `Add New Planning Container`
- [x] Move the current Planning Layers (Recovery Potential, Risk Potential (point, line, polygon), to be available in any DCE for 'LTPBR BASE` Protocol
- [x] New Table called plans with id and name and attributes of  which DCEs and their 
- [x] Store new key 'planID' optionally in DCEs  (multiple plans can reference as many DCEs as you want, DCEs can have multiple planIDs).
- [x] Modify Planning Form to allow list of DCEs in table and show whether they are `Current` and `Historic` and/or `Future` _Representations_  (allow as many as they want)
- [x] #482

**Comment by KellyMWhitehead** [comment]
@joewheaton, @Jdgilby Please confirm the following tabs:

Basic Properties
![Image](https://github.com/user-attachments/assets/e25ea86d-c21b-4fa2-a1da-fa30af57b462)

- Remove Valley Bottom, Event Completed at, and representation?
- Keep the date picker?
- Anything missing?

Associated Events
![Image](https://github.com/user-attachments/assets/96ed4aa8-5c96-43cb-a644-a97933d523e0)

- This is filtered to DCE's only. Include designs or AsBuilts?
- The data column is a little clunky for missing dates, I will work on this.
- Type column should include DCE,  AsBuilt, Design etc. Might not be needed if only DCE's are used.
- Phase column determines if a DCE is included, and what phase (use a different term?)
- There are currently no checks limiting the number of phases, or making sure there is at least one of each type. Do we need this functionality?

Other
- The Description and Metadata tabs function as usual.
- I will probably remove the add new layers to map checkbox at the bottom.

Project Tree
![Image](https://github.com/user-attachments/assets/d2436d7e-1afb-4721-9b76-bb791df5df80)

- Added to the bottom of DCE's. We can add sorting/grouping to this.

Right Click Menu
![Image](https://github.com/user-attachments/assets/5dfd3550-cff8-40ce-8d80-cf73220061f1)

- Additions or removals to this?

Any glaring omissions? I am currently testing and should be close to release once these comments are addressed. Thanks!
