### ISSUE TITLE
Don't collapse Data Capture Events node on project tree after every 'Add DCE' event 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#474]
The behavior of the tree is really annoying in that when a new Data Capture Event is added to the tree, it collapses the DCE node. Please leave it in previous state and make cursor focus the new DCE node added to the tree.

**Comment by KellyMWhitehead** [comment]
Behavior is changed for version 0.9. Let me know if this persists, or close ticket if verified.

**Comment by joewheaton** [comment]
Nice one @KellyMWhitehead. Appears to be working really well.
