### ISSUE TITLE
Metric calculations for Riverscape Length and Riverscape Area

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#478]
Right now Length is done in the background for calculations like sinuosity and for normalizing other metrics like density. Area is being done in the background on sample frames for proportion calculations. We want these as base metrics. @KellyMWhitehead Please advise if this is something we should now right a JSON for and how. If not we need to make sure it exposed in the metrics it is a part of.

**Comment by KellyMWhitehead** [comment]
I have added Riverscape Length and Area to the metric functions (v0.9.1):

1) Centerline, Valley Bottom and DEM can now be optionally specified when creating an Analysis. For now, you cannot add or select a different one once you have created the analysis (just create a new analysis). Will revisit this in the near future once the implications are better understood.
2) In the metric JSON, if you would like to specify one of these layers use the following (the rest of the JSON is the same):
```
    "metric_params": {
        "layers": [
            {
                "layer_name": "valley_bottom",
                "layer_source": "inputs"
            }
        ]
    }
```
for centerlines:
```
"metric_params": {
        "layers": [
            {
                "layer_name": "centerline",
                "layer_source": "inputs"
            }
        ]
    }
```
3) I have attached the metric json files I used for testing. @Jdgilby please take a look and modify/change description as needed. Note these will not work until you have QRiS version 0.9.1 installed.

[riverscape_area.json](https://github.com/user-attachments/files/16820338/riverscape_area.json)
[riverscape_length.json](https://github.com/user-attachments/files/16820339/riverscape_length.json)

**Comment by joewheaton** [comment]
@Jdgilby please test and report back. If good, close. If not, reassign to @KellyMWhitehead  with directions.

**Comment by Jdgilby** [comment]
@KellyMWhitehead I cant get Riverscape Length to work, seems to be an issue with the layer input. I need to get this sorted out ASAP to verify other metrics.

**Comment by Jdgilby** [comment]
@KellyMWhitehead Just to clarify, I have figured out it does work if JSON is written as "units": "". Riverscape Length and Area are defaulting to calculating in meters and sq meters off of the valley bottom in the riverscapes node. If "units" is filled in the metric fails to load into the project.

**Comment by Jdgilby** [comment]
@KellyMWhitehead Im going to close this issue since these are working, I am going to open a new ticket regarding units and unit conversions.
