### ISSUE TITLE
DCE and Planning Container Tasks

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRiS#479]
Data Capture events form:
- [x] Add to Basic Properties Tab: Date Label textbox (for labeling tables
- [x] Remove from Basic Properties Tab: Representation combobox

Planning Container
- [x] Drop Basic Properties Tab
- [x] Plus/Minus dialog for adding removing DCE's. Only show DCE's in the list that are part of the container. 
- [x] Change Phase to Representation (Optional, could be None). Contemporary, Predicted, Historic
- [x] Move Representation to a system metadata?
- [x] Reference the lkp_Representation table for labels. Update with new terms.

**Comment by KellyMWhitehead** [comment]
These enhancements are added for 0.9

**Comment by joewheaton** [comment]
@KellyMWhitehead this seems to be working nicely from what I can tell. @Jdgilby reopen or create specific new issues if you find problems.
