### ISSUE TITLE
Bulk edit feature attributes

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#480]
@Jdgilby requested that the three feature class architecture limits feature editing to the form view. This precludes selecting multiple features and applying an edit to all the selected features.

Here's a workaround:

1. User adds DCE layer to map and selects the features they want to edit.
2. Add a right click "Bulk Edit Attributes for Selected Features" menu item to DCE layers in the map TOC.
3. Pops up a form that is custom to the layer the user just clicked on. Single control that is dropbox listing the DCE attributes. User picks the attribute they want to edit.
4. Form closes and a new form opens with a single control where the user enters the value they want. (This form will be dynamic based on the field type that they are edting - string or float.)
5. User clicks OK and edits are applied to all selected features.

Not at smooth as traditional table bulk editing. But might make life a bit easier.

Thoughts @Jdgilby @KellyMWhitehead ?

**Comment by KellyMWhitehead** [comment]
added to version 1.0.2

1) User selects desired features to edit in map or by expression.

2) Right click menu in the Table of Contents on a DCE layer:
![Image](https://github.com/user-attachments/assets/e5f6399e-424d-4d28-b8a7-c0f5138b6eab)

3) New Form pops up that allows user to select a field. The value drop down or text box then appears, user selects or types in desired value. And clicks apply to commit the changes.

![Image](https://github.com/user-attachments/assets/c10575bc-b456-4008-ba80-3821497319db)

User can also make selections in the attribute table that appears on the form. User can also show only selected features or view all features.
