### ISSUE TITLE
Changes on Basis for Design tab (Design Properties)

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/QRiS#482]
Motivation: Add an optional drop down in design under `Bases for Design` tab to add DCEs by a planning collection instead of separately for each.

1) Change the drop downs to use the EventLibrary widget
2) save and load these to design metadata
3) Allow user to add remove events using individual dces
4) Allow user to add remove events based on a planning container (would this lock down user options then?)

**Comment by KellyMWhitehead** [comment]
@joewheaton @Jdgilby Making updates to the design form to incorporate referencing DCE's via the Planning Containers. Users can either
1) Select DCE's manually using the same widget that Planning Container uses. Users can specify any number of DCE's and set representation to None, Historic, Contemporary, Predicted.

![Image](https://github.com/user-attachments/assets/cd729f46-2394-4959-93d9-92e511e86f2e)

2) Under the drop down, users could instead choose an existing Planning Container. This will then populate the table with DCE's based on the Planning Container. The table is then locked down, unless a user selects a different Planning Container or chooses the Manual Selection option again. If a user later makes changes to the Planning Container, those changes are made to the Design (in fact under the hood, I only store the planning container id, unless it is a Manual selection, then I store the individual Events)

![Image](https://github.com/user-attachments/assets/b126746f-f1f4-498f-9a69-2c14597b97a6)

3) This is my real question: Do we need/want the surfaces table in this form (red box)? I add a better label if we want to keep it, otherwise I will disable and hide it for Designs.

![Image](https://github.com/user-attachments/assets/9a558914-65f5-4879-8d32-10e3868abfc0)


Sorry for all the details - I want to be clear as to how currently have this set up. Please let me know if this is on track, or if changes are needed. Thanks!

**Comment by KellyMWhitehead** [comment]
These changes are included in 0.9.1. Have a play, let me know if further changes are needed.

**Comment by joewheaton** [comment]
Looks good. We will run with this and if we need to tweak, we can do that post 1.0. Nice work.
