### ISSUE TITLE
Error importing temporary layers

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#484]
This is happening in Design points, haven't tested if its happening everywhere. This is the error
![image](https://github.com/user-attachments/assets/24a3f39c-d169-49dd-a432-46a78ec58b5a)
Uploading of existing feature class does however work

**Comment by joewheaton** [comment]
@Jdgilby is this still happening in 0.9.3?

**Comment by Jdgilby** [comment]
@joewheaton Not happening anymore, closing for now.
