### ISSUE TITLE
Failure importing Vectors from Riverscapes Viewer projects

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#486]
Version 0.9.1 is failing to import vector features from a Riverscapes Viewer project. Rasters are importing fine. 
The only error I'm getting is   "CRITICAL    Feature Class Copy Error : Review the QGIS log." But nothing else, cant find anything on any of the other Log Messages tab.

**Comment by Jdgilby** [comment]
@KellyMWhitehead It was an issue with the AOI being multipart. You can close this if you don't think we need to address that. I think there should be some sort of warning or message when this happens at a minimum though.

**Comment by joewheaton** [comment]
@Jdgilby close if you are satisfied, and reassign to @KellyMWhitehead if they need more work.

@philipbaileynar and @Jdgilby and I missed these in our roundup of 1.0 release tasks. I am assigning this to [1.0](https://github.com/Riverscapes/QRiS/milestone/3), if it is unrealistic, you can move this to [1.1](https://github.com/Riverscapes/QRiS/milestone/4).

**Comment by Jdgilby** [comment]
@joewheaton It has been fixed, if it happens again I'll open a new ticket.
