### ISSUE TITLE
Add these Right Click Commands to QRiS Project Folder

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#49]
The current QRiS Right-Click Context Menu has one command - `Expand All Child Nodes`. 
![image](https://user-images.githubusercontent.com/9723905/148435111-106f50df-3eab-4594-9946-114d77b03633.png)

We should update it to include a similar feel and functionality to QRAVE:
![image](https://user-images.githubusercontent.com/9723905/148435069-4e32d39a-460d-4743-990d-0c7039639dbb.png)

Please add using the code from QRAVE as example:

- [x] Add right-click command for Project `Collapse All Child Nodes`
- [x] Add right-click command for Project `Browse Project Folder`
- [x] #60
- [x] Add right-click command for Project `Add All Layers to the Map`
- [ ] Add right-click command for Project `Add Refresh Project Hierarchy`

Someday later we can talk about adding other functionality for exporting project, uploading to warehouse and other things.

**Comment by KellyMWhitehead** [comment]
All the menus have been implemented except for "Refresh Project Tree". QRiS already self-updates the project tree when items are added.
