### ISSUE TITLE
Fix "Import and clip a new project layer" bug when loading from Riverscapes Project

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#50]
![image](https://user-images.githubusercontent.com/9723905/148437342-45892f95-24a1-49da-9e5a-478cfca8ad2b.png)

As shown in video in #47, I could not successfully import and clip a polyline feature-class from a BRAT riverscapes project. We need to investigate if this is a workflow thing where a workaround is needed, or a bug or if we relate this to the need to load a layer from an existing riverscapes project.

**Comment by nick4rivers** [comment]
@joewheaton I'm pretty certain this is because you didn't save your edits when creating a new polygon.

**Comment by joewheaton** [comment]
@nick4rivers that was exactly the problem. This is solved. However, we'll want to think about both documentation and warnings or helper tips we can use to avoid someone doing same thing. 

One thought is a try / catch where on loading, you check to see if it is in an edit session. If it is catch and throw exception with warning telling user you can't do that until it is saved.

Also check and see if they share geometry.
