### ISSUE TITLE
Sample Frame Issues

### ISSUE THREAD

**Issue by Jdgilby** [Riverscapes/QRiS#506]
1. Create new sample frame- Empty feature class is not available to edit until closing and reopening the project
2. Create new from QRIS features- no feature class created. No error.
3. Import from temporary layer- only works if there are no fields from QRIS. 
   -to elaborate if I take a layer from QRIS export as temporary layer and try and import into SF it fails giving the issue mentioned in 
     #500, if I delete all the fields the import is successful.
   -if i create a new temporary scratch layer and import that it is successful

**Comment by KellyMWhitehead** [comment]
1 and 2 are fixed for 1.0.0.  Punting on # 3 for now since I am unable to reproduce.
