### ISSUE TITLE
Add "Import and clip a layer  from a Riverscapes Project" 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#52]
Similar to #50
![image](https://user-images.githubusercontent.com/9723905/148437257-99aaba0a-acb4-4a71-bce9-ed6fa7bc946b.png)

We know we want the ability to do the same thing but for a specific layer in a specific riverscapes project:
- [ ] We need to have a dialog for opening that doesn't just navigate on disc, but navigates to load a `project.rs.xml` project file using the tree explorer from QRAVE. 
- [ ] It allows the selection of a specific layer in the riverscapes tree (controlled by business logic)
- [ ] It adds to map and clip to map the same way the existing import tool works, but that it leverages the RiverscapesXML project type curation to add it with the correct symbology, label, definition query, etc..
- [ ] It records in `*.QRS` project geopackage the GUID, Project Name, and Project Type  of Riverscape Project it came from, as well as GUID and layer name/type of layer chosen. 
- [ ] We add to right click context menus for Basemaps and Scratch layers that were imported in this way the same `View Layer MetaData` command, 

![image](https://user-images.githubusercontent.com/9723905/197340151-c5dc7ce3-7c85-48e2-afb1-43c8a1e7b931.png)
which brings up both the Layer MetaData:
![image](https://user-images.githubusercontent.com/9723905/197340185-891bf6cd-2d79-496d-941a-3315db19c4e4.png)
but also the Project Metadata from which it came:
![image](https://user-images.githubusercontent.com/9723905/197340429-aec86f9b-2eab-4883-a758-a549b43dfe8d.png)

- [ ] We also add the `View in Warehouse` button to the right-click context for that layer once it has those metadata tags. 

![image](https://user-images.githubusercontent.com/9723905/197340282-dc42794c-6048-43f1-81c5-586222d88663.png)

**Comment by joewheaton** [comment]
We really want this, but we should probably have you @nick4rivers scope this with the help of @philipbaileynar first, and then we can assign when we can realistically get to it and / or if it is something either NAR does, or NAR helps you with.

**Comment by philipbaileynar** [comment]
The ability to import from QRAVE projects was implemented as a cleaner way of bringing into existing layers.

The current implementation doesn't bring in metadata so I moved that feature to #206.
