### ISSUE TITLE
QRiS Projects Won't Open With V 1.0.2

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#522]
I tried to open a few QRiS projects in QGIS and kept getting this error. Plus the plugin viewer wasn't displaying as it normally does when a QRiS project is opened within a qgz file. 

![Screenshot 2024-10-25 084621](https://github.com/user-attachments/assets/a9ce26df-c2d2-4a3b-87fd-74f567502a18)

**Comment by KellyMWhitehead** [comment]
This is a QGiS version issue. Technically you need version 3.32+ (but seemed to work for me in 3.28.15).

I will put out a hotfix for version 1.0.3 that will catch this error for lower versions of QGiS, however the Batch Attribute Editor will not be available.
