### ISSUE TITLE
Change "Watershed Catchments" to "Catchment Delineation(s)" and add layer group when adding to map

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#527]
![image](https://github.com/user-attachments/assets/10328f3f-520f-4762-8ed3-b94331d680e3)

"Watershed Catchments" is redundant. These are "Catchment Delineations", so lets 
- [ ] change the label in the Context in QRiS tree to "Catchment Delineation(s)" and 
- [ ] make sure to add that organization into the tree. 

For projects with lots of these (more common than you might think), this is useful to turn them all off at once.

**Comment by KellyMWhitehead** [comment]
version 1.0.4
