### ISSUE TITLE
Can't Import Layers from Riverscapes Viewer into QRiS

### ISSUE THREAD

**Issue by zburgert1997** [Riverscapes/QRiS#528]
I have been trying to import layers from the riverscape viewer into QRiS by using the "Add To QRiS" funtion but keep getting this error. 

![Screenshot 2024-10-31 210911](https://github.com/user-attachments/assets/2f807a98-b4db-4127-9d6e-03412b21f40b)

**Comment by KellyMWhitehead** [comment]
This is fixed in 1.0.4
