### ISSUE TITLE
Move Structure Types Library to a Settings Dialog & Add Default

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#54]
Like we discussed @nick4rivers on GCD, the "Structure Types" doesn't make sense under the Low-Tech Designs (i.e. as an attribute of just that project). You don't want users having to do this every time. It makes more sense as a "Structure Types Library" in a new Settings Command from a pull down in toolbar, and the user can customize it (saved in their own AppData folder as a text file or XML). Please discuss with @philipbaileynar strategies for this and whether we want to treat it like the FIS library tied to a repo users can contribute to.  

![image](https://user-images.githubusercontent.com/9723905/148444320-b3ca9f55-412e-49e7-8cc8-1fef96d304a5.png)

**Comment by nick4rivers** [comment]
Moving this to a different milestone as it needs to be discussed after the data structure for an ltpbr design stabalizes.
