### ISSUE TITLE
Suggested Modifications to Structure Type dialog and attributes

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#55]
I really like the idea of a "Structure Type Library" (see #54). This is what we currently have now:
![image](https://user-images.githubusercontent.com/9723905/148445803-cc4c47fa-ea60-41b2-ad96-b28845765114.png)

## Structure Type Name
@nick4rivers can you elaborate what was defined by default in the FMLTPBR (§ [3.1.3](https://fmltpbr.riverscapes.xyz/))?  I see you had structure type name,

![image](https://user-images.githubusercontent.com/9723905/148445128-6b55a322-486c-42de-80b1-9a0bfa097311.png)
I really don't like that "Structure Type Name" is user-defined. I'm fine with it being user-customized, but we will never be able to summarize if we don't use something that suggests the most common ones.
### Suggested tweaks/additions to structure types
I think we're best to go back to Manual and literature and have at least two tiers of structure definitions in Appendix C Chapter 1:

Default list:
- `BDA (beaver dam analogue)`
- `PALS (post assisted log structure)
- `ALS` (assisted log structure - postless)
- `ORD  (one rock dam)`
- `Tree Plug`
- `Post and Brush Plug`
- `Wicker Wiers`
- `Zuni Bowl`
- `Other`
I would suggest that a default construction description and function description and posts go with this.

We should also remind ourselves about this:
![image](https://user-images.githubusercontent.com/9723905/148447377-9f71adb4-02b9-4745-8e82-b5eafbf8606f.png)
and
![image](https://user-images.githubusercontent.com/9723905/148447102-8cc86b3b-55ee-46ca-8437-3ce86dc6b057.png)
from Wheaton et al. 2015 Fluvial Taxonomy.

We might want to just point out in this library what these correspond to. For example a BDA at tier 1 is Anthopogenic, at tier 2 is a BDA.

I think the "tier 3" attributes, should be what we add as optional attributes to each structure as it is placed.

## Structure Mimics
Choices are now:

-  `Beaver Dam`, 
-  `Woody Debris`
- `Other`

I like these, but it should be one of the "customizable" fields in the library. I would also add `Rhizomatous Root Mat`

## Structure dimensions and posts
I like all this stuff, but I think it should be a separate feature that it is clearly used for quantity estimation as opposed to part of the structure definitions. This would make more sense to have in the in the Design part of tree where `Structure Type` currently is but rename as `Structure Building Material Estimation`. It could have some defaults associated with typical structures.

**Comment by joewheaton** [comment]
See also #59.

**Comment by joewheaton** [comment]
Agreed with @nick4rivers:
![image](https://user-images.githubusercontent.com/9723905/148599278-1960e3fd-8677-41e1-b6ae-eb1d7673f857.png)

**Comment by joewheaton** [comment]
Add a tab control for  `Key Attributes`, for the above Taxonomy stuff.  These are optional.

**Comment by nick4rivers** [comment]
Again, we should come back to reference, but at this point the attributes for structures will consist of simple dimensions and an estimate of posts. More thought is needed about the structure of designs and what summary information we need in the future.

**Comment by joewheaton** [comment]
This is incorporated into LTPBR V2 and 0.3.6
