### ISSUE TITLE
Tweaks to ZOI workflow and attributes

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#56]
I really like how when you edit a ZOI and add a new polygon, the dialog brings up whether or not that ZOI is associated with a complex or structure (i.e. through ZOI Type, which can be `complex` or `structure`):
![image](https://user-images.githubusercontent.com/9723905/148449313-cdcf3830-5739-494d-8633-754526d2d046.png)

I think we should allow multiple ZOIs feature classes (not just features) each associated with a predicted event. This would be a property of the ZOI metadata, and ZOIs would be nested in a subfolder under designs. Each ZOI would have a name, and ZOI_event - 'Baseflow`, `Typical Flood`, `Rare Flood` and `Other`. Typically we would only do one ZOI in a design representing typical floods as this is our SoP minimum, but it is possible to do others. We may also consider controlling structure vs. complex at this level too?
- [x] Allow multiple ZOI feature classes for each design

####  ZOI InfluenceType
I think we may at some point consider adding a new attribute field, which is describing `Influence Type` and has its own customizable library, but in our case would default to following influences:
- `Backwater Pond`
- `Overflow`
- `Constriction Jet`
- `Lateral Erosion`
- `Eddy`
- `Deposition Zone`
- 
The influences are categorical, and multiple can be "selected" for any zone.
- [x] Add ZOI attribute field of `Influence Type(s)`

**Comment by nick4rivers** [comment]
@joewheaton - remember, I am trying to rely on the native to QGIS editing and form functionality for feature editing and creation of things like ZOIs. There is not built in tool for selection of multiple values for single attribute. e.g., I can't allow selection of multiple `ZOI_influence_type` values. To get around this I may just go default to `dominate_ZOI_influence` and only allow one selection.  Allowing multiple selection types is also extremely difficult to efficiently summarize anyway.

**Comment by nick4rivers** [comment]
@joewheaton I would think that `constriction jet` and `lateral erosion` are the same thing? Are these redundant?


> 
> * `Backwater Pond`
> * `Overflow`
> * `Constriction Jet`
> * `Lateral Erosion`
> * `Eddy`
> * `Deposition Zone`
>

**Comment by nick4rivers** [comment]
@joewheaton  - This many relationships would be very cumbersome to implement within the plugin framework we are working with, especially given the constraint of supporting the native QGIS editing tools. Would it be possible to store `zoi_stage` and `structure` vs `complex` as zoi attributes.

> 
> I think we should allow multiple ZOIs feature classes (not just features) each associated with a predicted event. This would be a property of the ZOI metadata, and ZOIs would be nested in a subfolder under designs. Each ZOI would have a name, and ZOI_event - 'Baseflow`, `Typical Flood`, `Rare Flood`and`Other`. Typically we would only do one ZOI in a design representing typical floods as this is our SoP minimum, but it is possible to do others. We may also consider controlling structure vs. complex at this level too?
>

**Comment by joewheaton** [comment]
> @joewheaton I would think that `constriction jet` and `lateral erosion` are the same thing? Are these redundant?
> 
> > * `Backwater Pond`
> > * `Overflow`
> > * `Constriction Jet`
> > * `Lateral Erosion`
> > * `Eddy`
> > * `Deposition Zone`

Sorry for slow response @nick4rivers. No they are two different things.  This is why we use the same margin attached PALS or ALS in different contexts as both a [bank blaster](https://figshare.com/articles/figure/LTPBR_Manual_-_Chapter_4_-_Appendix_D_-_Typical_Schematics_of_PALS/14445564/1?file=27630015) (i.e. lateral erosion where banks are erodible), and [pool-maker for constriction jets](https://figshare.com/articles/figure/LTPBR_Manual_-_Chapter_4_-_Appendix_D_-_Typical_Schematics_of_PALS/14445564/1?file=27630012) (where banks are resistant).

**Comment by joewheaton** [comment]
> @joewheaton - This many relationships would be very cumbersome to implement within the plugin framework we are working with, especially given the constraint of supporting the native QGIS editing tools. Would it be possible to store `zoi_stage` and `structure` vs `complex` as zoi attributes.
> 
> > I think we should allow multiple ZOIs feature classes (not just features) each associated with a predicted event. This would be a property of the ZOI metadata, and ZOIs would be nested in a subfolder under designs. Each ZOI would have a name, and ZOI_event - 'Baseflow`, `Typical Flood`, `Rare Flood`and`Other`. Typically we would only do one ZOI in a design representing typical floods as this is our SoP minimum, but it is possible to do others. We may also consider controlling structure vs. complex at this level too?

Again @nick4rivers sorry for slow reply, but can we talk to @philipbaileynar about this. I'm sure there are some ways we could allow multiple things selected (seems pretty fundamental), that don't kill us.

**Comment by nick4rivers** [comment]
@philipbaileynar and @joewheaton this kind of issue is pretty fundamental, but i'm already running into issues trying to summarize data based on overlapping geometry within the same feature classes. I think we can find a solution, but it's not a simple one.
