### ISSUE TITLE
Additional Attributes of Designs and Control

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#57]
Right now these are the Design Dialog for creating a new dialog.
![image](https://user-images.githubusercontent.com/9723905/148447852-ed841151-6f9a-48df-8b94-c9c1aee5bbd2.png)

First, we need to:
- [ ] Add a new right click command on a Design to "View and/or Edit Design Properties", which brings up the same dialog again and allows tweaking of it. 

## Design Name
This is fine.

## Design Source
Currently, options are `desktop` or `field`. 
- [x] Please capitalize first letters of `Design Source` options to `Desktop` or `Field`. 

This currently means that the 'structures' added to project are either named 'Field Structures' and of type point or 'Desktop Structures' and of type polyline. I don't like this. If we add the tree ability, creating a design simply creates an empty container with the metadata in this form (see #53 ). Lets add the following right click commands to the designs in the project tree:
- [x] Add right click command to all designs in tree: `Add Structures (points)`
- [x] Add right click command to all designs in tree: `Add Structures (polyline crests)`
- [x] Add right click command to all designs in tree: `Add Zone of Influence (ZOI)` 
- [ ] #67

- [x] Lets make the choice of whether those are points or crests explicit in the design commands proposed above. 
- [ ] Make the choice of Design Source as 'field' or 'desktop' or 'hybrid' as a property of the structures when structures are created.

## New Design Attributes
We'll convert these to tasks and/or other issues when we discuss.
### Design Period
Using the time class we talked about from GCD, allow 
### Phased Design?
Ask if this is part of a phased design.

- `No`
- `Pilot - full phase(s) anticipated later`
- `First Phase - later phase(s) anticipated`
- `Next Phase`
- `Final Phase`

### Design Phase
If Phased Design is not `No`, enable a text entry for describing this phase.

**Comment by nick4rivers** [comment]
@joewheaton is this the place to add designer name, organization, and emails. It seems like this should go in a setting or something and maybe not be specific to a design. However, it is fine to add it here and I could put this information on an optional tab in the design dialog?

**Comment by nick4rivers** [comment]
@joewheaton I really don't like these choices to describe phases. Phases need to be more flexible, contain a date range, and could be anywhere from _pilot_ to phase _n_. I don't see the reason to limit the choice of phase to just pilot, first, next, and final?

> * `No`
> * `Pilot - full phase(s) anticipated later`
> * `First Phase - later phase(s) anticipated`
> * `Next Phase`
> * `Final Phase`
> 
> ### Design Phase
> If Phased Design is not `No`, enable a text entry for describing this phase.

**Comment by nick4rivers** [comment]
Closing with some details such as right click commands adding individual items to the tree in #67
