### ISSUE TITLE
Add a Complex Footprint Feature Class to Designs

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#58]
Please add the discussed polygon (optional) 'Complex Footprint(s)' feature class as an 'Add to Design' option. This will be:
- Type of feature polygon
- Be where you map just the construction footprint of structures and draw a polygon around structures (points or polylines). 
- Be where you record the complex name
- Assign unique complex ID
- Record `Complex Description`
![image](https://user-images.githubusercontent.com/9723905/148451887-e2ff3251-0f80-412c-8955-24bbfaef135e.png)
- Record 'Complex Narrative'
- Record 'Current Condition'
- Record 'Anticipated condition`
- Area
- Length? (divide area by riverscape segment length)?
- Derive and specify or adjust Structure type and counts including +/-

We will need a command:
- [ ] #65

This will populate a table of structure type, counts and +/- and totals, that the user can override (i.e. unlink to geometry) if dervied from mapping of structures, or manually populate without any structure feature classes.

Lets hold true to supporting creation of this:
![image](https://user-images.githubusercontent.com/9723905/148452722-26562669-317c-460e-95e9-b84bce77218c.png)

This needs to be done for EACH complex. So this is the place we do that. It may be more of it in database than as an attribute field in polygon geometry, but we need to do this.

**Comment by nick4rivers** [comment]
@joewheaton we will need to discuss how this polygon will be different from #56

**Comment by nick4rivers** [comment]
Closing this issue after adding the adding and editing of complex and associated attributes. The summary functionality has been moved to a separate issue #65
