### ISSUE TITLE
Additional Structure Attributes for Designs

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#59]
Right now, the structure design dialog for each structure exposes:
![image](https://user-images.githubusercontent.com/9723905/148452889-8f108f69-341e-464f-9e7a-53def4a98d25.png)

I like that you can override which design it is tied to (presumably currently controlled from most recently used or added?) I also like that you choose your structure type (see changes to "structure type library" in #55).  I also like the option to have a structure description. 

I like that there is a structure length that calculated for polylines. This goes away for points and that makes sense:
![image](https://user-images.githubusercontent.com/9723905/148453122-14d293e4-6dbf-4a29-b9b7-a456ec9f6b31.png)

- [x] Update labels for fields on Field Structures form  to nice readable labels instead of field names.

For me, what's missing are two things: 1) optional key attributes of structural elements from Fluvial Taxonomy; and 2) the choices about structure types used for material estimation.  

## Adding optional key attributes of structural elements from Fluvial Taxonomy
This should be based on:
![image](https://user-images.githubusercontent.com/9723905/148453376-1880561f-075b-4275-8f3d-8958c8e98a17.png)
and the five attributes are in column 1 with their default choices (add other to each) in Types column 2:
![image](https://user-images.githubusercontent.com/9723905/148453480-5dade0ed-da18-47d6-b832-69bcd11b18c2.png)

No one has to populate these for every structure, but they can. We can also create a default population for many of these (not all) and allow user to over-ride (e.g. BDA 'Position' is always channel spanning). We can also do things like remember users last choice when they're in an edit session and making a new feature.

## Adding the choices about structure types used for material estimation

This is really about taking the cool stuff you have on post estimates and volume estimates and exposing that in a simple way so it can attempt to populate/estimate for each structure based on geometry of polyline, and structure type, but can be over-riden.  This seems to be best done its own special command (not prompted for each structure as making structure).

**Comment by nick4rivers** [comment]
@joewheaton I'm adding the above structural attributes. The list of structure types is will also be updated to the list you gave in #55

**Comment by nick4rivers** [comment]
Moving this to another milestone. Many of these more specific attributes of individual structures will be added after the overall data structure for ltpbr design becomes more stable.
