### ISSUE TITLE
Remember layer tree state on adding a new layer

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#63]

**Comment by nick4rivers** [comment]
@MattReimer i'm kind of at a loss for how I would go about remembering the expanded vs. collapsed state for items in a the tree so that when new layers are added or deleted we don't just completely collapse the tree.

![Screen Shot 2022-01-07 at 2 58 29 PM](https://user-images.githubusercontent.com/34071692/148617910-8d41f4f5-5362-4e5e-bdc4-e918315e1d44.png)

vs.


![Screen Shot 2022-01-07 at 2 58 47 PM](https://user-images.githubusercontent.com/34071692/148617915-43a955e8-2779-494d-9896-77b15a01d9f1.png)

**Comment by joewheaton** [comment]
This was a similar issue in QRAVE: https://github.com/Riverscapes/QRAVEPlugin/issues/32, which @KellyMWhitehead fixed with: https://github.com/Riverscapes/QRAVEPlugin/commit/e8667b5baa7e6708bbd01df914264f62f221b842

I'll defer to @MattReimer and @philipbaileynar on best way to do this for you, but hint might be at:

**Comment by MattReimer** [comment]
Yeah, @KellyMWhitehead solved it in a really ellegant, recursive way here. There are definitely other ways you could approach this but I like what he came up with.

**Comment by nick4rivers** [comment]
Thanks for the reference.  It's gonna be a bit before I get back to this but this should really help.

**Comment by nick4rivers** [comment]
@philipbaileynar wanted to bring your attention to this issue with the QRiS tree. You can find the solution that Kelly wrote in his commit for QRAVE.

This also brought up the question of whether we should completely redraw or just add nodes when components of the tree change.

**Comment by philipbaileynar** [comment]
Just add nodes!!!!!!!!!
