### ISSUE TITLE
Create New Design Dialog

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#64]
Changes for the create new design dialogue:

1. Change dialog title to "Create New Design"
2. Drop the word "Design" before all the labels. It's implied.
3. Can we hide/disable the min/max buttons?
4. I don't like the label or the concept of the "design source" control. Leave for now.

<img width="521" alt="Screen Shot 2022-01-19 at 1 40 16 PM" src="https://user-images.githubusercontent.com/8645379/150218188-fb3a7c9f-92ae-41b8-a898-90624f4ff7d6.png">

FYI @nick4rivers  these are just some minor changes to get my feet wet.

**Comment by nick4rivers** [comment]
@philipbaileynar I see this and will add to an immediate milestone if not already there.

I don't like the new design source concept either, but I do feel like it's a pretty fundamental concept and something that practitioners will actually use and appreciate the distinction being front and center. We will discuss.

**Comment by nick4rivers** [comment]
THanks @philipbaileynar I made these changes. As for removing the minimize and maximize buttons for the dialog I created a new issue as it is gonna take a bit of research. See #66
