### ISSUE TITLE
Dialogs with no minimize and maximize buttons

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#66]
Can we create dialog windows with the minimize and maximize buttons disabled. This comes from suggestions to the create design dialog mentioned in #64

![Screen Shot 2022-01-26 at 11 22 46 AM](https://user-images.githubusercontent.com/34071692/151232049-2a77036f-d95d-4268-a222-9703059ba0c5.png)

**Comment by joewheaton** [comment]
I think @philipbaileynar has figured this out.
