### ISSUE TITLE
Summarizing Overlapping Geometry

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#68]
Hey @KellyMWhitehead and @philipbaileynar,

I've been writing up some queries to summarize information in QRiS and I'm having some trouble when trying to aggregate data when geometry overlaps.

<img width="579" alt="Screen Shot 2022-03-07 at 4 24 50 PM" src="https://user-images.githubusercontent.com/34071692/157142928-6fa680b5-4ba9-47af-8817-5809bcca4c54.png">

In this example I use the following code to try to count the number of restoration structures ('points') in complexes ('polygons). In this case however both the structures and complexes are part of different designs, and so the aggregate count should reflect that. This is pretty fundamental to a lot of the data summarization we need.

Here is the SQL I use to get the counts of structures within each complex:

```SELECT complexes.design_id AS Design_ID, complexes.fid AS Complex_ID, complexes.complex_name AS Complex_Name, COUNT(structure_points.fid) AS Structure_Count
FROM structure_points, complexes
WHERE st_contains(complexes.geom, structure_points.geom)
GROUP BY complexes.design_id, complexes.fid, complexes.complex_name
ORDER BY complexes.complex_name ASC;
```
<img width="421" alt="Screen Shot 2022-03-07 at 4 48 00 PM" src="https://user-images.githubusercontent.com/34071692/157143476-9a23f783-8db3-4fbf-84b3-a77590d490b0.png">

So what we need is a way to specify that the structures are specific to the complex geometry and also the design_id.

**Comment by philipbaileynar** [comment]
The answers you are getting are correct on a purely spatial relationship. You must have some other context in your head that is not expressed by the query. Is there an attribute relationship between the brown polygon and the brown points. And the blue polygon and the blue points?

**Comment by nick4rivers** [comment]
@philipbaileynar exactly. It's that the polygons and points belong to different 'designs'. So yes, an attribute relationship. Does that make sense.

So what I want is for the spatial function to recognize the attribute relationship, and then the spatial relationship.

This is the SQL route. We could also consider doing all of this by looping through our data by triggering a pythong script. I would however much rather go the SQL route if possible.

**Comment by philipbaileynar** [comment]
```sql
SELECT 
FROM structure_points p
    inner join complexes c on st_contains(c.geom, p.geom) AND (s.complex_id = p.complex_id)
GROUP BY c.design_id, c.fid, c.complex_name
ORDER BY c.complex_name ASC;
```

**Comment by nick4rivers** [comment]
@philipbaileynar thanks a ton. I'm realizing I didn't add my entire sql statement. Does this change your solution. I'm trying to work through it with a bit of trouble getting it to run.

Here again is my code that now includes the `SELECT` statement. Could you adapt this again to your solution:

```sql
SELECT complexes.design_id AS Design_ID, complexes.fid AS Complex_ID, complexes.complex_name AS Complex_Name, COUNT(structure_points.fid) AS Structure_Count
FROM structure_points, complexes
WHERE st_contains(complexes.geom, structure_points.geom)
GROUP BY complexes.design_id, complexes.fid, complexes.complex_name
ORDER BY complexes.complex_name ASC;
```
