### ISSUE TITLE
Polygon Surface Area Summary

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#7]
This is the first feature request for generation of summary information from the RIPT plugin output. In it's first iteration it will just be a tool to extract and package up disparate pieces of riverscape information and RIPT output into summary tables that are useful for describing restoration potential/valley bottom characteristics.

 - The feature will allow summarization of the valley bottom area below a specified elevation (i.e., output of the DEM slider feature from #6 ) for a discrete segment of a riverscape (i.e., reaches within a LTPBR design).
 - The feature will also calculate the area normalized to the length of the riverscape segment, where length is measured along the valley center.

![Example](https://user-images.githubusercontent.com/34071692/121091486-e7a45980-c79e-11eb-8b40-69f2fb671621.jpeg)

**_Required Inputs:_**

This RIPT processing feature requires the following three spatial data types:

 - _Elevation Polygon_ - Extracted polygon showing area under the elevation of interest or representative of a riverscape surface (e.g., active channel, active floodplain). In most cases this will be exported using the elevation slider tool from within RIPT.

 - _Segment / Reach Boundary Polygon_ - Polygon showing the area of interest. This polygon can consist of multiple features representing LTPBR design reaches, ownership boundaries, etc.... NOTE: this is actually the layer that will be clipped to the extent of the elevation polygon. Each feature in the segment layer should have an attribute called "name" - this is required.

 - _Valley Center Line_ - line along the valley center. This line will be clipped to the reach / segment boundary polygon to extract the length of each segment. Ultimately used to normalize the area under each elevation to reach / segment length.

**_Final Output_**
In this iteration, the final output of this feature will be kept to a single geopackage that contains individual layers for each extracted elevational polygon, as well as a single table that compiles the polygon areas. e.g.,:

![Screen Shot 2021-06-07 at 3 12 12 PM](https://user-images.githubusercontent.com/34071692/121094020-c80f3000-c7a2-11eb-90c2-ae61770e0727.png)

**_Summary Metrics_**
The final output table should contain a final summary metric that expresses the area of the valley bottom that is under an elevation normalized to valley length (i.e., area / length). The following table can be used as an example:

![Screen Shot 2021-06-07 at 3 13 29 PM](https://user-images.githubusercontent.com/34071692/121094246-2d632100-c7a3-11eb-98f7-0dab053a0fea.png)
Where:

 - _reaches_name_ - the name of each segment / reach as defined within the **_Reach Boundary Polygon_** input.
 - _elevation_ - the surface or elevation of the extracted polygon. i.e., 1m, or "active-floodplain".
 - _area_m/ac_ - area of the extracted polygon in square meters and acres.
 - _reach_length_m/mi_ - length of the reach from the center line.
 - _vb_area_m/ac - area_ of the input polygon for each reach/segment.
 - _summary_ac_per_mi_ - Area of each extracted polygon normalized to the valley segment length (i.e., area_ac / reach_length_mi)

@philipbaileynar and @KellyMWhitehead please don't hesitate to ask for additional information or clarification but I think this is a start.

**Comment by philipbaileynar** [comment]
@nick4rivers this looks really good. I'm sure we will have more questions when we dive in, but this captures what we need to get started. Thanks.

**Comment by nick4rivers** [comment]
@philipbaileynar - Yes @KellyMWhitehead should be asking questions - there are a lot of details here that I didn't fully get articulate.

Also, seems like I couldn't assign this ticket to anyone? Am I lacking some permissions in this repo?

**Comment by joewheaton** [comment]
> @nick4rivers this looks really good. I'm sure we will have more questions when we dive in, but this captures what we need to get started. Thanks.

Agreed @philipbaileynar, nice job @nick4rivers. I will have suggestions about where to go with this, but lets get it implemented as you spec'd out first. 

- [ ] @philipbaileynar, note that @nick4rivers has assigned this to @KellyMWhitehead. Can I ask you to provide direction as to whether or not that is correct, or if you and/or @KellyMWhitehead should split this into multiple tasks and some can be assigned to @nick4rivers with reference back to this one.
- [ ] I have assigned this to the Kern project for billing purposes for you all (including you @nick4rivers) - Check to acknowledge.
- [ ] I set some milestones (this one for now I called Alpha Release). @nick4rivers, these milestones are a dart board for now. You and I (and Steve and Buster) will need to discuss priorities.
- [ ] @nick4rivers in meantime, please create an issue referencing this one and assign to yourself and/or Chalese to work on getting symbology for Valley Centerline dialed (note we have centerline symbology in VBET and CHaMP to use as starting point).

**Comment by nick4rivers** [comment]
@joewheaton and @philipbaileynar  - when asking for "symbology" we need to think about how this is implemented in RIPT as opposed to RAVE? are we developing .qml's? or some other means as symbology in RIPT may be implemented in pyQGIS?

**Comment by joewheaton** [comment]
> @joewheaton and @philipbaileynar - when asking for "symbology" we need to think about how this is implemented in RIPT as opposed to RAVE? are we developing .qml's? or some other means as symbology in RIPT may be implemented in pyQGIS?

Excellent point @nick4rivers. I am pretty confident that we will re-use the exact same functionality from qRAVE in RIPT. In other words, yes to `*.qml`. However, I will defer to @philipbaileynar on the rest. The business logic might be too static to deal with the flexibility we're after here. We may need to do something more similar to GCD, which to the user will feel just like a tree in RAVE, but how we plumb it might be similar to the *.gcd file. I don't know... I will defer to @philipbaileynar on that.

**Comment by philipbaileynar** [comment]
I have removed assignment and milestone while we refocus on getting to version 1.0 and funded features.

**Comment by joewheaton** [comment]
> I have removed assignment and milestone while we refocus on getting to version 1.0 and funded features.

Technically @philipbaileynar, you already built a version of this with the Zonal Statistics feature.
