### ISSUE TITLE
Post release as Zip File

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/QRiS#72]
Ask @MattReimer for standard for how to post releases in this repo in addition to putting it in the Plugin Store.

**Comment by MattReimer** [comment]
There really isn't anything to it. Just create a github release, put in any version notes and attach the exact same zipfile you uploaded to OSGEO website.

https://github.com/Riverscapes/QRAVEPlugin/releases

**Comment by nick4rivers** [comment]
Done: https://github.com/Riverscapes/QRiS/releases/tag/v0.1.0
