### ISSUE TITLE
ZOI Influence Documentation

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#78]

**Comment by nick4rivers** [comment]
**_Here is the description of original issue:_**

We will prepare documentation that explains how this list can be amended to anything. We will give specific examples of using the verbs of  specific hydrologic, hydraulic, geomorphic and biologic processes but point out this results in way too many polygons which overlap, over and over. So great learning tool, unnecessary.

**Comment by joewheaton** [comment]
Protocol addresses.
