### ISSUE TITLE
Riverscape Definitions

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#79]
**_Riverscape definitions_** will be the non-temporal (i.e., static and not part of an assessment) riverscape segments. They will be based primarily on valley bottom bottom polygons (so could be imported from VBet).

This issue should focus specifically on defining the database schema and the skeleton within the QRiS tree. Sub-issues below should be created as needed for much of the Riverscape Definitions functionality.

Breakdown in the QRiS Tree should be as follows (Context menu options)

- Riverscape Definitions
   - Valley Bottom Extents (Add Blank Valley Bottom, Import VBET Output, Import Layer)
      - _my valley bottom_ (Add to Map, Add Blank Centerline, Import Centerline, Run Centerline Tool, Edit Details, Delete)
         - Centerlines
            - _my centerline 1_ (Add to Map, Edit Details, Delete)
            - _my centerline 2_ 
       - _my other valley bottom_
       - _my third valley bottom_
    - Valley Bottom Transects (Add Blank Transects, Import Transect Layer, Generate Transects from Centerline)
       - _my special transects_ (Add to Map, Edit Details, Delete)
       - _my 500 m transects_
    - Reach Segments (Add Blank Segments, Import Layer, Generate from Valley Bottom and Transects)
       - my cool segments (Add to Map, Edit Details, Delete)
       - my cooler segments

## Additional Functionality
_Create new issues from these as needed._

- [ ] Generate Segments from Valley Bottom and Transects
- [ ] Add import from VBET project for valley bottom extents.
- [ ] All Layer CRUD Functionality
- [ ] Run centerline tool

**Comment by nick4rivers** [comment]
@philipbaileynar - I ported our conversation from yesterday over here - this is basically analogous to what we specified in: [https://docs.google.com/document/d/1BGWLjnTackiD6ACbkde3QBERJlun33EQXVr1cmS3mCg/edit#](https://docs.google.com/document/d/1BGWLjnTackiD6ACbkde3QBERJlun33EQXVr1cmS3mCg/edit#)

**Comment by nick4rivers** [comment]
Here is the initial skeleton in the QRiS tree:


<img width="327" alt="Screen Shot 2022-04-21 at 12 54 48 PM" src="https://user-images.githubusercontent.com/34071692/164542254-3ecf3347-22b5-4837-9d99-0bc3650727f4.png">

**Comment by nick4rivers** [comment]
THis issue is going to change drastically and will likely be deleted.

**Comment by joewheaton** [comment]
Before we close this issue, we should revisit it now with 0.2.1 in mind. This is notionally now dealt with in the new Mask Library, but we need to revisit this. We still need VB segments (i.e. Directional Masks) and centerlines and maybe even stationing (i.e. bring over VBET stuff). I know @nick4rivers and @nbouwes are going to want transects and segments too (remember GCD). Anyhow, it is good to remind ourselves we have had these discussions.

**Comment by joewheaton** [comment]
I think this is superseded now.
