### ISSUE TITLE
Riverscape Width Attribution

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#8]
This RIPT feature will allow attributing a valley center line with the width of specified riverscape surfaces. It is intended to assist with visualizing the width of riverscape surfaces (e.g., valley bottom, width at 1 m elevation above channel, active channel) at large spatial scales where polygons are not effective. The feature depends on spatial data extracted from RIPT features described in issues #6 and #7.

This feature is assigned to @KellyMWhitehead. @philipbaileynar - I can't seem to assign issues?

The example shown below demonstrates the inputs and functionality of this RIPT feature.
 - Cross sections / transects have been created at a specified frequency perpendicular to a valley center line.
 - The transects will be used to obtain widths of one or more riverscape feature polygons exported from issue #7.
 - Finally, the centerline will be segmented at a specified length (e.g., 100m) and attributed with an integrated / average (we need to discuss this) width of the transects overlapping each segment.

![example](https://user-images.githubusercontent.com/34071692/121213511-2257d180-c833-11eb-9b32-331f56037a73.jpeg)

**_Inputs:_**
 - a valley bottom center line covering the area of interest.
 - riverscape surface area polygons. These will in many cases be a product of #7.

**_Parameters_**
 - user specified transect / cross-section frequency, e.g., every 10 m.
 - user specified valley bottom segment length e.g., segment every 100 m.

**_Output_**
 - The output initially can be very simple. A single geopackage with a feature class for the segmented valley bottom line attributed with the segment length and transect frequency specification. Additional attributes would correspond to the name of each valley bottom surface (e.g., valley bottom, 1m elevation, etc....).

![Screen Shot 2021-06-08 at 8 40 39 AM](https://user-images.githubusercontent.com/34071692/121215845-369cce00-c835-11eb-8864-9730bbd35f79.png)

**Comment by joewheaton** [comment]
I like this request (nice spec @nick4rivers) ... A reminder to @KellyMWhitehead, @nick4rivers  and @philipbaileynar to think about whether this falls all on @KellyMWhitehead or can be tasked out (i.e. create actionable tasks as checkboxes that can be checked off before issue is closed with ` - [  ]` notation) within this ticket to mix of two of you.

**Comment by nick4rivers** [comment]
Also - this closely overlaps #19, which is currently in the works. We may bag this one but I'll leave it here for now.

**Comment by philipbaileynar** [comment]
Note that we now have the ability to generate cross sections from centerlines. 

Removing assignment and milestone while we re focus on funded features for version 1.0
