### ISSUE TITLE
Raster Project Layer Import

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#80]
Allow importing and clipping of raster project layers into the scratch space

**Comment by joewheaton** [comment]
@philipbaileynar, I think we can close this when you give me 0.1.3 and Scratch Space is back?  I think this functionality is also sort of in the Basemaps too, when rasters are used as basis for DCE:
![image](https://user-images.githubusercontent.com/9723905/192114827-d9e58007-8dd3-4c9a-a074-096f856ff7d1.png)

So the Cip to Mask is doing this:
![image](https://user-images.githubusercontent.com/9723905/192114870-06bf203f-e3b3-44de-a6e2-aab4924cdc06.png)

I think this will also be the option inside the Scratch Space import to.
