### ISSUE TITLE
Adding Event to Map Error

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#87]
# Steps to Reproduce:

1. Create new project.
2. Add new Data Capture Event
    1. I chose just the RIM protocol
4. Right click on the new event in the project tree and click "Edit".

# Observed

See screenshot:

<img width="1683" alt="Screen Shot 2022-08-08 at 9 25 22 AM" src="https://user-images.githubusercontent.com/8645379/183466272-13d943f4-01aa-4c26-9941-591724dfa9d9.png">

**Comment by philipbaileynar** [comment]
Does not occur in 0.1.5.alpha

**Comment by joewheaton** [comment]
> Does not occur in 0.1.5.alpha

Confirmed and tried to reproduce in 0.1.5. Editing seems to work now.
