### ISSUE TITLE
Cannot Edit Event

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#88]
# Steps to reproduce

1. Create new project
2. Create new event. I chose RIM protocol.
3. Click OK.
4. Right click on event in QRiS tree and click "Edit".

# Observed

Click OK on edit form and nothing happens!

<img width="633" alt="Screen Shot 2022-08-08 at 9 27 41 AM" src="https://user-images.githubusercontent.com/8645379/183466799-065d1fe9-475c-4aa8-b005-b608c1c2a0bd.png">

**Comment by nick4rivers** [comment]
I'm actually getting an error when I try to edit events:

<img width="1594" alt="Screen Shot 2022-08-10 at 9 31 58 AM" src="https://user-images.githubusercontent.com/34071692/183965201-2fd4c77f-0225-4501-ba63-13829c9855fa.png">

**Comment by kunztr** [comment]
@nick4rivers Did this error occur before or after we met to sort out the repository this morning? Is it still giving you this error?

**Comment by philipbaileynar** [comment]
Working in 0.1.3alpha
