### ISSUE TITLE
Error Adding Event (Structural Element)

### ISSUE THREAD

**Issue by kunztr** [Riverscapes/QRiS#92]
Error is thrown when adding a Structural Elements event to the map

Replication Instructions:
1. New Project
2. New Data Capture Event
3. Check 'Structural Elements' in the protocols
4. Add to Project
![Screenshot 2022-08-08 145753](https://user-images.githubusercontent.com/50641266/183513324-0d50b874-f267-4396-8ffc-5d1ef1f357e9.png)

**Comment by philipbaileynar** [comment]
@Cashe93 can you please upgrade to the latest version of QRiS, [0.1.5.alpha](https://github.com/Riverscapes/QRiS/releases/tag/0.1.5-alpha) and test again. Please report back here if it still happens or close this issue if it does not.

**Comment by Cashe93** [comment]
Was this intended for @kunztr?

**Comment by philipbaileynar** [comment]
Yes, my bad. Thanks @Cashe93

**Comment by kunztr** [comment]
@philipbaileynar It looks like you already closed the issue, but just in case, I upgraded to 0.1.5.alpha and the error is fixed.
