### ISSUE TITLE
Error on new DCE without Date

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#93]
Hey, I get a Type Error when adding a new DCE and not specifying a complete start and end date.

This should at a minimum just prompt for a date and not send an error. However I don't think that we actually need a complete date for each DCE?
<img width="1217" alt="Screen Shot 2022-08-09 at 11 33 37 AM" src="https://user-images.githubusercontent.com/34071692/183735646-e28cc303-1780-4d2e-af2d-c143eb8ef594.png">

**Comment by philipbaileynar** [comment]
@kunztr this is blocking everyone!

**Comment by kunztr** [comment]
@nick4rivers @philipbaileynar I just removed the DCE date logic that requires all date fields.

**Comment by joewheaton** [comment]
It seems like this is fixed. Can someone (@kunztr or @philipbaileynar) reference this issue in the commit and close this?

**Comment by philipbaileynar** [comment]
Sorry, this was fixed several weeks ago. It was a very minor bug that only existed for a day or two.
