### ISSUE TITLE
Basemaps adding to Masks Group in Layer Tree.....

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#94]
Hey, seems like Basemaps are being added to the Masks group using the 'Add to Map' function....

<img width="501" alt="Screen Shot 2022-08-10 at 9 02 09 AM" src="https://user-images.githubusercontent.com/34071692/183958720-681502ee-8235-41c1-a0f4-b2c84b3b7682.png">

**Comment by philipbaileynar** [comment]
I fixed this last night. Do a pull on dev. Please close when you see it fixed.

**Comment by philipbaileynar** [comment]
Fixed in 0.1.3.alpha
