### ISSUE TITLE
Watershed Attribute Report

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/QRiS#95]
1. Start new clean Python script
2. Include the [RST report module](https://stackoverflow.com/questions/30735665/displaying-a-temporary-html-file-with-webbrowser-in-python)
3. Main routine:
    - load [JSON file](https://github.com/Riverscapes/QRiS/files/9328726/metrics_rst.json.zip) into Python data structure
    - create new report object.
    - add a single table from the JSON data (see below)
    - save/write the HTML to file (to literal static file path for now)

## Snippets

Load JSON into Python data structure:

```python

import json

with open(`C:\myfile.json`) as f:
    data = json.loads(f.read())
```

## First Sample Table

Please make a table and graphic of slope! All numbers below are fake (areas and percentages don't add up).

The source JSON data should be available in the Python structure at:

data['project']['metrics']['raster']['floatingPoint']['SLOPE']

Bin|Area (ha)|Percent (5)
---|---|---
0-5%|4,025|7%
5.001-10%|12,035|50%
10.001-15%|765|1%
15.001%|0|0%

And put a nice MatPlotLib pie chart below this (see existing riverscapes report class or plotting library. Do not write this from scratch!)

**Comment by joewheaton** [comment]
Is this still relevant @philipbaileynar? If so, please reassign.

**Comment by joewheaton** [comment]
No longer relevant?
