### ISSUE TITLE
Add to Map on New DCE

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#96]
New DCE's don't add to the map on creation even when the checkbox is checked:

<img width="1124" alt="Screen Shot 2022-08-15 at 12 49 28 PM" src="https://user-images.githubusercontent.com/34071692/184707445-fbeeebe9-95bf-41e9-a822-a277752b2c9a.png">

**Comment by philipbaileynar** [comment]
Fixed for 0.1.3-alpha
