### ISSUE TITLE
Basemaps in Tree and Dce's

### ISSUE THREAD

**Issue by nick4rivers** [Riverscapes/QRiS#98]
If basemaps are exposed under the DCE node in the QRiS tree it seems like they should be nested under each DCE and only show basemaps that are specific to that Dce. As of now they are just inline with the other Dce nodes.

<img width="464" alt="Screen Shot 2022-08-15 at 1 01 19 PM" src="https://user-images.githubusercontent.com/34071692/184708751-0aef779e-25a3-4279-932b-68ffe57121d8.png">

**Comment by philipbaileynar** [comment]
Moot now that we no longer show basemaps under DCE
